### ISSUE TITLE
Editor.wrapNodes does NOT trigger normalize node on wrapped Leaf

### ISSUE THREAD

**Issue by flavordaaave** [ianstormtaylor/slate#3758] opened 2020-07-01 20:04 UTC
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

1.) Wrap some text with a mark within e.g. a link
2.) `normalizeNode` is executed for the `link` node up
=> The wrapped lead is NOT normalized
3.) When typing within the wrapped node, the normalizer is finally triggered and normalization is applied.

![CxXknLFuXX](https://user-images.githubusercontent.com/5305150/86286427-b7475900-bbe6-11ea-81e1-854fda2acecc.gif)

[Codesandbox](https://codesandbox.io/s/slate-wrapnodes-not-normalizing-leaf-qvgql?file=/src/examples/links.tsx:1212-1249)

Slate: 0.58.3
Browser: Chrome
OS: Mac

#### What's the expected behavior?

When wrapping nodes, alls nodes underneath the wrapper should be normalized

**Comment by flavordaaave** [comment] 2020-07-01 20:16
Changing an element's type using `Editor.setNodes` also does NOT trigger normalization...

**Comment by BrentFarese** [comment] 2020-07-24 20:47
The real issue here is that no `DIRTY_PATHS` are calculated for the operations you mention for nodes below where the operation occurred.  This is by design though, I think.  The basic assumption is that the node inside the wrapping has not changed so why does it need to be normalized?

I am not sure I agree with that either but that is the reasoning...

A better solution for Slate users might be to make `getDirtyPaths` a function that is overridable, just like `editor.normalizeNode`.  Then, if you wanted to opt-out of Slate's behavior that is already backed in, you could by providing a `getDirtyPaths` function override that includes the paths you want to normalize, and a custom function in `editor.normalizeNode` to normalize those nodes.

Do you want to take a stab at a PR?

**Comment by BrentFarese** [comment] 2021-01-14 05:45
@flavordaaave going to close this as #4012 now allows users to customize `getDirtyPaths`.  So, if you need the wrapped node to be normalized in your particular implementation, then you can add it in by customizing `getDirtyPaths`.

Since I can't say for certain in **_all_** cases that all descendants of a wrapped node should be normalized, I'd rather leave it to the particular implementation then add it to core.  If wrong and many users have this same need, glad to add to core's `getDirtyPaths` function as a default.  Thanks!

Fixed by #4012.

**Closed by BrentFarese** 2021-01-14 05:45 UTC
