### ISSUE TITLE
Selection in not collapsing when a void inline is in the editor

### ISSUE THREAD

**Issue by alizeaiter** [ianstormtaylor/slate#2230] opened 2018-10-05 17:02 UTC
The entire text selection seems to move when going right when a void inline is on the right.The same thing happens when the void inline is on the left.
![gifslate](https://user-images.githubusercontent.com/20495861/46549069-23d9da80-c8d1-11e8-86e9-9d59b8799dcc.gif)

https://jsfiddle.net/fj9dvhom/2384/

**Comment by skogsmaskin** [comment] 2018-10-05 17:34
Thanks for reporting @alizeaiter.

Closing this as it is a duplicate of https://github.com/ianstormtaylor/slate/issues/2069

**Closed by skogsmaskin** 2018-10-05 17:34 UTC
