### ISSUE TITLE
Unexpected behavior in Firefox when copy & pasting text.

### ISSUE THREAD

**Issue by absorber** [ianstormtaylor/slate#2612] opened 2019-02-24 07:15 UTC
#### Do you want to request a _feature_ or report a _bug_?

Bug.

#### What's the current behavior?

Video: https://youtu.be/PyEqFUY8X3k

In Firefox, when I paste (rich) text copied from a website (I used [this](https://en.wikipedia.org/wiki/Software_bug) as an example) the pasted text can not be removed.

Steps to reproduce:

0. Go to a random Wikipedia article (in my example I went to [here](https://en.wikipedia.org/wiki/Software_bug))
1. Select and copy text in that Wikipedia article.
2. Paste it into the text input field of https://jsfiddle.net/fj9dvhom/1/
3. Select all of the text you have pasted into the text input field (I did Ctrl+a)
4. Press the Backspace or Delete key.

Similar thing happens in https://www.slatejs.org/#/rich-text but with a more descriptive error message. See [this](https://github.com/vector-im/riot-web/issues/7062#issuecomment-466739810) comment.

Info about my system:
* OS: Ubuntu 16.04 64bit with i3wm and without a compositor.
* Browser: Firefox 65.0 64bit
* Slate version: Whatever is the version as of 2019-02-24 in JSFiddle.

#### What's the expected behavior?

Pasted text can be deleted.

**Comment by ericedem** [comment] 2019-02-25 16:04
I'm not able to reproduce this in firefox in either the fiddle or in the slate rich text example.

From the video it looks like copy / paste is somehow pulling all the formatting HTML out of wikipedia and injecting it into slate. In mine all the html is stripped out and it is inserted as plain text. I wonder if this is a difference between OSX (what I'm using) and linux.

**Comment by non-Jedi** [comment] 2019-02-25 16:21
Assuming this is the same bug as over at vector-im/riot-web#7062, most of the complaints have come from linux user although one user was able to reproduce with Firefox on Windows.

**Comment by ianstormtaylor** [comment] 2019-11-28 03:08
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Closed by ianstormtaylor** 2019-11-28 03:08 UTC
Labels: bug, ♥ help
