### ISSUE TITLE
refactor handlers to take `data` instead of `event, data, editor`

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#511] opened 2016-12-09 01:08 UTC
This isn't a near-term thing, but I think the current pattern of `handler(e, data, state, editor)` is not great from an encapsulation standpoint:

- The `event` parameter means that plugins are tightly coupled to React's event implementation if they use any of the React-specific properties. Which means that using Slate with Preact or even a less React-like view layer is impossible.

- The `editor` parameter means that plugins are tightly coupled to the view layer in general, which adds unnecessary complexity when trying to write simple tests, and generally just allows for bad patterns.

Instead, I think the "ideal" would be for all of the current uses of `event` and `editor` to be encapsulated into a Slate-specific argument, which would be an instance of `Slate.Event` and probably be called `event` colloquially.

This new `event` object would have:

- All of the existing properties in `data`. 
- Many DOM event-specific properties (`preventDefault`, `stopPropagation`, `which`, `isDefaultPrevented`, `isPropagationStopped`, etc.) that allow for all of the current functionality and behaviors, but without being specifically tied to React.
- A few editor-specific accessors (`getState`, `getSchema`, etc.) that allow for async operations, or plugin-specific logic to occur.

So we'd end up with something like:

```js
function onKeyDown(state, event) {
  if (event.shiftKey) return
  if (event.key != 'a') return 
  if (state.startBlock.type != 'image') return

  setTimeout(() => {
    const state = event
      .getState()
      .transform()
      .blur()
      .apply()

    event.setState(state)
  }, 1000)
}
```

**Comment by thesunny** [comment] 2016-12-10 17:27
I think I remember in another issue, it was proposed to remove the state argument since (a) it can be derived from `editor` and (b) doing so would reduce the chance of errors in async operation where it is easy to use the outdated  `state` instead of using `editor.getState()`.

I may be missing something. Is there a reason to pass state separately?

Also, I wonder if it would be worthwhile to have an `event.transform()` method since `transform()` is so commonly used.

**Comment by ianstormtaylor** [comment] 2016-12-10 19:41
@thesunny you're right, although that's from https://github.com/ianstormtaylor/slate/issues/277 where it is in reference to `props.state` in the components. It's deceiving in that case because if `shouldComponentUpdate` returns `false` then `props.state` is old. But in the case of the plugi handlers the `state` argument won't ever be stale, so it's not a worry here.

Since they're primary function is to take the current state and return a new one, I think it should be kept in the arguments. And I actually think I should have made it the first argument to all of the handlers (unfortunately I made the event-based ones `e, data`), so I might fix this in the future.

**Comment by thesunny** [comment] 2016-12-16 11:57
@ianstormtaylor just wanted to add that the idea of encapsulating the event has a lot of merit IMHO and makes the code cleaner. I just overall like the direction of the code becoming cleaner and simpler and the dedication to removing `debt`.

The new `event` object has a lot of benefits including making it easier to write re-usable code.

In particular, it's common to have an external method that takes several arguments then later realizing that you need more arguments that you hadn't passed through. When this happens you need to update the function signature and all the places where the method was called from. With an encapsulated `event` object, developers are guaranteed to have everything they need and so these sorts of refactors become unnecessary.

By the way, thanks for finding and referring to the original issue and it's context.

With respect to keeping the `state` I defer to you and ultimately I don't think it makes too much difference; however, I'd just like to (gently) push back with a few points for your consideration:

**Point 1**

You mentioned that `props.state` would not be stale on an event handler. That may be true at the time it is originally called; however, in your example, you needed to call `event.getState()` in the `setTimeout` callback. So it's not stale at the original time of calling but any deferred calls can have stale `state` and it's potentially the cause of confusing bugs; however, having to call `event.getState()` eliminates the possibility of the bug from ever happening because you can't access the `state` without the function call which is always current.

**Point 2**

While having to call `event.getState()` is more typing and potentially more boilerplate in the code, another benefit is that it makes it easier to refactor code.

Here's a (contrived) example that may demonstrate the issue:

Let's say you write a plugin and in that plugin, when you type `@usercount` it actively replaces the text with the count of actual users at the time. There's also a keyboard shortcut COMMAND-OPT-U.

Since there are two place to call it, we put this into a separate function. It takes `state` and `event` because we pulled the code out of the original event handler.

We realize later that the local user count (in the browser) can be outdated so we need to make a request to a REST service. So because of this, it runs async now. This function is one step away now from the original call and it may not be as clear that `state` will be stale at this point. Assuming here that maybe a different developer is working on this code or it's been a month since you've looked at the code, not realizing that `state` may be stale when the code goes async is a possibility.

But even if we realize it is going to be stale, we have to refactor our code to remove that `state` argument which feels a little redundant because, in essence, we never needed it in the first place.

I don't think it's a huge issue and it probably wouldn't trip me up personally now (since, well, I've written essentially a blog post worth of information on it!)

**Point 3**

You are already reducing the function signature from 4 down to 2. It feels like an `event` object usually carries everything you need to deal with the event.

**Moving Right Along**

Anyways, I'm actually pretty happy even with the current function signature with 4 arguments; however, I felt like it would be worthwhile to present the entirety of the argument for a single `event` object for consideration.

**Comment by ianstormtaylor** [comment] 2016-12-16 18:19
Hey @thesunny I think you definitely have some good points. I'm not totally convinced either way, but I was planning to let this issue sit while I think on it and come across more related concerns, so thanks for the extra info!

**Comment by thesunny** [comment] 2016-12-16 19:21
@ianstormtaylor I'm actually in the same boat. Wanted to bring up some points but I'm actually feeling not that confident in the approach.

I think I'm also conflating the encapsulated event idea, the passing of multiple arguments on the event handler function and the forcing of the call to getState into one.

I just actually had another thought which I'm kinda liking right now.

What if we did this:

```js
function onKeyDown(event, state, editor) {
  // stuff goes here
}
```

where `event` is the new `Slate.Event` type.

The two changes are:

1. Argument Order
2. Uses the new `Slate.Event`

The event includes properties like:

* state
* getState()
* editor
* transform()
* ...all the other stuff you mentioned

One thing I really like is that `state` and `editor` can be used directly from the arguments without assigning to another variable and without the cruft but because of the argument order, it is all actually optional. In essence, they are all convenience arguments.

This is really nice because:

1. It keeps actions that are fully handled in the handler neat. No need to `const {state, editor} = event`

2. However, if we want to pass the `event` object to an external function, we only have to pass the one object around. Because the argument order puts out new `Slate.Event` first, we don't even need to create argument variables for them:

```js
function onKeyDown(event) {
  console.log('calling event handling method')
  specialEventHandlingMethod(event)
}
```

3. The argument list is ordered logically from most likely to be used (the essential `Slate.Event`) to least likely (state then editor). I would suggest that the original React Event is used so rarely that it doesn't get a place in the argument list.

It's also kind of nice in that refactoring code isn't too bad. One just has to find the event handlers and remove the first `e` argument and everything else should work. The 2nd argument would be named `data` instead of `event` but the code would work.

**Comment by ianstormtaylor** [comment] 2017-10-16 20:22
Closing this because with the changes that have happened since it was opened, it's become less necessary, and I actually think there's a better way, which is what #1240 presents.

**Closed** 2017-10-16 20:22 UTC
Labels: idea
