### ISSUE TITLE
Spell-check is editing on wrong range in markdown example

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#2015] opened 2018-08-01 01:52 UTC
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

As shown below, spell-check in previewing is making a wide-range change in markdown example:
![](http://g.recordit.co/OgoR6YWzpZ.gif)

#### What's the expected behavior?

Shall only affect the `previewing` last word in the previous example.

**Comment by Slapbox** [comment] 2018-08-05 04:53
Confirming this is an issue in Chrome 68 on Windows.

**Comment by Slapbox** [comment] 2018-08-05 04:54
This is probably caused by https://github.com/ianstormtaylor/slate/issues/1419

**Comment by ianstormtaylor** [comment] 2019-11-28 02:42
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Closed by ianstormtaylor** 2019-11-28 02:42 UTC
Labels: bug, ♥ help
