### ISSUE TITLE
cmd+a + cmd+x doesn't work in rich text example

### ISSUE THREAD

**Issue by geakstr** [ianstormtaylor/slate#2309] opened 2018-10-24 06:41 UTC
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
cmd+x doesn't work in rich text example

#### What's the expected behavior?
cmx+x works

![ezgif-4-99749bb270d5](https://user-images.githubusercontent.com/1496368/47411195-06ce5400-d779-11e8-8093-cd019af494cf.gif)

P.S. I noticed other similar troubles with corrupted documents in my project too, but not investigated yet.

**Comment by Slapbox** [comment] 2018-10-24 14:49
Duplicate of #2279

**Comment by zhujinxuan** [comment] 2018-10-24 15:16
I find the reason. When delete all, the paragraph will include no leaves.   Then moveToStart have no place to move.

It shall be fixed if 
1. we normalize node before moveToStart
2. trying to have a better strategy for deleteAll.

**Comment by Slapbox** [comment] 2018-10-24 15:41
@zhujinxuan - I believe this rule should prevent empty paragraphs. I suspect it is not being applied. https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/plugins/core.js#L97-L107

I suspect the majority of all issues from the past week are caused by the schema rules not being properly applied.

**Comment by zhujinxuan** [comment] 2018-10-24 15:43
@Slapbox I am unsure how the Ctrl-X and backspace is handled differently.  It seems backspace works after C-a, but C-x does not work after C-a

**Comment by Slapbox** [comment] 2018-10-24 15:47
Great point.

**Comment by zhujinxuan** [comment] 2018-10-24 15:55
Hi @Slapbox @ianstormtaylor  Is `cmd+x` is not defined in slate-hotkeys?  I cannot see the binding.

**Comment by Slapbox** [comment] 2018-10-24 16:16
I guess it's not. Looking through the history I guess it's never been. If it was there it would be in as `mod+x`.

**Comment by Slapbox** [comment] 2018-10-24 16:42
This is the line that crashes things: https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/utils/clone-fragment.js#L133

**Comment by zhujinxuan** [comment] 2018-10-24 17:20
@Slapbox  Oh, I see.  It  is fixed in https://github.com/ianstormtaylor/slate/pull/2298

**Comment by Slapbox** [comment] 2018-10-24 23:32
This is greatly improved in the latest releases, which include #2298, but it's not perfect.

@kalley

### New Behavior

Cutting the entire contents does not crash the editor, and does copy the contents to clipboard, but it does not clear out the editor and it throws the following error:

`Uncaught Error: `Node.assertNode` could not find node with path or key: List [ 1 ]`

**Comment by skogsmaskin** [comment] 2018-10-25 00:46
> 
> `Uncaught Error: `Node.assertNode` could not find node with path or key: List [ 1 ]`
> 

This is probably https://github.com/ianstormtaylor/slate/issues/2291#issuecomment-432871992

**Comment by Slapbox** [comment] 2018-10-25 01:00
@skogsmaskin I agree. My mistake.

**Comment by steobrien** [comment] 2018-10-25 20:44
I think this has been fixed – can no longer reproduce at https://www.slatejs.org/#/rich-text.

Perhaps this had the same root cause as https://github.com/ianstormtaylor/slate/issues/2291?

**Comment by Slapbox** [comment] 2018-10-25 21:06
It would appear so!

**Closed** 2018-10-25 21:19 UTC
Labels: bug, ♥ help please
