### ISSUE TITLE
withoutNormalizing still runs editor.normalizeNode

### ISSUE THREAD

**Issue by flavordaaave** [ianstormtaylor/slate#3467] opened 2020-01-24 16:12 UTC
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

![](http://g.recordit.co/20yZzCwVUx.gif)

[Codesandbox](https://codesandbox.io/s/slate-05x-l8vx8?fontsize=14&hidenavigation=1&theme=dark)

Slate: 0.57.1
Browser: Safari
OS: Mac

#### What's the expected behavior?

The node should be toggled to have type `invalid` since the `Transform.setNodes` is wrapped within an `Editor.withoutNormalizing` (in the example code it would be rendered red)

**Comment by CameronAckermanSEL** [comment] 2020-02-22 16:55
Hey @flavordaaave , if the issue you're reporting is that withoutNormalizing is not leaving the node in an unnormalized state, then this is by design and is more a problem with the name of withoutNormalizing. A new name would would probably be a better solution.

Going to close this issue, but please feel free to continue the discussion.

**Closed by CameronAckermanSEL** 2020-02-22 16:55 UTC
Labels: discussion

**Comment by flavordaaave** [comment] 2020-03-09 12:03
@CameronAckermanSEL No, the issue I have is that I can NOT get the state into an invalid state even though I'm using `withoutNormalizing`.

You can have a look at my codesandbox above:
Basically I'm trying to set my nodes to type `invalid` but when I do so, the normalizer is run and prevents it from beeing transformed to `invalid`:

```
Editor.withoutNormalizing(editor, () => {
  Transforms.setNodes(editor, {
    type: "invalid"
  });
});
```

Steps to reproduce in codesandbox:
1) Mark text `This node should be toggled into invalid type without normalizing.`
2) Click `toggle to invalid` button
3) Normalizer is run and alert is visible

Expected behavior:
3) Normalizer is NOT executed (since transformation is wrapped within `Editor.withoutNormalizing` AND the node is transformed to type `invalid` (which renders red text)

**Comment by CameronAckermanSEL** [comment] 2020-03-09 14:59
Hi @flavordaaave. What I’m trying to explain to you is that `withoutNormalizing` defers normalization to the after the passed in delegate function is complete. *It does not turn off normalization*. And *there is no feature that turns off normalization*. The absence of such a feature is completely intentional and by design.

**Comment by flavordaaave** [comment] 2020-03-09 16:01
@CameronAckermanSEL Ok, got it. Thanks for the explanation.
