### ISSUE TITLE
Composition text bugs with placeholder

### ISSUE THREAD

**Issue by knubie** [ianstormtaylor/slate#3686] opened 2020-05-14 13:36 UTC
### What's the current behavior?
When using IME to type with placeholder text present, the placeholder text movies with the IME input instead of begin removed. Once IME completes, behavior varies by browser:

**_Chrome:_**
Raises the following error:
```
Cannot resolve a Slate point from DOM point: [object Text],5
```
If the error is caught, the composition text is inserted correctly.

**_Safari_**
Composition text is inserted correctly, but cursor is placed at the beginning of the input.

**_Firefox_**
Composition text is inserted twice. Adding additional text / modifying the slate state in any way will raise an error:
```
Cannot resolve a DOM point from Slate point: {"path":[0,0],"offset":11}
```
See: #3824

Slate: v0.58.1
Browser: Chrome / Safari / Firefox / Edge
OS: Mac / Windows / Linux / iOS / Android

### What's the expected behavior?
1. Placeholder text should be removed as soon as composition starts.
2. Completing the composition should insert the composition text and place the cursor at the end of the inserted text.

Duplicate of #3369

**Comment by swanf** [comment] 2021-03-01 08:06
Any updates please?

**Comment by swanf** [comment] 2021-03-01 08:14
ok, I found a workaround:
```ts
    const onComposition = (e: React.CompositionEvent<HTMLDivElement>) => {
        if (e.type === "compositionstart") {
            setComposition(true);
            if (value[0].children.length === 1 && value[0].children[0].text === "")
            ) {
                setIsPlaceholderRemove(true);
                editor.insertText(" "); // important, this will be added at the head of the composition text and change the visibility of placeholder
            }
        } else if (e.type === "compositionend") {
            setComposition(false);
            if (isPlaceholderRemove) {
                editor.deleteBackward("character"); // remove the space " " we just added
                setIsPlaceholderRemove(false);
            }
        }
    };
```

**Comment by neko-neko** [comment] 2021-08-13 14:04
I was not able to reproduce the problem on 0.65.3. Probably fixed in https://github.com/ianstormtaylor/slate/pull/4352.

**Closed** 2021-08-13 14:29 UTC
Labels: bug, ♥ help, ⚑ ime
