### ISSUE TITLE
The `move_node` operation doesn't invert properly

### ISSUE THREAD

**Issue by justinweiss** [ianstormtaylor/slate#1469] opened 2017-12-13 23:15 UTC
#### Do you want to request a *feature* or report a *bug*?

Report a bug.

#### What's the current behavior?

Fiddle is here: https://jsfiddle.net/fj9dvhom/21/

Wait one second, and you'll see an error in the console: `Error: Could not find a descendant at path "2,1".`

#### What's the expected behavior?

There should be no visible change, since we performed an operation and immediately ran the inverse.

This happens because moving a node changes the structure of the document, but `move_node` ignores that structure change when it inverts the operation. For example, the inverse of

`{type: "move_node", path: [1], newPath: [2, 1]}`

should be

`{type: "move_node", path: [1, 1], newPath: [1]}`

I can try to fix this.

**Comment by emilbruckner** [comment] 2017-12-27 10:12
Duplicate of #1406

**Closed** 2017-12-29 18:57 UTC
Labels: bug
