### ISSUE TITLE
Adding Image Block Doesn't Trigger OnDocumentChange?

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#553] opened 2017-01-15 16:43 UTC
When I add an image block it doesn't trigger OnDocumentChange. When I add some text after, it does. Any ideas? Bug? Implementation error?

Thank you.

**Comment by ianstormtaylor** [comment] 2017-01-17 18:16
Hey @Slapbox can you include a smallest-possible test case that shows this behavior in a JSFiddle? That will help people resolve the bug much more. If you check out the [`Contributing.md`](https://github.com/ianstormtaylor/slate/blob/master/Contributing.md) file there's a template you can use to get started. Thanks!

**Comment by Slapbox** [comment] 2017-01-22 18:09
I'm a little embarrassed to say, I don't know how to use JSFiddle in conjunction with npm packages.

Recreating this one locally is really simple though. If you just run your [slate-drop-or-paste-images ](https://github.com/ianstormtaylor/slate-drop-or-paste-images) example and add in a function as below and then reference it in your return statement with `onDocumentChange={this.onDocumentChange}`

```
onDocumentChange = () => {
    console.log("Document Change")
  }
```

You'll notice that when you paste in an image, onDocumentChange is not firing.

As an aside, I tried originally simply adding first, rather than writing a function, `onDocumentChange={console.log("Document Change")`, but this triggered whenever anything in the editor changed. Even just mouse clicks.  This is probably for known reasons beyond what I understand, but in case this is a related finding, I figured I would mention it.

**Comment by eelsweb** [comment] 2017-01-30 00:50
Here's how to reproduce this:

Go [here](http://slatejs.org/#/images)

Go to the bottom of the editor and click on the add image icon. After the image is added, there is no new space at the bottom of (or above) the image.

There is another associated bug in the images example code -

Now press the back key and then press enter. Two new lines are inserted - meaning one paragraph was inserted above the image rather than below it. Try pressing the backspace key - This also inserts a line rather than deleting it. (Since a paragraph node is inserted above the image)

**Comment by jrtilson** [comment] 2017-02-08 16:58
I'm seeing the same as @eelsweb. Additionally, on the image demo if you remove all content from the editor then drop in a new image, there is no space below and you can no longer enter any text. (Due to lack of blocks above or below)

**Comment by jrtilson** [comment] 2017-02-08 18:31
#538 appears to be the same issue. In the image example, the image is inserted as a block, block's don't appear to be calling onDocumentChange at all.

**Comment by ianstormtaylor** [comment] 2017-02-28 23:26
Should be fixed by https://github.com/ianstormtaylor/slate/commit/1511d9f203455734065246d729bd8fb07cff264e

**Comment by Slapbox** [comment] 2017-03-01 03:02
Ian you are a gentleman and a scholar. Thanks very much for this.

**Comment by conorcussell** [comment] 2017-04-19 17:05
Sorry to bring this one back up. But I don't think the changes made have fixed the issue. Here is a fiddle showing that with version 0.19.18 `onDocumentChange` is not called when adding an image, it is also broken on the examples in the repo: 

https://jsfiddle.net/r0yv536x/1/ 

I've dug around in the code a bit, and this condition [`state.document != document`](https://github.com/ianstormtaylor/slate/blob/master/src/components/editor.js#L231) is not `true` when you are inserting an image in the manner shown in the examples. 

I haven't really got my head around a lot of the internals yet, but this seems to be happening because [`cacheState`](https://github.com/ianstormtaylor/slate/blob/master/src/components/editor.js#L165) is being called before [`onChange`](https://github.com/ianstormtaylor/slate/blob/master/src/components/editor.js#L222), meaning the documents are already equal and `onDocumentChange` is not being called for inserted blocks. 

For transforms like the [images example's `insertImage`](https://github.com/ianstormtaylor/slate/blob/master/examples/images/index.js#L273) it seems they execute in this order

1. `componentWillReceiveProps`
2. `cacheState`
3. `onChange`

Whereas for transforms which trigger `onDocumentChange` it doesn't receive props before `onChange` is called

1. `onChange`
2. `onDocumentChange`
3. `cacheState`

I'll try and dig a little further into this tomorrow so will report back if I can work out what is going wrong.

**Comment by erquhart** [comment] 2017-06-20 19:53
There's a good chance that this and #614 are the same issue. I posted a workaround there for anyone that needs it.

**Comment by ianstormtaylor** [comment] 2017-06-21 21:24
Closing in favor of #614

**Closed by ianstormtaylor** 2017-06-21 21:24 UTC
Labels: bug
