### ISSUE TITLE
on Chrome, shift-arrow down then delete doesn't delete text

### ISSUE THREAD

**Issue by jaked** [ianstormtaylor/slate#4496] opened 2021-09-08 02:13 UTC
**Description**
If you position the cursor at the beginning of a paragraph, shift-arrow down, then press delete, the text should be deleted. On HEAD on Chrome, instead the cursor moves to the previous line and the text is not deleted.

I bisected the issue to https://github.com/ianstormtaylor/slate/commit/2d1aaafa from #4455. Not sure what the problem is. I see that the change affects Chrome only, and I tested on Safari; the bug is not present.

**Recording**
Bug at https://github.com/ianstormtaylor/slate/commit/2d1aaafa :

![Bug](http://g.recordit.co/MfP3aKW9He.gif)

Correct behavior at previous commit https://github.com/ianstormtaylor/slate/commit/8eb1abac :

![Correct](http://g.recordit.co/nB93ldYtDn.gif)

**Sandbox**
https://www.slatejs.org/examples/richtext

**Steps**
To reproduce the behavior:
1. position the cursor at the beginning of a paragraph
2. shift-arrow down to select paragraph
3. press delete
4. see that the cursor moves to the previous line and the text is not deleted

**Expectation**
Text should be deleted.

**Environment**
- Slate Version: HEAD
- Operating System: MacOS
- Browser: Chrome 93.0.4577.63

**Comment by TheSpyder** [comment] 2021-09-08 05:26
Duplicate of #4492

**Closed by TheSpyder** 2021-09-08 05:26 UTC
Labels: bug, ⚑ cross platform
