### ISSUE TITLE
Transform interferes when click+dragging selection

### ISSUE THREAD

**Issue by mjadobson** [ianstormtaylor/slate#933] opened 2017-07-14 17:46 UTC
#### Do you want to request a *feature* or report a *bug*?

Bug

#### What's the current behavior?

When there is a node updated while selecting text via click + drag, the selection be interrupted and collapse. Using the keyboard to select a range with shift + arrow keys works fine. Also once the selection has been completed after mouseup, it is fine; it's only during the selection that this bug occurs.

https://jsfiddle.net/2zokvrvt/166/
![](http://g.recordit.co/DqoWLqUGft.gif)

#### What's the expected behavior?

Should be able to select a range of text via click and drag without interference from updating elements.

**Comment by ianstormtaylor** [comment] 2017-11-22 00:54
Hey, thanks for reporting this. I think this is actually a duplicate of https://github.com/ianstormtaylor/slate/issues/1135, so I'm going to close this in favor of that one. Feel free to comment over there with any other info!

**Closed by ianstormtaylor** 2017-11-22 00:54 UTC
