### ISSUE TITLE
deleteBackwardAtRange with empty initial value

### ISSUE THREAD

**Issue by cabaret** [ianstormtaylor/slate#3091] opened 2019-11-04 13:25 UTC
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

My editor has a character limit of 1000 characters. When pasting four blocks of 251, the text gets trimmed properly using `deleteBackward`. However, when pasting 1000+ characters at once, the editor crashes. 

- A JSFiddle that minimally reproduces the issue.
https://codesandbox.io/s/crazy-feistel-9cmjw

(See browser console for the error, codesandbox does not display the error)

- A GIF showing the issue in action.
Pasting more than 1000 chars
![Screen+Recording+2019-11-04+at+02 16+PM](https://user-images.githubusercontent.com/625152/68123664-e699af00-ff0d-11e9-8947-37c338fb1b91.gif)

- Information about your OS, browser, Slate version, etc.
OS X Mojave, Chrome 78, Slate 0.47.8, Slate-React 0.22.9

#### What's the expected behavior?

I expect the editor to trim the pasted text to 1000 characters without crashing.

Note that pasting 1000+ characters works after typing a couple of characters or setting the initial value to some text or a space. The crash only happens when the initial value is an empty string. 

It seems like there's a check missing in `deleteBackwardAtRange` where it attempts to access `node.key` while `node` is null.

I'm not completely sure if the way we impose the character limit is the correct way to do so. If possible, any pointers to improve the code (while avoiding the "bug") are welcome. If not, I am certainly willing to work with you in fixing the issue in the Slate code.

Thanks!

**Comment by CameronAckermanSEL** [comment] 2019-11-05 23:35
This is kind of a tricky one to respond to. I think in general it is an anti pattern (and perhaps even a user error) to have an empty initial value because there are so many unknowns with that state (including selection being impossible or meaningless).  I would recommend that you solve this problem by never allowing an empty editor and always having some default block in there at all times.

There is however nothing in the API that can really guide a user to a point where this condition is impossible because slate does not provide a default schema that dictates a default block. The default block is squarely defined by the user and cannot/should not be provided by slate. Therefore the core library cannot rely on this concept.

Perhaps the best thing to do is to update the guides to indicate that a user is operating in a bad space when they have an empty editor.

**Comment by ryanmitts** [comment] 2019-11-06 08:15
The default "empty" state for this example is a single paragraph block with an empty text node inside. I think that is a reasonable state to have an editor in and expect this to work.

At the time of the paste in the steps of this bug, the selection anchor and focus are both at path [0,0], offset 0, which is the text node within the paragraph block.

It seems the issue is because [this condition](https://github.com/ianstormtaylor/slate/blob/7f5ad9c1fcb04dbe0b07ee0cd61c7bb9e07f240a/packages/slate/src/commands/at-range.js#L836) is causing the node at the current selection to be removed, which invalidates the selection, and then the pasted text replaces it. Therefore, when the schema normalization happens, it's deleting backwards from a selection where the path and offset of the anchor and focus are now null.

I'm not quite sure what that condition is preventing.

**Comment by cabaret** [comment] 2019-11-06 08:39
Thanks for the replies. The default "empty" state of my example is indeed a single paragraph with an empty text node, which I thought would be a reasonable starting state. 

Our use case is that we want to limit the input to a maximum of 1000 characters and cut off anything longer than 1000. I haven't yet looked at an onPaste listener. I might investigate that approach if this will not be considered a bug..

**Comment by CameronAckermanSEL** [comment] 2019-11-06 08:41
It is a great default state, I think I misread

**Comment by cabaret** [comment] 2019-11-07 11:05
When I add a condition in the part @ryanmitts mentioned, the problem seems to be fixed. However, I do not have enough background of the slate code to know if this is a proper fix. 

I've changed this code: ([commands/at-range.js:831](https://github.com/ianstormtaylor/slate/blob/7f5ad9c1fcb04dbe0b07ee0cd61c7bb9e07f240a/packages/slate/src/commands/at-range.js#L831))
```
if (
      !editor.isVoid(startBlock) &&
      startBlock.text === '' &&
      !startBlock.findDescendant(n => editor.isVoid(n))
    ) {
      editor.removeNodeByKey(startBlock.key)
      editor.insertNodeByKey(parent.key, index, firstBlock)
    } 
```

to include the following if-statement:

```
if (
      !editor.isVoid(startBlock) &&
      startBlock.text === '' &&
      !startBlock.findDescendant(n => editor.isVoid(n))
    ) {
      if (firstBlock !== lastBlock) {
        editor.removeNodeByKey(startBlock.key);
      }
      editor.insertNodeByKey(parent.key, index, firstBlock)
    } 
```

The idea behind this being that it should not remove the empty node when it is the only node in the editor. 

Any feedback on this would be greatly appreciated. Thanks!

@CameronAckermanSEL @ryanmitts @ianstormtaylor

**Comment by ianstormtaylor** [comment] 2019-11-28 03:13
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Closed by ianstormtaylor** 2019-11-28 03:13 UTC
