### ISSUE TITLE
Japanese input seems to overlap

### ISSUE THREAD

**Issue by bokuweb** [ianstormtaylor/slate#2595] opened 2019-02-13 02:31 UTC
#### Do you want to request a _feature_ or report a _bug_?

Bug report

#### What's the current behavior?

Japanese input seems to overlap in this example (https://www.slatejs.org/#/markdown-preview). Please see following gif. I guess this behavior is occurred by decorator.

![untitled](https://user-images.githubusercontent.com/10220449/52682096-95ade900-2f81-11e9-9170-133317b1cab3.gif)

`日本語` is duplicated.

### My env

Google chrome  71.0.3578.98
Google 日本語入力 2.24.3250.1

#### What's the expected behavior?

Japanese input does not overlap with decorator.

**Comment by wuxiandiejia** [comment] 2019-02-13 10:01
You can add `onCompositionStart` and `onCompositionEnd` props on the `Editor` component.

**Comment by bokuweb** [comment] 2019-02-13 12:29
@wuxiandiejia Thanks :) I'll try it !!

**Comment by bokuweb** [comment] 2019-02-14 06:13
Hmm, I tried above workaround, but unfortunately it does not solve my problem... Do you have any idea??

**Comment by wuxiandiejia** [comment] 2019-02-14 06:31
Maybe you can get help on the slate's [slack](https://slate-slack.herokuapp.com/) channel.

**Comment by wuxiandiejia** [comment] 2019-02-16 00:48
I found a solution.
When you are composing  give the mark a new `key` to enforce the mark to re-render.
```javascript
    // in decorateNode mehod
      if (typeof token != 'string') {
        const dec = {
          anchor: {
            key: startText.key,
            offset: startOffset,
          },
          focus: {
            key: endText.key,
            offset: endOffset,
          },
          mark: {
            type: token.type,
          },
        }
        if (this.state.isComposing) {
          const nodeKey = token.type + Date.now()
          dec.mark.data = {
            key: nodeKey
          }
        }
        decorations.push(dec)
      }
```

```javascript
// set key prop in renderMark method
case 'bold':
        return <strong {...attributes} key={mark.data.get('key')}>{children}</strong>
// other mark also can set key
```

**Comment by bokuweb** [comment] 2019-02-16 05:01
@wuxiandiejia Thanks :) I'll try it 👍

**Comment by ianstormtaylor** [comment] 2019-05-09 02:15
Hey, thanks for reporting this. I think this is actually a duplicate of https://github.com/ianstormtaylor/slate/issues/2368, so I'm going to close this in favor of that one. Feel free to comment over there with any other info!

**Closed by ianstormtaylor** 2019-05-09 02:15 UTC
