### ISSUE TITLE
When hitting backspace, all remaining nodes are removed

### ISSUE THREAD

**Issue by pavlyna** [ianstormtaylor/slate#3521] opened 2020-02-27 15:16 UTC
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?

See https://codesandbox.io/s/clever-tu-3cmy4

Step to reproduce
1. Having json like in the example provided above 
2. Put the cursor at the beginning of the first element
3. Hit backspace

Selected node is merged with the previous line, the rest of the nodes after the selected node are removed

Slate: 0.57.1
Browser: Chrome
OS: Mac / Windows / Linux

![ezgif com-crop (1)](https://user-images.githubusercontent.com/7562331/75457680-6e0ba200-5985-11ea-853b-27c58570144e.gif)

#### What's the expected behavior?
Selected node is merged with the previous line, the rest of the nodes after the selected node remain.

This happens in `mergeNodes` when determining `emptyAncestor`

**Comment by pavlyna** [comment] 2020-03-11 19:10
just in case, PR #3547

**Comment by juliankrispel** [comment] 2021-04-23 07:02
Managed to reproduce this issue with the original codesandbox example, upgraded it and cannot reproduce it anymore, seems to now work as it should, here's a sandbox with an upgraded version of slate for reference https://codesandbox.io/s/zealous-golick-gs9vg

Hence closing this issue

**Closed by juliankrispel** 2021-04-23 07:02 UTC
Labels: bug
