### ISSUE TITLE
Chinese input breaks when using marks

### ISSUE THREAD

**Issue by giddens9527** [ianstormtaylor/slate#2467] opened 2018-12-03 07:31 UTC
#### Do you want to request a _feature_ or report a _bug_?

Bug 
#### What's the current behavior?

Input some characters with Chinese IME and then hit "cmd + i" without selecting anything. Input Chinese again and there will be both English and Chinese characters displayed. 
The deletion behavior is not as expected either.
on Mojave + Chrome with sougou input method
[GIF here](http://g.recordit.co/dwANBt5g7i.gif)

#### What's the expected behavior?

should only display Chinese.

**Comment by jimshute** [comment] 2019-01-11 02:12
貌似这是一个普遍的用IME在block尾部编辑会出现的问题，在block中间位置编辑则正常。主要出现在chrome。可以参考一下https://github.com/ianstormtaylor/slate/issues/2062 这个issue。

**Comment by changlin-cn** [comment] 2019-03-15 02:15
`editor.toggleMark(type);
      if (editor.value.selection.isCollapsed) {
        editor.insertText('\u200B');
      }`

**Comment by giddens9527** [comment] 2019-03-20 06:00
> `editor.toggleMark(type); if (editor.value.selection.isCollapsed) { editor.insertText('\u200B'); }`
> @giddens9527

Worked like a charm! Thanks! Mind explaining why it works?

**Comment by Jiang-Rain** [comment] 2019-03-28 09:11
请问这个问题解决了吗？

**Comment by Jiang-Rain** [comment] 2019-03-28 09:12
请问这个问题解决了吗？editor.toggleMark（type）; if（editor.value.selection.isCollapsed）{editor.insertText（'\ u200B'）; }
要放在哪里？ @giddens9527 @changlin-cn

**Comment by giddens9527** [comment] 2019-03-28 13:23
@Jiang-Rain 我这边就是按toggleMark后面加editor.insertText('\u200B'); 解决的，治标不治本吧。暂时没发现带来其他问题。

**Comment by ianstormtaylor** [comment] 2019-05-09 02:22
Hey, thanks for reporting this. I think this is actually a duplicate of https://github.com/ianstormtaylor/slate/issues/2368, so I'm going to close this in favor of that one. Feel free to comment over there with any other info!

**Closed by ianstormtaylor** 2019-05-09 02:22 UTC
