### ISSUE TITLE
slate tries to get deleted node in `with-schema.js`

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#1537] opened 2018-01-16 16:06 UTC
#### Do you want to request a *feature* or report a *bug*?

Perhaps a bug:

#### What's the current behavior?

https://jsfiddle.net/JinxuanZhu/711y5rLe/
The link trys:
1. if a child of `bad-table` is not `bad-row`; unwrap the child; by the default logic of `unwrapNodeByKey`, if `bad-table.nodes.size === 1`, bad-table is deleted
2.  if a child of `bad-row` is not `bad-cell`; unwrap the child; by the default logic of `unwrapNodeByKey`, if `bad-row.nodes.size === 1`, bad-row is deleted

However, it is conflicting with the `with-schema.js` in this part, where `node=refindNode` is undefined

```
    if (change.operations.size > size) {
      node = refindNode(change, node);

      // Add any new children back onto the stack.
      node.nodes.forEach(function (n) {
        if (set.has(n.key)) return;
        keys.unshift(n.key);
      });
    }
```
It seems that the problem is caused by visiting the bad-row after the bad-table normalized...

**Comment by CameronAckermanSEL** [comment] 2018-01-16 16:27
Strong probability of being a duplicate of https://github.com/ianstormtaylor/slate/issues/1528

**Closed** 2018-02-06 18:53 UTC
Labels: bug
