### ISSUE TITLE
error in the 'code-highlighting'  by type key words at last lines.

### ISSUE THREAD

**Issue by solsos** [ianstormtaylor/slate#2232] opened 2018-10-05 21:02 UTC
![image](https://user-images.githubusercontent.com/17923026/46559979-0fd9ad00-c8c0-11e8-94ff-a6c1dda335eb.png)

at the last line. `enter` twice and type `for`. 

When you finished the for, there is an error. 

![image](https://user-images.githubusercontent.com/17923026/46560040-457e9600-c8c0-11e8-8fa4-4d5b33b9cc76.png)

**Comment by SmilinBrian** [comment] 2018-10-05 22:45
Duplicate of #2154 

Can be fixed by applying the Pull: https://github.com/ianstormtaylor/slate/pull/2157

**Comment by solsos** [comment] 2018-10-09 14:14
Yes, I used the latest version of the `slate-react: "^0.18.10"` but the error still there in my project.

**Comment by solsos** [comment] 2018-10-09 14:19
And, to clarify, my ticket is different from the previous one. You need to type the `keywords` to reproduce this error. Such as `for`.

**Comment by SmilinBrian** [comment] 2018-10-10 00:19
To clarify, that Pull shows "Closed" because the author decided the "real fix" should be more pervasive. No real fix has yet been made as far as I know.

It **is** a duplicate of #2154 -- error when no path is supplied when a new syntax highlight Decoration is added.

#2154 just uses "1" because it also triggers syntax highlight. The problem does not occur when the initial value is first rendered, only when new Decorations are added.

**Comment by SmilinBrian** [comment] 2018-11-21 00:16
#2319 is a better fix. Should close this in favor of that one.

**Comment by brendancarney** [comment] 2019-03-02 19:09
Closing in favor of #2319

**Closed by brendancarney** 2019-03-02 19:09 UTC
