### ISSUE TITLE
Cannot resolve a DOM point from Slate point

### ISSUE THREAD

**Issue by joesonw** [ianstormtaylor/slate#3239] opened 2019-12-05 02:33 UTC
#### Do you want to request a _feature_ or report a _bug_?

bug
#### What's the current behavior?

steps:
1. goto https://www.slatejs.org/examples/images
2. drop a image from computer to the editor
3. click empty area in editor

`Cannot resolve a DOM point from Slate point: {"path":[1,0],"offset":1}`

Slate: 0.50.X (official example)
Browser: Chrome
OS: Mac

#### What's the expected behavior?
Normal

**Comment by dmarkow** [comment] 2019-12-05 14:26
You don't even need to add another image. Just left click once on the existing image to highlight, then right click on it. Same error.

**Comment by dmarkow** [comment] 2019-12-05 14:37
Same issue with https://www.slatejs.org/examples/embeds -- try selecting some text above and continuing the selection into the embed.

![ScreenFlow](https://user-images.githubusercontent.com/8009/70244583-4ae0a600-173a-11ea-8eb7-20cc46693478.gif)

**Comment by focux** [comment] 2019-12-05 18:05
Duplicate of #3145

**Closed** 2019-12-06 16:13 UTC
Labels: bug, ♥ help
