### ISSUE TITLE
Selecting all and pressing any key fails and causes an exception

### ISSUE THREAD

**Issue by steobrien** [ianstormtaylor/slate#2323] opened 2018-10-25 17:43 UTC
#### Do you want to request a _feature_ or report a _bug_?

Bug.

#### What's the current behavior?

1. Select all
2. Press a key (e.g. to replace selection with a character, or backspace to remove selection)
3. Selection is maintained and an exception fires

#### What's the expected behavior?

After pressing a key, there is no exception, and the selection is replaced or removed.

<p>
<details><summary><b>Example exception</b></summary>
<pre><code>

element.js:1774 Uncaught Error: `Node.assertNode` could not find node with path or key: List [ 1 ]
    at a.Xa.(/anonymous function) [as assertNode] (https://www.slatejs.org/main-73ddf306323965c29187.js:1:136769)
    at a.value (change.js:198)
    at a.value (change.js:182)
    at a.value (change.js:265)
    at a.value (change.js:245)
    at a.value (change.js:182)
    at a.value (change.js:265)
    at a.value (change.js:245)
    at a.value (change.js:182)
    at a.value (change.js:265)
</code></pre>
</details>
</p>

#### Example gif
This affects the [rich text demo](https://www.slatejs.org/#/rich-text), and may be an issue with it specifically:
![gifable-0f8bc176-7567-40d6-bf13-3e8ce9d8450d](https://user-images.githubusercontent.com/1694410/47519163-e70f5c80-d85a-11e8-974f-c92336daea0b.gif)

**Comment by ericedem** [comment] 2018-10-25 17:49
Thanks! Looks like a duplicate of: https://github.com/ianstormtaylor/slate/issues/2291

**Comment by ianstormtaylor** [comment] 2018-10-25 17:51
Closing in favor of that one.

**Closed by ianstormtaylor** 2018-10-25 17:51 UTC

**Comment by steobrien** [comment] 2018-10-25 17:52
Ah! Thank you.
