### ISSUE TITLE
AutoReplace  is not supported Chinese?

### ISSUE THREAD

**Issue by KingJeason** [ianstormtaylor/slate#2494] opened 2018-12-11 13:28 UTC
http://g.recordit.co/XYkZQ7CfFX.gif
```
AutoReplace({
        trigger: 'space',
        before: /(\*\*)(.+)(\*\*)/,

        change: (edite, e, matches) => {
            console.log(edite, e, matches.before)
            return edite
                .addMark({
                    type: 'bold'
                })
                .insertText(matches.before[2])
                .toggleMark('bold')
                .splitInline()
        }
    })
```
When it gets bold, typing Chinese will have a strange effect

**Comment by zhujinxuan** [comment] 2018-12-11 15:47
I think the onKeyDown captures the input method composition end.

Perhaps we need to block onKeyDown during composition.

**Comment by ianstormtaylor** [comment] 2019-05-09 02:42
Hey, thanks for reporting this. I think this is actually a duplicate of https://github.com/ianstormtaylor/slate/issues/2368, so I'm going to close this in favor of that one. Feel free to comment over there with any other info!

**Closed by ianstormtaylor** 2019-05-09 02:42 UTC
