### ISSUE TITLE
Focus by click not working on Linux's Firefox, Chromium

### ISSUE THREAD

**Issue by doums** [ianstormtaylor/slate#2630] opened 2019-03-04 23:14 UTC
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
Linux desktop
Mozilla Firefox 65.0.2
Chromium Version 72.0.3626.121 (official build) Arch Linux (64 bits)
OS 4.20.13-arch1-1-ARCH x86_64 GNU/Linux
slate: ^0.44.10
slate-react: ^0.21.16
react: ^16.8.3
react-dom: ^16.8.3
immutable: ^4.0.0-rc.12

EDIT: with Tab the focus works, but not with mouse click

When the editor loses focus (by pressing escape or removing all the text for example) it's impossible to get it back! So it's currently impossible to use the Slate's editor (at least on my machine).
For example with the following simple code, it is just impossible to interact with the editor at all. Even if I try to left/right click with mouse, ~pressing Tab~ etc...
I tested both on Chromium and Firefox.

```
import React, { useState } from 'react'
import { Editor } from 'slate-react'
import { Value } from 'slate'

const initialValue = Value.fromJSON({
  document: {
    nodes: [
      {
        object: 'block',
        type: 'paragraph',
        nodes: [
          {
            object: 'text',
            leaves: [
              {
                text: ''
              }
            ]
          }
        ]
      }
    ]
  }
})

export default function PMEditor () {
  const [ value, setValue ] = useState(initialValue)

  const onChange = ({ value }) => {
    setValue(value)
  }

  return <Editor
    value={value}
    onChange={onChange}
    placeholder='your words...'
  />
}
```

#### What's the expected behavior?
focus works

**Comment by adjourn** [comment] 2019-03-11 11:59
Could you reproduce this behaviour in [Codesandbox](https://codesandbox.io/s/new)? Im not able to reproduce it on Ubuntu.

**Comment by robinschuster** [comment] 2019-04-10 09:52
I also have this issue.

I am using the `focus` state to enable certain buttons of the editor, rendering them useless when used with firefox on linux.

**Comment by adjourn** [comment] 2019-04-10 13:16
Can you reproduce this in fiddle? Tried both Chromium and Firefox, not getting this problem. (Linux)

**Comment by ianstormtaylor** [comment] 2019-11-28 03:09
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Closed by ianstormtaylor** 2019-11-28 03:09 UTC
Labels: ⚑ needs info, ⚑ needs sandbox
