### ISSUE TITLE
Safari does not Undo added marks/inlines

### ISSUE THREAD

**Issue by jas7457** [ianstormtaylor/slate#3021] opened 2019-09-16 12:55 UTC
#### Do you want to request a _feature_ or report a _bug_?
Report a bug

#### What's the current behavior?
In Safari, a user cannot undo an added mark (Bold, Italic, Underline, etc). What's more interesting is that if the user adds multiple marks, they can undo all but the first one that was added.

Tested on Mac Mojave, Safari 12.1, with the newest Slate (0.47.8)
Occurs on https://www.slatejs.org/#/rich-text
Gif of issue: http://g.recordit.co/RemTiU5Itd.gif

#### Steps to reproduce:
1. Add a mark (bold)
2. Try to undo it, realize you can't
3. Add several marks (bold, italic, underline)
4. Try to undo all of them, and all but the first added can be undone, but not the first added.

#### What's the expected behavior?
You should be able to undo these marks in Safari, just like in other browsers.

**Comment by justinweiss** [comment] 2019-09-17 22:02
I ran into this before, and I think it's caused by a difference in how Safari positions the cursor when it's in between two nodes. It should be fixed whenever either #2746 or #2973 make it in.

**Comment by ianstormtaylor** [comment] 2019-11-28 03:12
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Closed by ianstormtaylor** 2019-11-28 03:12 UTC
