### ISSUE TITLE
no easy way to add normal text after a link

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#349] opened 2016-09-22 22:36 UTC
From #317:

> Adding text immediately after the link styles the text as part of the link. In other words it doesn't seem easy to add normal text after the link.

**Comment by arekkas** [comment] 2016-11-17 21:04
This is still an issue in 0.15

**Comment by ianstormtaylor** [comment] 2016-11-23 16:41
This is slightly tricky form a UX perspective, since there's no easy way to guess what the user's intention is for whether their cursor is on either side of the inline node boundary.

That said, I think the way I'd like to solve this is similar to Google Docs, where if your cursor is at the edge of an inline node, and you try to insert text, it will actually insert it on either side of the node. To insert more text into an inline node, you need to not be on one of it's edges:

![](http://g.recordit.co/Tntp2Aamta.gif)

**Comment by arekkas** [comment] 2016-11-29 09:45
yeah, that makes sense!

**Comment by SamyPesse** [comment] 2016-12-01 18:39
@ianstormtaylor This is a very good idea 👍 Any idea how to implement this with Slate ?

I'll probably try writing a small plugin for this, I guess something can be done in `onKeydown` by testing the position of the cursor in the parent inline.

**Comment by ianstormtaylor** [comment] 2016-12-01 19:53
@SamyPesse awesome! Yup, I think the most "correct" way would probably be for additional logic in the core plugin's `onBeforeInput` that changes where the text is inserted if at the edge of an inline node. Let me know if you run into any issues!

**Comment by alexeygolev** [comment] 2017-04-27 21:57
'Adding text immediately after the link styles the text as part of the link' is still there. Text added before the link is styled correctly (as normal text) but anything typed after the link is still a link.

**Comment by alexeygolev** [comment] 2017-05-02 10:47
@Soreine One thing I'm not sure — should it even be in the core? It seems like other "inline" like italic and bold don't need this.

**Comment by alexeygolev** [comment] 2017-05-08 13:07
@ianstormtaylor @Soreine Did some tests — it's a browser specific bug. In fact as of chrome 58.0.3029.96 it became a browser version specific bug as it started working in chrome. Still doesn't work in Safari 10.1 (11603.1.30.0.34). Going to check what is this all about

**Comment by andrewgleave** [comment] 2017-07-25 14:17
It seems hit-and-miss for me in Chromium 59.0.3071.0.

With an empty editor, the first link which is added is Ok – I press space and I'm outside of the inline node. After adding any subsequent link I am still inside the node.

In Chrome/Chromium I can press the right arrow key and escape the node (which you can see in the last couple of frames of this gif), but in Safari I cannot.

![links](https://user-images.githubusercontent.com/100615/28576662-5bd9fa4c-714c-11e7-8bd3-afcc6e5a755a.gif)

**Comment by YurkaninRyan** [comment] 2017-08-19 16:13
If anyone comes across this and is looking for this kind of inline functionality, i've created the plugin `slate-sticky-inlines` just for that purpose

**Comment by schneidmaster** [comment] 2018-02-23 01:06
Looks like this is solved now (at least as of 0.33.0, may have actually been fixed in some previous version).

![Gif](https://user-images.githubusercontent.com/1896112/36572832-dce996f4-180b-11e8-9563-4723ba2493d1.gif)

**Closed by schneidmaster** 2018-02-23 01:06 UTC
Labels: improvement, ♥ help please

**Comment by BrechtVds** [comment] 2019-03-13 16:34
I still seem to be experiencing this problem when using Safari and testing the [link example](https://www.slatejs.org/#/links).

To reproduce just add a link at the very end of content and you won't be able to add normal text after it. Doesn't seem to be an issue in Chrome.
