### ISSUE TITLE
Examples/code-highlighting error

### ISSUE THREAD

**Issue by An0nymous0** [ianstormtaylor/slate#2154] opened 2018-09-05 08:36 UTC
#### Do you want to request a _feature_ or report a _bug_?
examples bug

https://github.com/ianstormtaylor/slate/tree/master/examples/code-highlighting

#### What's the current behavior?
Enter 1 and press Enter to repeat this fast
![image](https://user-images.githubusercontent.com/6836030/45081344-9700fd00-b129-11e8-9309-13ea37e843d3.png)
![image](https://user-images.githubusercontent.com/6836030/45081384-abdd9080-b129-11e8-99f6-44cc757b10c5.png)

#### What's the expected behavior?
No error

**Comment by ericedem** [comment] 2018-09-05 15:33
@An0nymous0 Can you please add browser info and more detailed steps? I'm having trouble reproducing this issue.

**Comment by uipoptart** [comment] 2018-09-06 20:39
Looks like there is an issue with the way the decoration is made on line 228-236. The anchor and focus values aren't getting their paths assigned. So, when the paths are compared later down the line the value is null. I'll try to put together a pull request later this afternoon.

**Comment by SmilinBrian** [comment] 2018-11-21 00:16
#2319 has a more definitive fix.

**Comment by brendancarney** [comment] 2019-03-02 19:06
Closing in favor of #2319.

**Closed** 2019-03-02 19:21 UTC
