### ISSUE TITLE
Update HTML Example in Docs

### ISSUE THREAD

**Issue by YurkaninRyan** [ianstormtaylor/slate#976] opened 2017-08-09 16:38 UTC
Currently, the tutorial makes assumptions that are no longer true.  (You don't get an object anymore for example, you can get an array or a raw dom node while deserializing.)

We should update it to match the switch.

**Comment by towfiqi** [comment] 2017-08-11 13:45
Just followed the guide and implemented it in my project. But the issue is, the editor doesnt render the `<p>` tags. It saves it correctly with html. But when rendering inside the editor, it strips all the html and shows it inside in a span. like this:

`<div data-key="12" style="position: relative;"><span data-key="10"><span data-offset-key="10-0">Firebase queries allow you to order your data by any child key on the fly. However, if you know in advance what your indexes will be, you can define them via the .indexOn rule in your Security Rules for better performance. </span></span></div>`

Instead of:

`<div data-key="12" style="position: relative;"><span data-key="10"><span data-offset-key="10-0"><p>Firebase queries allow you to order your data by any child key on the fly.</p><p> However, if you know in advance what your indexes will be, you can define them via the .indexOn rule in your Security Rules for better performance.</p></span></span></div>`

The schema, marks, rules are exactly as in the documentation:
https://docs.slatejs.org/walkthroughs/saving-and-loading-html-content.html

**Comment by YurkaninRyan** [comment] 2017-08-11 13:58
@towfiqi el.tagName on a native dom element isn't going to be "p" anymore instead it will be "P", that's why it isn't rendering a paragraph.

**Comment by towfiqi** [comment] 2017-08-11 14:45
Worked! Thanks. Looks like the documentation needs updating.

**Comment by schneidmaster** [comment] 2017-08-17 17:34
@YurkaninRyan I think this is fixed via your #985 and my #1001 -- are there any other HTML documentation issues you're aware of?

**Comment by YurkaninRyan** [comment] 2017-08-17 17:55
This looks good to me!

**Closed** 2017-08-17 18:39 UTC
Labels: docs, ⭐  help-please
