### ISSUE TITLE
removeMark behavior changed slightly since 0.45.x - By design, or accident?

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#2880] opened 2019-06-13 00:12 UTC
#### Do you want to request a _feature_ or report a _bug_?

Bug(?)

#### What's the current behavior?

`removeMark` no longer removes marks from a collapsed selection.

#### What's the expected behavior?

Previously calling `removeMark` would remove marks from a collapsed selection.

**Comment by isubasti** [comment] 2019-06-14 00:51
duplicate of https://github.com/ianstormtaylor/slate/issues/2848, https://github.com/ianstormtaylor/slate/issues/2830, https://github.com/ianstormtaylor/slate/issues/2736, maybe https://github.com/ianstormtaylor/slate/issues/2736. fixes PR seems to be on the way https://github.com/ianstormtaylor/slate/pull/2818

**Closed** 2019-06-14 03:54 UTC
Labels: bug, ♥ help please, ⚑ needs info

**Comment by Slapbox** [comment] 2019-06-14 03:56
Nice work @isubasti, it's indeed a duplicate of #2848
