### ISSUE TITLE
JSON cannot be mutated

### ISSUE THREAD

**Issue by irmerk** [ianstormtaylor/slate#3577] opened 2020-04-02 16:58 UTC
#### Do you want to request a _feature_ or report a _bug_?
*Bug*

#### What's the current behavior?

When mutating the `JSON`, there is a type error because Slate does not seem to be `JSON` based:

```js
  const onCopy = (event) => {
    const SLATE_SELECTION = Node.fragment(editor, editor.selection);
    SLATE_SELECTION[0].children = []; // ERROR HERE
    console.log('SLATE_SELECTION ', SLATE_SELECTION);
  };
```
```sh
Uncaught TypeError: Cannot assign to read only property 'children' of object '#<Object>'
``` 

- [GIF of issue in action](http://www.giphy.com/gifs/hvk9QvzUDgmSWpQyRM)
- [Sandbox of issue reproduction](https://codesandbox.io/s/slate-reproductions-9rbph)
- Info:
  - Slate: `0.57.1` (`0.50.0` in the Sandbox)
  - OS: macOS Catalina version `10.15.3`
  - Browser: Chrome Version `80.0.3987.149` (Official Build) (64-bit)

My current workaround is:
```js
const SLATE_SELECTION = JSON.parse(JSON.stringify(Node.fragment(editor, editor.selection));
```

#### What's the expected behavior?

Reading about [`JSON` in the Migration guide](https://docs.slatejs.org/concepts/xx-migrating#json) as well as [in the Interfaces concept](https://docs.slatejs.org/concepts/01-interfaces), I understand that Slate is now based on `JSON`. I should therefore be able to mutate the data.

**Comment by irmerk** [comment] 2020-04-02 16:59
Is this expected/intended behavior?

**Comment by irmerk** [comment] 2020-04-02 17:07
From @CameronAckermanSEL: The value or `Node.fragment` is immutable via [`immer`](https://github.com/immerjs/immer). Not intended for users to mutate it directly, instead should use `Transformations`

**Comment by CameronAckermanSEL** [comment] 2020-04-02 18:13
Hey! Thanks for the issue. As I said in slack it's unintended for you to mutate the JSON directly, and instead you can use the Transforms library, or you can use immer to mutate the JSON (but this will likely not get picked up by the editor state and is probably not a great idea).

Closing for now as this is intended behavior

**Closed by CameronAckermanSEL** 2020-04-02 18:13 UTC
