### ISSUE TITLE
TypeError: Cannot read property 'size' of null

### ISSUE THREAD

**Issue by tolmasky** [ianstormtaylor/slate#2428] opened 2018-11-15 18:06 UTC
Was using the Code Highlighting example in the docs, and it threw this: 

<details>
<summary>TypeError: Cannot read property 'size' of null</summary>

```javascript
TypeError: Cannot read property 'size' of null
    at Ge (https://www.slatejs.org/main-9a612105532ed99867a4.js:1:24847)
    at Object.Pe [as compare] (https://www.slatejs.org/main-9a612105532ed99867a4.js:1:23815)
    at https://www.slatejs.org/main-9a612105532ed99867a4.js:1:172062
    at https://www.slatejs.org/main-9a612105532ed99867a4.js:1:226467
    at pa.__iterate (https://www.slatejs.org/main-9a612105532ed99867a4.js:1:219866)
    at r.Ga.r.__iterateUncached (https://www.slatejs.org/main-9a612105532ed99867a4.js:1:226436)
    at ue (https://www.slatejs.org/main-9a612105532ed99867a4.js:1:199933)
    at r.U.__iterate (https://www.slatejs.org/main-9a612105532ed99867a4.js:1:198764)
    at r.forEach (https://www.slatejs.org/main-9a612105532ed99867a4.js:1:243809)
    at https://www.slatejs.org/main-9a612105532ed99867a4.js:1:217624

    in a
    in div
    in B
    in a
    in code
    in pre
    in div
    in M
    in a
    in div
    in a
    in a
    in a
    in a
    in a
    in div
    in Styled(div)
    in div
    in a
    in a
    in a
    in a
```
</details>

## Steps to reproduce:

1. Place cursor at the end of line 6:
<img width="689" alt="screen shot 2018-11-15 at 10 08 25 am" src="https://user-images.githubusercontent.com/23753/48572507-72aa6500-e8be-11e8-994b-25f2a30e17ed.png">

2. Type "\nfor(i=0;i<10;++i)\n{\n}":

<img width="682" alt="screen shot 2018-11-15 at 10 09 39 am" src="https://user-images.githubusercontent.com/23753/48572550-98376e80-e8be-11e8-9f7e-b78a7dc0b89f.png">

3. Move cursor up one line using the up arrow:

<img width="683" alt="screen shot 2018-11-15 at 10 10 36 am" src="https://user-images.githubusercontent.com/23753/48572611-bef5a500-e8be-11e8-8864-a8d312d5adb3.png">

4. Hit return:

<img width="704" alt="screen shot 2018-11-15 at 10 10 46 am" src="https://user-images.githubusercontent.com/23753/48572617-c321c280-e8be-11e8-8805-e20d87c998e3.png">

**Comment by SmilinBrian** [comment] 2018-11-21 00:10
Duplicate of #2319

**Comment by brendancarney** [comment] 2019-03-02 19:03
Closing due to the duplicate mentioned above.

**Closed by brendancarney** 2019-03-02 19:03 UTC
