### ISSUE TITLE
'type' does not exist in type 'Descendant'

### ISSUE THREAD

**Issue by ayepRahman** [ianstormtaylor/slate#4415] opened 2021-08-06 03:48 UTC
**Description**
Iam using typescript for react project, iam having issue initial setting basic setup with inital values saying 'type' does not exist in the type "Descendant'

<img width="360" alt="Screenshot 2021-08-06 at 11 46 52 AM" src="https://user-images.githubusercontent.com/26382836/128453161-3671bd92-e386-42ac-9090-f4fbd877f997.png">
<img width="936" alt="Screenshot 2021-08-06 at 11 46 23 AM" src="https://user-images.githubusercontent.com/26382836/128453164-3bb90660-c7cc-4b12-acfc-9dd137c3285a.png">
<img width="749" alt="Screenshot 2021-08-06 at 11 45 38 AM" src="https://user-images.githubusercontent.com/26382836/128453172-d23610e7-b14c-4bea-a21c-17ceafe544fa.png">

**Comment by imdbsd** [comment] 2021-08-09 12:45
there is a guide about it here https://docs.slatejs.org/concepts/12-typescript

**Comment by BrentFarese** [comment] 2021-08-09 14:59
This comment seems like it belongs in Slack and is not a bug?  Have you tried using this guide to define your custom types?  https://docs.slatejs.org/concepts/12-typescript#defining-editor-element-and-text-types.

I'll close this shortly if it's not a bug as the discussion can be moved to Slack.  Thanks!

**Closed** 2021-08-21 15:18 UTC
Labels: bug

**Comment by dxinteractive** [comment] 2021-11-29 05:00
Hi, I'm also encountering this. I'm not using custom types, all I've done is copy this example verbatim into an existing typescript / react project (https://github.com/ianstormtaylor/slate/blob/main/site/examples/plaintext.tsx). Did the Slack discussion take place and was there any outcome there?

Minimal reproduction for me:

```
import type {Descendant} from 'slate';
const initialValue: Descendant[] = [
    {
        type: 'paragraph',
        children: [
            {
                text: 'This is editable plain text, just like a <textarea>!'
            }
        ]
    }
];
```

TS throws error:

```
TS2322: Type '{ type: string; children: { text: string; }[]; }' is not assignable to type 'Descendant'.
Object literal may only specify known properties, and 'type' does not exist in type 'Descendant'.
```

Versions:

```
"slate": "0.71.0",
"slate-react": "0.71.0",
"typescript": "^4.0.2"
```
