### ISSUE TITLE
Right click paste doesn't paste on empty line

### ISSUE THREAD

**Issue by adrianclay** [ianstormtaylor/slate#1680] opened 2018-02-27 16:11 UTC
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?

When copy and pasting, you are only able to paste to a new/empty line using the keyboard shortcut and not the right click paste. This is reproducible on the [demo site](http://slatejs.org/#/rich-text) on Chrome Stable 64

![feb-27-2018 16-06-52](https://user-images.githubusercontent.com/976274/36739786-b5dc8fc8-1bd8-11e8-928a-5de0337bcf5f.gif)

#### What's the expected behavior?

Able to paste using right click.

**Comment by zhujinxuan** [comment] 2018-02-27 19:20
I think the problem is that the right-click menu pop-up lose the selection.

**Comment by benjycui** [comment] 2018-03-28 02:05
It works fine on Mac@10.13.3 & Chrome@65.0.3325.181

<img src="http://g.recordit.co/iVcOiuUlcD.gif" />

**Comment by brendancarney** [comment] 2019-03-02 19:49
I'm unable to reproduce this, testing with OSX and Windows in multiple browsers. I'll close this issue, but if you provide more info on how to reproduce, we're happy to reopen it.

**Closed by brendancarney** 2019-03-02 19:49 UTC
Labels: ⚑ needs info
