### ISSUE TITLE
Error accessing editor state via React DevTools

### ISSUE THREAD

**Issue by oyeanuj** [ianstormtaylor/slate#590] opened 2017-02-09 03:28 UTC
Hey @ianstormtaylor! While accessing the `state` of the editor in the React DevTools, I get the following error in the console.

I am on Chrome, and have the Immutable.js Object Formatter extension enabled as well.

```
warn.js:32 Warning: An object was passed to a Node method instead of a `key` string. This was previously supported, but is being deprecated because it can have a negative impact on performance. The object in question was: null
warn	@	warn.js:32
key	@	normalize.js:95
getClosest	@	node.js:389
object.(anonymous function)	@	memoize.js:109
(anonymous)	@	backend.js:7345
_inspectResponse	@	backend.js:7341
_handleMessage	@	backend.js:7260
listener	@	backend.js:91
postMessage (async)		
handleMessageFromDevtools	@	contentScript.js:18
EventImpl.dispatch_	@	VM77180 extensions::event_bindings:372
dispatchOnMessage	@	VM77187 extensions::messaging:320

normalize.js:101 Uncaught Error: Invalid `key` argument! It must be either a block, an inline, a text, or a string. You passed: "null".
    at Object.key (webpack:///./~/slate/lib/utils/normalize.js?:101:9)
    at Document.getClosest (webpack:///./~/slate/lib/models/node.js?:389:31)
    at Document.object.(anonymous function) [as getClosestBlock] (webpack:///./~/slate/lib/utils/memoize.js?:109:30)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:7345:54
    at Array.forEach (native)
    at Bridge._inspectResponse (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:7341:54)
    at Bridge._handleMessage (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:7260:15)
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:91:10)
```

Thanks!

**Comment by ianstormtaylor** [comment] 2017-02-23 23:08
I think this is a duplicate of https://github.com/ianstormtaylor/slate/issues/545

**Closed by ianstormtaylor** 2017-02-23 23:08 UTC
