### ISSUE TITLE
Accentuated characters with ^ are broken on Safari

### ISSUE THREAD

**Issue by renchap** [ianstormtaylor/slate#1319] opened 2017-10-28 08:53 UTC
With Safari 11.0:

![2017-10-28 10_45_24](https://user-images.githubusercontent.com/42070/32132921-5344d6f6-bbcd-11e7-80e9-f2f3c9763631.gif)

On a french keyboard, the character is obtained by pressing the `^` key followed by the `a` key. The error occurs when `space` is pressed after entering the `â`.

Console errors:

```
[Error] TypeError: undefined is not an object (evaluating 'g.text')
	db (build.prod.js:4703:3297)
	processEventQueue (build.prod.js:4704:21470)
	handleTopLevel (build.prod.js:4704:23947)
	xb (build.prod.js:4703:4428)
	batchedUpdates (build.prod.js:4704:4634)
	batchedUpdates (build.prod.js:4704:19685)
	dispatchEvent (build.prod.js:4704:20551)
	dispatchEvent
```

```
[Error] TypeError: undefined is not an object (evaluating 'this.getDescendant(n).characters.get(e.startOffset-1).marks')
	value — build.prod.js:5039:11122
	(anonymous function) — build.prod.js:5073:716
	value — build.prod.js:5039:10248
	(anonymous function) — build.prod.js:5073:716
	hasMark — build.prod.js:841:1828
	renderMarkButton — build.prod.js:841:3601
	renderToolbar — build.prod.js:841:3132
	value — build.prod.js:841:5351
	u — build.prod.js:4703:19032
	o — build.prod.js:4704:817
	u — build.prod.js:4704:1327
	c — build.prod.js:4704:1795
	batchedUpdates — build.prod.js:4704:4657
	batchedUpdates — build.prod.js:4704:19685
	dispatchEvent — build.prod.js:4704:20551
	dispatchEvent
	s (build.prod.js:4704:3114)
	c (build.prod.js:4704:1883)
	batchedUpdates (build.prod.js:4704:4657)
	batchedUpdates (build.prod.js:4704:19685)
	dispatchEvent (build.prod.js:4704:20551)
	dispatchEvent
```

This might be related to the Safari IME issues, but I am not sure the `â` characters are using IME.

**Comment by doodlewind** [comment] 2017-10-28 14:50
Seems that this can be solved with #1316 

![french-good](https://user-images.githubusercontent.com/7312949/32135458-3a615702-bbc5-11e7-9697-a80d3acbaa63.gif)

**Comment by renchap** [comment] 2017-10-29 17:58
It was not breaking after hitting `a`, but when hitting `space` after `^` and `a`.
Now with the latest Slate version it still fails, but with another error:

```
Error: Unable to find a DOM node for "10". This is often because of forgetting to add `props.attributes` to a custom component.
findDOMNode — build.prod.js:4927:151
findDOMPoint — build.prod.js:4930:149
findDOMRange — build.prod.js:4933:235
updateSelection — build.prod.js:4888:3429
componentDidUpdate — build.prod.js:4888:3039
commitLifeCycles — build.prod.js:4703:27728
n — build.prod.js:4703:31694
u — build.prod.js:4704:1358
c — build.prod.js:4704:1795
batchedUpdates — build.prod.js:4704:4657
batchedUpdates — build.prod.js:4704:19685
dispatchEvent — build.prod.js:4704:20551
dispatchEvent
```

**Comment by ianstormtaylor** [comment] 2017-10-29 21:25
@renchap good to know thanks. If you want this fixed, I'd recommend figuring out what's going wrong and submitting a PR like @doodlewind has been doing. Thanks!

**Comment by eliecerthoms** [comment] 2017-10-30 18:44
I've tried reproducing it with all the accented characters I know and the problem isn't showing, even after hitting space. Currently using the latest `0.30.2`, btw.

**Comment by ianstormtaylor** [comment] 2017-10-30 18:56
I think @renchap said this was now fixed in the Slate slack channel.

**Closed by ianstormtaylor** 2017-10-30 18:56 UTC
Labels: bug, ♥ help please
