### ISSUE TITLE
Upgrade examples to use the latest version of emotion

### ISSUE THREAD

**Issue by FrancisVila** [ianstormtaylor/slate#2584] opened 2019-02-05 09:14 UTC
1. After downloading the [mentions ](https://github.com/ianstormtaylor/slate/tree/master/examples/mentions) example, I get the following error message:
Error: The package "react-emotion" has been replaced by "@emotion/styled" in version 10. See https://emotion.sh/docs/migrating-to-emotion-10 for more information on migrating.
1. Suggestion: replace the use of such modules by traditional CSS files. This will be much simpler for people like me who come from html+javascript+css. And it works. No hassle.

- In the component: `import './MyComponent.css'`
- In MyComponent.css: just plain css

**Comment by adjourn** [comment] 2019-02-05 13:59
I disagree on CSS files, examples are small and having small styles next to components is easier to read.

But +1 for regular components and inline styles, `emotion` is unnecessary barrier or at least I found it a little bit confusing at first because I don't use it myself.

**Comment by FrancisVila** [comment] 2019-02-05 14:18
Thanks for your support, I'm preparing a pull request. 

I may be missing the whole point, but the concept of "CSS-in-JS" (the tagline of the emotion site) escapes me completely. I don't understand what problem they are attempting to solve. It seems to create problems and complexity where none existed, and demand new skills to replace old ones that have been around over 20 years.

**Comment by thesunny** [comment] 2019-02-05 21:46
I have to say, I learned about `emotion` from SlateJS and I think they are fantastic and am so glad I was introduced to it! I'm switching my large project over to it.

That said, I agree that they make understanding the examples harder and it may not be the best place to introduce a relatively new technology.

**Comment by FrancisVila** [comment] 2019-02-06 07:58
Hi @thesunny  ,
Do they do something more than just apply CSS styles? The advantage I see to separating CSS styles from JS code is that it means that styling the app is open to designers who don't want to meddle with the inner workings of the app. Even if the designer and the developer are the same person, that seems to be a healthy distinction.

**Comment by thesunny** [comment] 2019-02-06 19:08
@FrancisVila 

If you have designers that adjust the CSS, that's a good argument for using CSS although I'd recommend SASS if you aren't using it already. It allows for code reuse and is similar enough to CSS that designers can pick it up.

If you are the designer though, try using emotion and it's styled components (`styled`). It's hard to explain in one succinct statement but after trying it in some for-fun projects, I found that I had these feelings about my code (I'm now moving my big project to it and where I've migrated it so far, I like it better):

- More maintainable
- Cleaner
- Solid

These feelings are important and its hard to impart them with facts alone but I'll try. Individually, there are workarounds. Together, it brings more confidence in the code:

### Better Condition Styling

Conditional styling is handled in the styled component intuitively.

```jsx
return <MyFancyDiv active={active} />
```
instead of
```jsx
const className = classnames('MyFancyDiv', {
  "MyFancyDiv--active": active
}
return <div className={className} />
```

### Reduced className Management

- Not having to think of class names and then making sure they match on the CSS and in the JavaScript. No typos to worry about.
- Not worrying about global class name namespace collisions. Even with BEM, you have to be conscious about it. With styled components, you don't worry about classNames. The components are just regular variables.
- Not having to manage removal of class names. Let's say I don't need `MyFancyDiv--active` anymore? Okay, with CSS you have to make sure to remove in the JavaScript and the CSS. Oops, I forgot to remove the CSS because I was just playing with it and got a call in the middle. What are the chances that I'm going to get the --active version cleaned up now? With `styled` both get removed at the same time in the same place.
- In a perfect world, your CSS can be independent and should mostly be managed separately from the hierarchy of a DOM. Pragmatically, the hierarchy matters. It is easier to manage the CSS when it's there with the hierarchy.

It takes a bit to get used to it. There's some "How do I do this? Ugh! I could do this in a few seconds in CSS". It's just like with React when people were using jQuery and it was something like "How do I reposition this? Ugh! This would take a few seconds in jQuery". That said, the learning curve is much lighter than learning React.

**Comment by ianstormtaylor** [comment] 2019-02-06 19:39
Hey folks, this isn’t the place to have CSS-in-JS arguments. If anyone can help to upgrade emotion (or otherwise fix the error) that would be awesome! But we’re not going to switch technologies just to fix a warning like this.

**Comment by FrancisVila** [comment] 2019-02-07 07:41
@ianstormtaylor : well a bit more than a warning, it stops examples from working. This puts an extra hurdle to mastering and applying the technology. It's not very encouraging for people who have heard about the power of Slate but are wondering whether it's worth the effort of taming the beast. OTH the incredible support from the Slate Slack community (https://slate-js.slack.com) makes up for the technical hitches.

**Comment by ericedem** [comment] 2019-02-08 01:00
@FrancisVila Thanks for the bug report. I'm having trouble reproducing, locally, can you provide some more specific steps on how to reproduce? Thanks!

**Comment by Buzzology** [comment] 2019-02-08 01:05
> @FrancisVila Thanks for the bug report. I'm having trouble reproducing, locally, can you provide some more specific steps on how to reproduce? Thanks!

I'm not at home atm but hit the same issue just using create react app and following the RichText example. Note that it's not a build error, but crashes once you view the page.

**Comment by FrancisVila** [comment] 2019-02-08 08:50
@ericedem : was @Buzzology 's comment enough to reproduce ?
I think you get the same error across several of the examples in the project.
Also I can't get Slate examples in JSfiddle to work either: https://jsfiddle.net/pv95mqbo/

**Comment by ericedem** [comment] 2019-02-08 14:37
@FrancisVila In that fiddle I see a bunch of errors in the console that seem unrelated to this issue, like the react JS file getting a 404 on request. You might want to try using the base testing fiddle for slate: `https://jsfiddle.net/fj9dvhom/1/`. Is it possible that dependencies are missing when you guys are following the examples? It's possible that if you are copy pasting the example and installing `react-emotion` manually that there is a version mismatch.

**Comment by FrancisVila** [comment] 2019-02-08 14:44
I'll note down the official url. The url I mentioned was found in a link somewhere, I think it was in a github .MD file.

**Comment by brendancarney** [comment] 2019-03-25 23:42
It sounds like this is due to copying the example and using a different version of emotion in create-react-app. It would be nice to have this work for people on the latest version. I'm going to retitle the issue.

**Comment by ianstormtaylor** [comment] 2019-11-28 03:08
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Closed by ianstormtaylor** 2019-11-28 03:08 UTC
Labels: examples, ♥ help
