### ISSUE TITLE
setSelection is not scrolling item in view after updating props.

### ISSUE THREAD

**Issue by vijaiendransv** [ianstormtaylor/slate#3970] opened 2020-11-04 05:01 UTC
#### Do you want to request a _feature_ or report a _bug_?

To be considered as a bug.

#### What's the current behavior?
Whenever a selection is changed via code using `Transforms.setSelection` or `Transforms.select`, if the newly set selection is not visible, the editor is updating the selection with new props but not scrolling the block into view.

Slate: >0.58.0
Browser: Safari / Chrome
OS: Mac

#### What's the expected behavior?
Up until slate 0.57.3 whenever a selection change is triggered using `Transforms.setSelection` or `Transforms.select` and if the block selected is not visible in the screen, the piece of code in `editable.tsx` will ensure the `scrollInView` is executed and the newly set selection is made visible.

The change in behavior is suspected due to this [issue](https://github.com/ianstormtaylor/slate/pull/3654) fix merged via the commit [commit](https://github.com/ianstormtaylor/slate/commit/e25c30c7a85a3a30f13d0f544d7f8583ec1759fa).

Other commits where this could have happened can be found [here](https://github.com/ianstormtaylor/slate/compare/v0.57.3...v0.58.0)

**Comment by ridhambhat** [comment] 2021-02-19 16:41
Hey Brent, It will be great if you can assign me to this issue.

**Comment by ridhambhat** [comment] 2021-02-22 21:14
Hey @vijaiendransv, 

I was trying to reproduce this bug but was not able to. Can you please give me more information regarding the issue.

**Behavious Seen :**

When triggered function `Transforms.setSelection` programmatically, it works as expected(the editor scrolls down to the new range which is selected if it was not visible before). Do note, that the selection only takes place when the editor is in focus.

![Current Behaviour](https://i.imgur.com/Y9SQZ8b.gif)

Slate: >0.60.3
Browser: Chrome
OS: Windows

**Comment by ridhambhat** [comment] 2021-03-05 13:09
Hi @vijaiendransv ,

On further deliberation, there might be another way you might have reproduced this behavior.
You could have just kept the editor without any set width and height and relied on the scroll view of the webpage to view all the content in the editor.

Something like,

<img src="https://slack-imgs.com/?c=1&o1=ro&url=http%3A%2F%2Fg.recordit.co%2FnnH8EfYcHg.gif"></img>

In the current implementation, whenever selection is not visible and if the editor is scroll-able(has its own scroll bar) then the editor scrolls to the right position as in the previous comment. But it doesn't scroll the entire webpage.

With this information, can you elaborate what behavior do you expect and do you consider the current behavior as a bug?

**Comment by BrentFarese** [comment] 2021-04-16 16:03
Hi @vijaiendransv let us know if you can still reproduce this error as we cannot.  Will keep open if you can provide a reproduction.  Thanks!

**Comment by BrentFarese** [comment] 2021-06-24 15:43
Going to close this issue @vijaiendransv as we cannot reproduce it.  Glad to reopen if you provide a reproduction!  Thanks.

**Closed by BrentFarese** 2021-06-24 15:43 UTC
Labels: mlh
