### ISSUE TITLE
performance issues with big documents

### ISSUE THREAD

**Issue by cogell** [ianstormtaylor/slate#119] opened 2016-07-18 15:50 UTC
At 7k+ words the editor becomes unusable. This is not an issue for draftjs or prosemirror. Here is a gist with 7k+ words copy pasted from Oliver Twist for testing: https://gist.github.com/cogell/56f4e50e9092bd463f90f82b57e9e523

Great work so far!

**Comment by ianstormtaylor** [comment] 2016-07-18 20:13
Hey @cogell thanks for looking into this! I definitely want to improve the performance. Since it's so early, I think there's lots of low-hanging fruit we can fix. The first two are https://github.com/ianstormtaylor/slate/issues/59 and https://github.com/ianstormtaylor/slate/issues/65.

There are probably low-hanging fruits relating to:

- unnecessary React rendering.
- unnecessary React checking whether to touch the DOM (solved by better `shouldComponentUpdate`).
- unnecessary extra creation of [`Immutable`](https://facebook.github.io/immutable-js/) objects (solved by using [`withMutations()`](https://facebook.github.io/immutable-js/docs/#/List/withMutations) or  [`asMutable()`](https://facebook.github.io/immutable-js/docs/#/List/asMutable) potentially).

I'm hoping to get to some of these a bit later, once the core library is more locked down. If anyone else wants to help with tracking down performance issues that would be awesome!

**Comment by ianstormtaylor** [comment] 2016-07-18 22:02
@cogell could you record a video of the editor and how it's performance degrades? 

In the plain text version at 7,000 words I'm seeing it max out when typing, but unless you're typing super fast it's far from unusable. But I definitely still see room for improvement.

**Comment by ianstormtaylor** [comment] 2016-07-19 00:36
@cogell added a fix that seems to make the large documents even more performant. Let me know if you're still seeing this!

**Comment by arekkas** [comment] 2016-07-19 16:12
I stumbled upon a similar issue witch much smaller documents. This is also reproducible on your demo site by just copying the content a few times (strg+a, strg+c, strg+v). Apart from this, slate is the most awesomest thing in contenteditable every. Thank you.

To the issue: doing shouldComponentUpdate everywhere is an easy win, I strongly encourage it. If you haven't, use the React perf tools ( http://benchling.engineering/performance-engineering-with-react/ ) as well, it will save you the troubles of doing unneccessary optimization.

**Comment by arekkas** [comment] 2016-07-19 16:14
One more thing: In my experience, even `deepEqualing` is faster then react diffing the DOM. I wouldn't worry about

> unnecessary extra creation of Immutable objects (solved by using withMutations() or asMutable() potentially).

too much yet.

**Comment by howardjing** [comment] 2016-07-20 02:01
I noticed the same issues with the editor on the demo site. Looking at the timeline in chrome, it looks like the majority of time is spent in 

```

  /**
   * Check if the any of the currently selected blocks are of `type`.
   *
   * @param {String} type
   * @return {Boolean}
   */

  hasBlock = (type) => {
    const { state } = this.state
    return state.blocks.some(node => node.type == type)
  }
```

<img width="858" alt="screen shot 2016-07-19 at 9 58 10 pm" src="https://cloud.githubusercontent.com/assets/831651/16972783/43d64e6a-4dfc-11e6-9a61-b5bfe419d9e5.png">

**Comment by ianstormtaylor** [comment] 2016-07-21 02:15
Hey @howardjing thanks for digging into this! Is there any way you can post a video of the steps you took to get the report with that output? I'm not a pro with perf tools, and can't seem to reproduce.

I have ideas about how to speed this up!

**Comment by ianstormtaylor** [comment] 2016-07-21 02:22
Nevermind, I just wasn't using quite enough blocks I think. Got it working now. Investigating fixes!

**Comment by ianstormtaylor** [comment] 2016-07-21 04:33
About to land https://github.com/ianstormtaylor/slate/pull/141 which adds memoization to the `Node`-level methods, including where most of the work is being done in the `getBlocksAtRange` method as @howardjing showed.

**Comment by ianstormtaylor** [comment] 2016-07-21 04:42
Okay, can you all give `0.5.0` a test (the latest examples site is running it!) and see if the issues you were seeing at the document lengths you were testing with are gone? Thanks!

**Comment by arekkas** [comment] 2016-07-21 07:43
The issue sill persists, unfortunately. 

![slate-lagg](https://cloud.githubusercontent.com/assets/3372410/17014868/3d3abdbc-4f27-11e6-9b3e-717f2f967820.gif)

**Comment by arekkas** [comment] 2016-07-21 07:44
Is the demo site using a proper production build? Development builds cause a lot of overhead as React checks PropTypes and stuff.

**Comment by arekkas** [comment] 2016-07-21 07:48
Here's what React's perf tools are saying:

![slate-slag](https://cloud.githubusercontent.com/assets/3372410/17015050/4c0f4dca-4f28-11e6-96b5-25f0abf6df9d.PNG)

**Comment by arekkas** [comment] 2016-07-21 07:54
One of the issues, I believe, is large text nodes: 

![largetextn](https://cloud.githubusercontent.com/assets/3372410/17015146/cd5242b6-4f28-11e6-9f4c-d0256880ba09.PNG)

Maybe you could split long texts using `<span>` and save react the troubles of re-rendering the whole block.

**Comment by arekkas** [comment] 2016-07-21 07:56
It doesn't look like you're using a production build environment on slatejs.org, because Perf tools are available. I'm not sure if this is intended, but it significantly increases overall computation time.

**Comment by arekkas** [comment] 2016-07-21 08:02
On the demo site (after copy pasting the content a "few" times), it looks like the blockQuote type is being rendered a lot (most obvious outlier in the dataset). This might be a root cause of performance troubles on the demosite.

![blockquote](https://cloud.githubusercontent.com/assets/3372410/17015367/22dd973e-4f2a-11e6-955b-fd995af58ad1.PNG)

**Comment by ianstormtaylor** [comment] 2016-07-21 08:18
@arekkas nice, thanks! For that blockquote issue I've just opened https://github.com/ianstormtaylor/slate/issues/143 which is the reason it's slower than the others, since the other are all default rendered. That should speed that one up.

Hmm yeah not using production React, good point. Might be a simple way setup the build steps to ship `gh-pages` with production but keep development locally for testing.

**Comment by arekkas** [comment] 2016-07-21 08:25
It would be perfect to have both on slatejs.org - one hidden for debugging and one in production. Before you do *any* further optimization, fix the production build first. It will significantly boost performance.

**Comment by arekkas** [comment] 2016-07-21 08:26
What we usually do is, we have one npm task called `dev` and one `build`. The dev tasks starts a webpack server with hot reloading and development environment, the build one creates a production bundle.js in /dist.

**Comment by ianstormtaylor** [comment] 2016-07-27 00:28
Just pushed `0.7.7` which changes the way decorations are calculated (for code highlighting, etc.) which I think greatly improves this! Can you all check it out and tell me if you see it improved? If not I can re-open.

I'm going to close this issue in favor of opening up other, more direct ones for specific problems that can be fixed.

**Closed by ianstormtaylor** 2016-07-27 00:28 UTC
Labels: performance

**Comment by cogell** [comment] 2016-07-28 16:14
Thanks! This is coming along nicely. I'll make performance tickets more specific in the future.

**Comment by ianstormtaylor** [comment] 2016-07-28 16:49
Thanks @cogell! If you find anything else performance-wise I definitely want to hear it!

**Comment by okonet** [comment] 2016-10-20 14:06
Does 0.14.x  has a regression?

**Comment by sowasred2012** [comment] 2017-10-19 15:47
I'm seeing some pretty serious lag on very large documents, even on the demo site:
![lag](https://user-images.githubusercontent.com/2376968/31780201-ec97b82e-b4ec-11e7-904a-70e12f0f8ed9.gif)

Any chance of reopening this issue? Love this editor otherwise! :)

**Comment by arekkas** [comment] 2017-10-19 16:54
I can confirm this, the huge document worked better a few releases ago!

**Comment by ianstormtaylor** [comment] 2017-10-19 19:36
Hey folks, thanks for the report. If you want to help, please profile with Dev Tools and open an issue with a specific piece that is running slow, and maybe even ideas for how to fix it. Thanks!
