### ISSUE TITLE
Undo break block's data structure

### ISSUE THREAD

**Issue by rema7** [ianstormtaylor/slate#1510] opened 2018-01-07 10:56 UTC
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?
I have several blocks with a filled data structure. 
Steps:
1. I select several of them and left one block before selection.
2. Delete them
3. Press cmd-z

**Bolded** text stored as block's data.

Result:
All blocks come back, but the last one has data struct from the previous block.

See: http://recordit.co/DgFrqgge98

reproduced on Mac OS, Chrome & Safari
slate from master

#### What's the expected behavior?

All block must have their own data structure.

**Comment by CameronAckermanSEL** [comment] 2018-01-19 17:26
This is a duplicate of https://github.com/ianstormtaylor/slate/issues/1485. I have some findings documented there

**Closed** 2018-01-25 20:43 UTC
Labels: ⚑ needs jsfiddle
