### ISSUE TITLE
Should clipboard handler prioritize HTML over file paste?

### ISSUE THREAD

**Issue by jasonphillips** [ianstormtaylor/slate#442] opened 2016-11-21 06:35 UTC
At the moment, the core paste handling detects the "primary" type of data on the clipboard and uses only that to build the subsequent object supplied to plugin `onPaste` handlers.

As seen here, the order of detection checks for files (images, etc) before HTML content: https://github.com/ianstormtaylor/slate/blob/d28114061962a911068afb467b73cb48c54aba71/src/utils/transfer.js#L187

After a round of browser testing, I found that many uses of Microsoft Word will, as default behavior, place both an image of a selected portion of a document (whether or not it contains images) and the HTML selection on the clipboard at the same time -- and this caused the above detection to build a clipboard data object only using the file (image) data, while skipping the HTML content so that no further onPaste handlers could see it. In effect, no Word pasting was coming through, except to the images plugin when I enabled it, and then of course only as a static image of that portion of the document.

Is there any particular reason for prioritizing file content over HTML? I swapped the priority locally, and that indeed fixed the problem with pasting from the Word documents we tried. I'm not clear if another use case prompted that order of behavior; at the very least, it seems to me that the HTML content should be preserved along with the file data, so that onPaste handlers can access it unless a plugin prior in the chain decided to use the former.

**Comment by ianstormtaylor** [comment] 2016-11-21 21:36
Hey @jasonphillips good question! I can confirm that with macOS `10.12` and Word for Mac `2011` I also get the image-only behavior you describe.

For ordering, the way I see it is that the paste data types are constructed as fallbacks. Such that it's common to add "lower fidelity" types to the payload so that "dumber" environments can fallback to them nicely. For example it's common to add `text` as a fallback when dealing with HTML, or even potentially PDFs or other types of files. Using `html` as a fallback is probably slightly rarer, but I figured it was probably valid for rich-text cases, so that's why it comes after `files`.

This case is weird though since Word is using an image as a fallback for rich text, which is unfortunate... 

Working on a fix for this now.

**Closed** 2016-11-21 22:03 UTC
Labels: bug
