### ISSUE TITLE
bug: `normalizeNode` is not called on all changed nodes.

### ISSUE THREAD

**Issue by bebbi** [ianstormtaylor/slate#2521] opened 2019-01-03 14:16 UTC
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

The `normalizeNode` function does not check all relevant nodes on editor changes in trees, and the editor state degrades.

##### Editor structure to normalize:
This is a simplified example of our use-case which requires the `normalizeNode` function.
The allowed editor structure is a tree: a `container` node (a node of `{ type: 'container' }`) which contains a `paragraph` as a first child node, and optionally more `container`s as subsequent children nodes.

This structure gets broken by edit operations because `normalizeNode` is not called on all changed nodes.

##### Reproduction:

(macos 10.14.2/Chrome 71/0.44.9)

The repro annotates the editor value with keys in `node.data` for easier reading.

1. Open https://jsfiddle.net/gLk4dh29/1/
2. Open the dev console
3. Put the cursor at the start of the second line that ends with "para 2"
4. Hit Backspace and see the first 2 lines merge.
5. Move the cursor to the last line and enter any character.
6. See the console output from the `normalizeNode` function which found an illegal structure but is called too late.

#### What's the expected behavior?

Right at step 4 of the repro, `normalizeNode` should be called with the node `container 2` because the structure of that node has changed.

**Comment by CameronAckermanSEL** [comment] 2019-01-03 15:15
I think the root cause of this issue is that the `getDirtyPaths` function that is called in `applyOperation` doesn't grab the correct path for where the node used to be when it is merged out of a parent node.

https://github.com/ianstormtaylor/slate/blob/76a88a649a9ec7d27d207416d94b3de1de0828d6/packages/slate/src/controllers/editor.js#L520

At least I think so, I'm having some trouble groking this (haven't had coffee yet ;))

**Comment by CameronAckermanSEL** [comment] 2019-01-04 17:08
I think we might be missing a few dirty nodes here:

1. Like in move node, we probably need to get the previous set of ancestors in conjunction with the new ancestors.
2. To address the previous rule, we need to also get the sibling of the previous path.

**Closed** 2019-03-07 23:08 UTC
Labels: bug, ♥ help please
