### ISSUE TITLE
Internal copy paste is broken

### ISSUE THREAD

**Issue by skogsmaskin** [ianstormtaylor/slate#734] opened 2017-04-19 22:33 UTC
Version 0.19.16 was the last version where copy and pasting internally in the document worked as expected (keeping the formatting intact). The ``.fragment`` document is now ``null``, and there is only a ``.html`` part, thus it falls back to ``onPasteText`` by the default core plugin. I suspect it has something to do with #716.

If you try copying and pasting the contents of http://slatejs.org/#/rich-text?_k=952y37, you see what I mean.

**Comment by skogsmaskin** [comment] 2017-04-19 23:20
Confirmed it happened with 3e573453a8c5d92963d3f290fb7266f66e2a6b78.

**Comment by skogsmaskin** [comment] 2017-04-20 01:12
What is happening is that the span with the encoded data is no longer on the clipboard, thus [getTransferData](https://github.com/ianstormtaylor/slate/blob/master/src/utils/get-transfer-data.js#L30) don´t recognize it as a fragment.

**Comment by skogsmaskin** [comment] 2017-04-20 08:10
Temporarily fixed by #736 (revert patch 3e573453a8c5d92963d3f290fb7266f66e2a6b78).

**Comment by skogsmaskin** [comment] 2017-04-20 08:12
Regretted closing it. Should be some tests in place.

**Comment by ianstormtaylor** [comment] 2017-05-01 18:20
Seems like this is fixed now.

**Comment by SebAshton** [comment] 2017-05-25 10:48
@ianstormtaylor I think this may have regressed. Confirmed on http://slatejs.org/#/rich-text.

![bug_report](https://cloud.githubusercontent.com/assets/881759/26447281/bedd04e6-413f-11e7-99e9-0133ea4ff750.gif)

Neither the marks, or blocks are correctly copied/pasted.

**Browser** Chrome - Version 58.0.3029.110 (64-bit)

**Comment by illesg** [comment] 2017-06-26 10:08
I can reproduce it too with the official example the same way as @SebAshton 

Browser: Chrome, Version 59.0.3071.109 (Official Build) (64-bit)

**Comment by danburzo** [comment] 2017-08-23 23:48
There are a hosts of problems relating to copy/paste in Chrome and Safari and they stem from a single problem:

```js
    const r = window.document.createRange()
    r.selectNodeContents(div)
    native.removeAllRanges()
    native.addRange(r)
```

And the <div> has a single child node, on copy the _content_ of the child node is copied instead of the _entire_ child node (as it happens in Firefox), i.e. Webkit will copy the "inner HTML" while Firefox will copy the "outer HTML". What this means in practice is that the fragment data, which resides on the outer HTML, will be lost to Webkit in a host of situations, and it has to fall back to the HTML content, which is a single, unstyled span.

A secondary problem is that any trailing whitespace is also lost in the process, but this can be fixed with a `white-space: pre-wrap` on the temporary div that gets created to hold the copy data.

I'm not sure if this behavior is intended (or what spec governs it), but I have not found a way yet to make the selection take the "outer html" in this situation. `Selection.selectAllChildren()` is different from `Range.selectNodeContents` in subtle ways but exhibits the same essential problems.

There is of course the possibility of always ensuring we have at least two child nodes by inserting a dummy node, but it needs to have non-empty content (a zero width space perhaps), and pasting into external apps will introduce these unwelcome artifacts.

Alternatively, we can theoretically use `clipboardData.setData('text/plain')` and `clipboardData.setData('text/html')` on the copy event and eschew the div thing entirely.

**Comment by ianstormtaylor** [comment] 2017-08-24 16:50
Hey @danburzo could you screencast the issue to show how the problems manifest themselves? I'm  just wondering because I'm not able to reproduce whatever the issue is, which I'm assuming is because I'm trying to reproduce it wrong.

In the rich text example, I can copy/paste internally inside a single paragraph maintaining bold text:

![](http://g.recordit.co/MYnhMmvRDe.gif)

And I can copy/paste externally when only copying inside a single node:

![](http://g.recordit.co/tIsEczvlm7.gif)

**Comment by ianstormtaylor** [comment] 2017-08-24 16:53
Ah I'm dumb, I didn't watch @SebAshton's GIF carefully enough, it's only a problem when the selection is completely inside a mark like a bold mark:

![](http://g.recordit.co/NvDGIDkZvH.gif)

**Comment by ianstormtaylor** [comment] 2017-08-24 16:56
Does anyone know how Draft.js solves this?

**Comment by dmitrizzle** [comment] 2017-08-25 15:14
I can confirm that copy-paste for HTML worked well on `0.20.6` and stopped working once I upgraded to `0.21.3` - for everything (right now all HTML formatting gets purged, no matter where I paste from). I've been testing with Chrome 60 macOS 10.12

I'm using the exact code as in the example (but implemented in a different project).

Can the changes that caused the breakage be rolled back in the next version?

I obviously don't understand most of the details with this issue, just a casual user's perspective: "it worked before but now it doesn't."

**Comment by ashutoshrishi** [comment] 2017-10-30 04:35
Still getting instances where `onCutOrCopy` handler creates the fake div properly, but the browser (Chrome) does not copy that. Hence the `getEventTransfer()` does not get the slate fragment.

Is there any reason the `onCutOrCopy` does not use 

```
    event.clipboardData.setData('application/x-slate-fragment', encoded)
    event.preventDefault()
```

With this the `getEventTransfer` helper is always able to recognise the copied fragment. I am assuming this causes Compatibility issues.

**Comment by jennaplusplus** [comment] 2017-11-29 22:03
Seconding @ashutoshrishi that this is broken in Chrome and we end up with a null fragment and only html. For me this causes a weird issue with background color: 
![copypaste](https://user-images.githubusercontent.com/13112590/33401390-fa55129a-d50d-11e7-9573-dda56d14d242.gif)

Would love to know if this an easy fix with @ashutoshrishi's solution.

**Comment by ianstormtaylor** [comment] 2017-12-02 20:36
@ashutoshrishi @jennaplusplus I assume that it causes compatibility issues, but I'm not sure. I'd be open to a PR that investigates this and fixes it for all browsers though.

**Comment by czechdave** [comment] 2017-12-15 12:08
I'm not sure if this is a separate issue or not but when copy/pasting paragraph with inlines from a "hanging selection", the inlines don't make it through:
![inline bug](https://user-images.githubusercontent.com/8127927/34041581-f0a1e0ba-e198-11e7-87f9-b7f576133864.gif)

**Comment by mfbx9da4** [comment] 2017-12-18 14:20
Pasting links work if you select to the beginning of the line but not if you select just above the line which transforms the selection into a text only multiline selection (I am guessing)?

![o1yenvkn7q](https://user-images.githubusercontent.com/1690659/34110232-6325d12e-e3dc-11e7-808b-623479ea72df.gif)

Similar issue with pasting images. How does the paste selection change for multi line selections?

**Comment by Soreine** [comment] 2018-03-14 13:19
The state of this issue is not clear. Most of the issues initially mentioned seem to be resolved.

Should we close this issue and invite people to open new issues for the unresolved bugs? Or could someone sum up the state of this issue ?

**Comment by ianstormtaylor** [comment] 2018-03-21 01:59
@Soreine sounds good to me!

If anyone is experiencing something from this issue, please open a new one with a specific description and reproduction case. Thanks!

**Closed by ianstormtaylor** 2018-03-21 01:59 UTC
Labels: bug, ♥ help please
