### ISSUE TITLE
Mouse dragging all text from Slate into non-Slate input destroys the editor

### ISSUE THREAD

**Issue by gdehmlow** [ianstormtaylor/slate#874] opened 2017-06-09 00:10 UTC
#### Do you want to request a *feature* or report a *bug*?

Bug

#### What's the current behavior?

I actually discovered this in [DraftJS](https://github.com/facebook/draft-js/issues/1240) and figured it would apply to Slate as well.

If you click and drag all of the text in a Slate editor with your mouse out of a Slate editor into a non-Slate input, it.. removes the Slate editor. 

https://jsfiddle.net/h74rvhha/

#### What's the expected behavior?

It shouldn't destroy the editor.

I don't know if there's a good way to fix this, as DraftJS and Draft-Quill both seem to suffer from this problem as well (they both use `contenteditable`), except maybe being clever and handling drops on other `input`s in your app with a nice `e.preventDefault()`

**Comment by Tzelon** [comment] 2019-02-12 11:43
I can't reproduce the problem

**Comment by brendancarney** [comment] 2019-02-23 16:07
Can't reproduce: https://codesandbox.io/s/9zp8zmx76y

**Comment by adjourn** [comment] 2019-02-23 17:39
Editor doesn't get destroyed but editor `div` has loses all children after drag and I get errors when I try to type or drag content back after that. (Chromium, Ubuntu)

![sh](https://user-images.githubusercontent.com/17890701/53289731-7e9da100-37a2-11e9-8191-5936fe4e8c1a.png)

**Comment by brendancarney** [comment] 2019-03-26 00:13
Ah, so maybe we're not updating the value to remove the nodes. We may need to be handling some drag/drop event or using MutationObserver

**Comment by ianstormtaylor** [comment] 2019-11-28 03:08
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Closed by ianstormtaylor** 2019-11-28 03:08 UTC
Labels: bug, ♥ help
