### ISSUE TITLE
Unable to delete mention in mentions sample

### ISSUE THREAD

**Issue by thunderousNinja** [ianstormtaylor/slate#3282] opened 2019-12-10 04:43 UTC
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

Steps:

1. Go to: https://www.slatejs.org/examples/mentions
2. Click on a mention so it is focused/selected (blue border should be around the mention).
3. Press press backspace or delete.
4. Nothing happens.

This works on [embed ](https://www.slatejs.org/examples/embeds) and [image ](https://www.slatejs.org/examples/images) examples.

-->

Slate: Latest version on Slate site.
Browser: Chrome / Safari / Firefox
OS: Mac / Window

#### What's the expected behavior?

When you click on a mention, and it is focused/selected, then hit backspace/delete it should remove the mention.

**Comment by eddyw** [comment] 2019-12-10 16:18
I don't know if this is a bug on the example itself or how inline | voids are handled.
This works:
```typescript
const MentionElement = ({ attributes, children, element }) => {
  const selected = useSelected()
  const focused = useFocused()
  return (
    <React.Fragment>
      <span
        {...attributes} // <<< it'll insert contenteditable={false}
        style={{
          padding: '3px 3px 2px',
          margin: '0 1px',
          verticalAlign: 'baseline',
          display: 'inline-block',
          borderRadius: '4px',
          backgroundColor: '#eee',
          fontSize: '0.9em',
          boxShadow: selected && focused ? '0 0 0 2px #B4D5FF' : 'none',
        }}
      >
        @{element.character}
      </span>
      {children} // <<< outside
    </React.Fragment>
  )
}
```
@ianstormtaylor could you please clarify? 🙃 
It seems like the zero-width char should be within `contenteditable={true}` to be able to delete the mention by clicking on it and pressing backspace. Otherwise, `onDOMBeforeInput` isn't triggered on pressing backspace.

**Comment by ianstormtaylor** [comment] 2019-12-10 17:54
@eddyw your intuition sounds right to me. Maybe it would be working if the DOM structure matched what's happening in the `images` example? Which I think is slightly different in terms of where `children` lives.

**Comment by eddyw** [comment] 2019-12-10 19:34
Ok, previous code I shared crashes on right click 🙈 

@ianstormtaylor I checked the source in `slate-react/.../element.tsx` and it's doing:
```typescript
    if (!readOnly && isInline) {
      attributes.contentEditable = false
    }
```
Is this necessary? In the images example, we are adding the `contenteditable={false}` ourselves, is there a reason why it's added automatically for inlines?

In any case, removing `contenteditable` and assigning ourselves as in images example (matching DOM structure) works:
```typescript
const MentionElement = ({ attributes: allAttributes, children, element }) => {
  const { contentEditable, ...attributes } = allAttributes // remove auto-added contentEditable
  const selected = useSelected()
  const focused = useFocused()
  return (
    <span
      {...attributes} // << as in images example
      style={{
        padding: '3px 3px 2px',
        margin: '0 1px',
        verticalAlign: 'baseline',
        display: 'inline-block',
        borderRadius: '4px',
        backgroundColor: '#eee',
        fontSize: '0.9em',
        boxShadow: selected && focused ? '0 0 0 2px #B4D5FF' : 'none',
      }}
    >
      <span contentEditable={contentEditable}>@{element.character}</span>
      {children}
    </span>
  )
}
```
Bug or feature? 🙈

**Comment by ianstormtaylor** [comment] 2019-12-10 19:54
Haha uhoh, clearly that needed a `COMPAT` comment. I'm sure it was added for a reason. But I'm down to try tweaking it and seeing if it can be fixed.

Does it work when doing it _exactly_ like the images example, with a hard-coded `contentEditable={false}`?

**Comment by eddyw** [comment] 2019-12-10 19:57
@ianstormtaylor yes, it works if hard-cored. It's what I did here:
```typescript
<span contentEditable={contentEditable}>@{element.character}</span>
```
Since `contentEditable` would be `false` because it's inline and this:
```
    if (!readOnly && isInline) {
      attributes.contentEditable = false
    }
```
Then it's equivalent to the images example (in structure)

**Comment by ianstormtaylor** [comment] 2019-12-10 20:54
@eddyw but the difference in that snippet above is that `{ contentEditable, ...attributes }` is special-cased, whereas it's not in the images example. And I don't want to have that leakiness exposed to users for all voids.

**Comment by CameronAckermanSEL** [comment] 2020-02-26 06:32
Hey guys, I went to go check this on the current live example and I'm able to delete the mentions on chrome so I'm going to close this issue. If you guys find it's still a problem, please let me know and I'll reopen it.

**Closed by CameronAckermanSEL** 2020-02-26 06:32 UTC
Labels: bug, ♥ help

**Comment by Eld0ud** [comment] 2020-06-29 15:55
Still not working on chrome (v83.0.4103.116)

**Comment by markogresak** [comment] 2020-07-24 20:48
@CameronAckermanSEL did you follow the exact steps to reproduce? 

> Steps:
> 
> 1. Go to: https://www.slatejs.org/examples/mentions
> 2. **Click on a mention** so it is focused/selected (blue border should be around the mention).
> 3. Press press backspace or delete.
> 4. Nothing happens.

The Click part is important. Yes, it works if you focus the block and use backspace. But if you click the mention element, or use the keyboard to focus it, deleting will not work.

Please reopen this issue as it's not fixed.

**Comment by markogresak** [comment] 2020-08-04 14:38
The fix here is to add one more child `span` and ensure the `children` are rendered as a direct descendant of the element with `{...attributes}`, but _without_ `contentEditable={false}`. 
See point 3. here: https://github.com/ianstormtaylor/slate/issues/3813#issuecomment-668634790

**Comment by golota60** [comment] 2021-06-08 12:39
For anybody looking for a solution: I was encountering this bug using chrome(v90.0.4430.212) with `slate-react` v0.63, but upgrading it to v0.65 fixed the issue for me
