### ISSUE TITLE
input error on window10 Pinyin IME

### ISSUE THREAD

**Issue by olabala** [ianstormtaylor/slate#2796] opened 2019-05-17 04:44 UTC
#### Do you want to request a _feature_ or report a _bug_?
BUG

#### What's the current behavior?
I can not input anything after I type about 20+ characters, and there is some issue with the rendering either.

here is a [video](https://www.youtube.com/watch?v=HdE90uIxtos&feature=youtu.be) about this issue，I have been typing the entire process without deleting.

I guess it may be a problem with the IME（Pinyin IME,  windows 10）. I tried it under mac and it works well.

#### What's the expected behavior?
slate works well

**Comment by ianstormtaylor** [comment] 2019-05-20 21:43
Hey, thanks for reporting this. I think this is actually a duplicate of https://github.com/ianstormtaylor/slate/issues/2368, so I'm going to close this in favor of that one. Feel free to comment over there with any other info!

**Closed by ianstormtaylor** 2019-05-20 21:43 UTC
