### ISSUE TITLE
Undo of inserting nodes fails, leads to console error

### ISSUE THREAD

**Issue by oyeanuj** [ianstormtaylor/slate#851] opened 2017-05-26 21:49 UTC
Hi @ianstormtaylor, I was intending to simulate cut/paste from one kind of node to another. Essentially, when a user highlights a certain text, and clicks a button, it should convert it to a new node type at the top level, no matter how nested the text might be.

I've gotten that to work by inserting all the nodes in `state.fragment` into the new block but it breaks the undo behavior. Not sure if there is a better way to do it that wouldn't lead to the undo failing or if it is hitting a limitation in undo logic.

Here is a simple JSFiddle illustrating that with the steps: https://jsfiddle.net/urr1z99g/2/

Relevant Code Pieces:
```js

  /**
  * Inserts the nodes of a fragment in the destination block
  * @param  {Transform}	transform
  * @param  {Fragment}	fragment
  * @param  {Block}		destination
  * @return {Transform}
  **/
  insertFragmentNodes = (transform, fragment, destination) => {
    let indexToInsert = 1;

    fragment.nodes.forEach((node) => {
      console.log('inserting node', node);
      transform.insertNodeByKey(destination.key, indexToInsert, node);
      indexToInsert += 1;
    });

    return transform;
  };

  onClickBlock = (e, type) => {
    e.preventDefault()
    
    const currentState = this.state.state
    const frag = currentState.fragment
    const newArticle = Block.create({ type: 'article', isVoid: false })
    
    console.log(frag);
    const state = currentState
      .transform()
      .deleteAtRange(currentState.selection)
      .insertNodeByKey(currentState.document.key, 0, newArticle)
      .call(this.insertFragmentNodes, currentState.fragment, newArticle)
      .apply()
      
    this.setState({ state: state })
  }
````

Console error:
```
Uncaught Error: Could not find a descendant at path "0,3".
    at Document.assertPath (https://npmcdn.com/slate@0.20.1/dist/slate.js:37030:13)
    at removeNode (https://npmcdn.com/slate@0.20.1/dist/slate.js:45225:23)
    at Object.Transforms.applyOperation (https://npmcdn.com/slate@0.20.1/dist/slate.js:44981:21)
    at Transform.(anonymous function) [as applyOperation] (https://npmcdn.com/slate@0.20.1/dist/slate.js:42041:32)
    at https://npmcdn.com/slate@0.20.1/dist/slate.js:48408:17
    at Array.forEach (<anonymous>)
    at https://npmcdn.com/slate@0.20.1/dist/slate.js:48407:16
    at Array.forEach (<anonymous>)
    at Object.Transforms.undo (https://npmcdn.com/slate@0.20.1/dist/slate.js:48406:30)
    at Transform.(anonymous function) [as undo]
```

Thanks!

**Comment by ianstormtaylor** [comment] 2017-10-26 20:40
This issue hasn't had a response in a while, and it's unclear if it's still present in the latest versions of Slate. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice that the bug is still happening, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!

**Closed by ianstormtaylor** 2017-10-26 20:40 UTC

**Comment by abhi-nav** [comment] 2020-04-17 11:19
Hi I am also getting the same console error. However Node is successfully removed. I am not sure if I am missing something.

Slate Version: 0.57.1

Error at Command: `Transforms.removeNodes(editor, {match: n => n.type === 'video'})`
Also with command `Transforms.removeNodes(editor, {at: path})`

> Uncaught Error: Cannot find a descendant at path [2] in node: {"children":[{"type":"paragraph","children":[{"text":"simpletext"}]},{"type":"paragraph","children":[{"text":"boldtext","bold":true}]}],"operations":[{"type":"remove_node","path":[2],"node":{"type":"video","url":"https://youtu.be/NXFTK1XAVH0","children":[{"text":"https://youtu.be/NXFTK1XAVH0"}]}}],"selection":{"anchor":{"path":[1,0],"offset":8},"focus":{"path":[1,0],"offset":8}},"marks":null}

Thanks for the great editor.

**Comment by swashata** [comment] 2020-05-14 15:28
Hello,

This is happening for me too. I will try to create a reproducible repo.

**Comment by chrisdostert** [comment] 2020-09-06 06:53
This happens for me as well when I use `Transforms.removeNodes(editor, {at: path}`. As a workaround, `Transforms.removeNodes(editor)` works successfully (i.e. doesn't break undo).
