### ISSUE TITLE
undo twice not working

### ISSUE THREAD

**Issue by chilijung** [ianstormtaylor/slate#451] opened 2016-11-24 02:50 UTC
demo: https://jsfiddle.net/chilijung/4890mgej/1/

modified two places and push undo button twice, it will have error `TypeError: op.inverse is undefined`

**Comment by ianstormtaylor** [comment] 2016-11-30 00:23
Hey @chilijung I can't reproduce this one, can you give me some more info? What specific modifications are you making, etc?

**Comment by chilijung** [comment] 2016-11-30 02:15
@ianstormtaylor fixed the link. Forget to saved the fiddle.

**Comment by thesunny** [comment] 2016-12-01 06:55
Hi @chilijung,

I posted a fix for you here: https://jsfiddle.net/4890mgej/2/

I made one change. It was to add `apply({save: false})` which I found in the undo code here: https://github.com/ianstormtaylor/slate/blob/master/src/plugins/core.js#L600

Here is updated code for reference:

```js
  undo() {
    const state = this.state.state
      .transform()
      .undo()
      .apply({save: false});
      
    this.setState({ state });
  }
```

It might be a good idea to have `{save: false}` set automatically if there is an `undo()` operation involved. Not sure how easy this would be though.

**Comment by ianstormtaylor** [comment] 2016-12-01 16:58
@thesunny good find! Thank you!

I'm going to close this one in that case, but I've opened an issue for a UX improvement to make this less confusing for the future.

**Closed by ianstormtaylor** 2016-12-01 16:58 UTC
Labels: bug
