### ISSUE TITLE
Performance issue in larger documents

### ISSUE THREAD

**Issue by mirrec** [ianstormtaylor/slate#944] opened 2017-07-20 15:45 UTC
Hello,
First of all, slatejs is very nice library with great documentation! Awesome work! Thanks a lof for that.

#### What's the current behavior?

In larger documents (e.g. http://slatejs.org/#/dev-large) redrawing is a bit slow. It takes quite a lot of time when I hit `enter`, to draw new section block.
If I select all text in `dev-large`, copy it, remove it and then paste it back, editor even freezes for a few seconds.

#### What's the expected behavior?

When I do the same in [ProseMirror](http://prosemirror.net), everything is very fast and smooth.

---

Do you know about this issue? Is it something that can change in near future?

All the best

**Comment by ianstormtaylor** [comment] 2017-07-20 16:59
Hey @mirrec thanks for the kind words. Performance is definitely something that we're constantly looking for places to improve in Slate. There are a few open issues that mention similar things, check out the [`performance`](https://github.com/ianstormtaylor/slate/issues?q=is%3Aopen+is%3Aissue+label%3A%22%E2%9A%91+performance%22) issue label for them. I'm going to close this one as a duplicate of those. I'd love any help with them! Thanks

**Closed by ianstormtaylor** 2017-07-20 16:59 UTC
