### ISSUE TITLE
deleteLineForward borks selection range on demo

### ISSUE THREAD

**Issue by mattkrick** [ianstormtaylor/slate#1966] opened 2018-07-11 01:28 UTC
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

hitting delete line foward delete as expected, but the cursor ends up in the wrong spot
![borkdeletelineforward](https://user-images.githubusercontent.com/5514175/42545802-f4bfb0d6-846e-11e8-9202-6ea676556bf3.gif)

Chrome 67
Ubuntu 16.04
Slate demo website

**Comment by zhujinxuan** [comment] 2018-07-12 15:45
> hitting delete line foward delete as expected, but the cursor ends up in the wrong spot

Can I know which key you are using?  I tried `ctrl-k` in mac, and I cannot reproduce the result.

**Comment by zhujinxuan** [comment] 2018-07-12 21:43
I think the reason is `ctrl + shift + delete` is not captured in slate-hotkeys.  I will change a PR to support it.

**Comment by zhujinxuan** [comment] 2018-07-12 21:53
I think it is fixed in https://github.com/ianstormtaylor/slate/pull/1888

Can you have a try of delete backward/forward in PR preview (https://deploy-preview-1888--slatejs.netlify.com/#/rich-text)

**Comment by mattkrick** [comment] 2018-07-14 13:31
confirmed working!

**Comment by ianstormtaylor** [comment] 2019-11-28 02:42
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Closed by ianstormtaylor** 2019-11-28 02:42 UTC
Labels: bug, ♥ help
