### ISSUE TITLE
Significant performance decrease when updating slate from 0.27.x to 0.28.x or higher

### ISSUE THREAD

**Issue by HydraOrc** [ianstormtaylor/slate#1401] opened 2017-11-14 11:19 UTC
I have a project where there are lots of editors on the page and updating higher than 0.27.x makes it just impossible to use some features of the project at all, because everything becomes slowed down too much.

I am not sure, but probably it could be the case of the new normalization or the old shema versus renderNode/renderMark functions, because that are the differences in my code for these versions.

**Comment by lxcid** [comment] 2017-11-14 13:43
I did face similar issue. The performance regression is pretty noticeable for me as well.

One of the issue I identified is described in https://github.com/ianstormtaylor/slate/issues/1318#issuecomment-341956697

First, the `<Editor />` will always trigger `onChange()` when component load because `Value`'s `Schema` does not match `<Editor />`'s `Schema`.

Second, the `onChange()` is triggered by a timer, which if you end up having large number of editors, it just cause a huge hang on start up.

I do hope we can work around this issue, Slate used to be really performant for such use case, I hope it doesn't lose that capability.

**Comment by lxcid** [comment] 2017-11-14 13:50
I going copy my comment from https://github.com/ianstormtaylor/slate/issues/1318#issuecomment-341956697 to here as the ticket is already closed.

> I'm facing a new issue though, as we are using `setTimeout()` for the new behaviour, on browser like Safari that does not aggressively process those timeout in a timely manner, you can see that timeout build up as well. So if I duplicate the number of editors by 10x in the jsfiddle running inside Safari, the console will slowly print out the debug statement one after another.
> 
> I understand I am using Slate very differently from the normal path, but this is a regression for me, before the change, older version was very capable on rendering hundreds of `<Editor />` components.
> 
> Analysing the situation, I identify the following issues:
> 
> - flushing of changes only happen in `componentDidMount()` and `componentDidUpdate()`, although you have specifically documented the rationale for having change queue, it doesn't seems like a bad idea to trigger the `onChange()` event immediately during these component life cycle.
> - `setTimeout()` might not be immediate.
> - Value's schema must be exact reference to Editor's schema (identity), even if their value is the same, if not, `onChange()` event is fired.
> - There's no way we can pass in a schema from the outside (update Value's schema) so as to suppress the `onChange()` situation.
> 
> I'm still digging the code to see if I can workaround the issue. I haven't gotten up to speed with the latest changes, will keep you updated!
> 
> ### References
> 
> - [setTimeout() - Reasons for delays longer than specified](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#Reasons_for_delays_longer_than_specified)

**Comment by HydraOrc** [comment] 2017-11-14 15:00
@lxcid, your issue is closed, so have you managed to fix it? I have tried the newest version of package today in the morning before writing mine and it was still present.

I append the shrinked and cut code sample of my wysiwyg component to show what i have.

`import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { fromJS } from 'immutable';
import { connect } from 'react-redux';
import { Value } from 'slate';
import { Editor } from 'slate-react';
import cx from 'classnames';
import assign from 'lodash/assign';
import debounce from 'lodash/debounce';
import each from 'lodash/each';
import get from 'lodash/get';
import isUndefined from 'lodash/isUndefined';
import isFunction from 'lodash/isFunction';
import set from 'lodash/set';
import marks, { marksForSchema } from './marks';
import nodes, { nodesForSchema } from './nodes';
import { getLang, getLabelConfig } from './selectors';
import { getLabelValue } from '../../utils/scenario/selectors';
import { setLabel } from '../../utils/scenario/actions';
import styles from './css/wysiwyg.css';

const defaultNodes = [
  {
    type: 'span',
    nodes: [
      {
        kind: 'text',
        text: '',
      }
    ],
    kind: 'block'
  }
];

export class RedactorWysiwyg extends Component {
  static propTypes = {
    id: PropTypes.string.isRequired,
    lang: PropTypes.string.isRequired,
    config: PropTypes.object.isRequired, // eslint-disable-line
    className: PropTypes.string,
    structure: PropTypes.object, // eslint-disable-line
    readOnly: PropTypes.bool,
    setLabel: PropTypes.func.isRequired,
  }

  static defaultProps = {
    config: fromJS({}),
    toolbarStyle: {},
    withoutToolbar: false,
  }

  state = {
    version: 0,
  }

  componentWillMount() {
    this.prepareState(this.props);

    this.setLabel = debounce(this.setLabel, 150, { leading: true });
  }

  componentWillReceiveProps(newProps) {
    if (this.lang === newProps.lang) {
      return;
    }

    this.prepareState(newProps);
  }

  prepareState(props) {
    this.lang = props.lang;

    const structure = props.structure || props.config.get('structure').toJS();

    if (!structure.nodes.length) {
      set(structure, 'nodes', defaultNodes);
    }

    this.setState({
      value: Value.fromJSON({
        document: structure,
      }),
    });
  }

  onFocus = () => {
    this.setState({
      version: ++this.state.version,
    });
  }

  onChange = (change) => {
    const { value } = change;

    this.setState({
      value,
    });

    this.setLabel(value);
  }

  setLabel = (value) => {
    const { lang, id } = this.props;

    const structure = value.toJSON().document;

    this.props.setLabel({ lang, id, structure });
  }

  renderNode = (data) => {
    const { children, node } = data;

    const Node = nodesForSchema[node.type];

    return (
      <Node {...data}>
        {children}
      </Node>
    );
  }

  renderMark = (data) => {
    const { mark } = data;

    const Mark = marksForSchema[mark.type];

    if (isFunction(Mark)) {
      return <Mark {...data} />;
    }

    return (
      <span style={Mark} {...data} />
    );
  }

  render() {
    const { id, className, readOnly } = this.props;

    const { value } = this.state;

    return (
      <div
        className={className}
        data-id={id}
      >
        <Editor
          className={styles.editor}
          value={value}
          readOnly={readOnly}
          onFocus={this.onFocus}
          onKeyUp={this.onKeyUp}
          onChange={this.onChange}
          renderNode={this.renderNode}
          renderMark={this.renderMark}
        />
      </div>
    );
  }
}

const mapStateToProps = () => (state, { lang = getLang(state).get('code'), id, structure }) => ({
  config: getLabelConfig(state, id),
  structure: structure || getLabelValue(state, { lang, id }),
  lang,
});

export default connect(
  mapStateToProps,
  {
    setLabel,
  },
)(RedactorWysiwyg);`

**Comment by lxcid** [comment] 2017-11-14 15:31
It was still usable for me. @HydraOrc, will u be able to create a jsfiddle to showcase your issue?

https://jsfiddle.net/2zokvrvt/192/

U might have to change the state to value in the JSFiddle though.

**Comment by HydraOrc** [comment] 2017-11-15 13:07
With the newest version: https://jsfiddle.net/HydraOrc/4hutkdxb/
With the old good-working version: https://jsfiddle.net/HydraOrc/6v1nhztr/
I see that this case is not so slow to showcase my issue, but in the real project the code with the newest version causes the significant performance decrease

**Comment by lxcid** [comment] 2017-11-16 09:47
Nice @HydraOrc, I do want to be able to help improve this aspect of the codebase. I'll do some investigation on top of what I suspecting at the moment when I have some time this week! I'll keep this thread updated.

**Comment by davegw** [comment] 2017-11-22 18:31
+1. I have a similar use case with multiple editors that would prevent me from updating past 0.27.x. Let me know if I can help.

**Comment by TimYi** [comment] 2017-11-28 06:35
We have a huge word document, about 700 pages, we transfer to slate document, but we can't open this document whit slate 0.31.3

**Comment by ianstormtaylor** [comment] 2018-10-26 05:50
A lot of the logic has changed since `0.27`, so I'm going to close this. Feel free to open new issues with specific performance bottlenecks!

**Closed by ianstormtaylor** 2018-10-26 05:50 UTC
