### ISSUE TITLE
Editor crashes on hitting enter key

### ISSUE THREAD

**Issue by udhay-appminds** [ianstormtaylor/slate#4955] opened 2022-04-20 11:23 UTC
**Description**
 Hi team
I am using below version for react slate edittor
"slate": "^0.76.1",
 "slate-history": "^0.66.0",
 "slate-hyperscript": "^0.67.0",
  "slate-react": "^0.76.1",
**In updated chrome(100.0.4896.88) or firefox(99.0.1) both browsers are 64bit on mac os catalina**, 
when I hit enter on editor I am getting below error

![Screenshot 2022-04-20 at 4 33 54 PM](https://user-images.githubusercontent.com/99753285/164218107-6d37e6cb-4697-4562-b61f-2a20efecec00.png)

After that i have updated to below version
"slate": "^0.77.2",
    "slate-history": "^0.66.0",
    "slate-hyperscript": "^0.77.2",
    "slate-react": "^0.77.2"

After that, I am not getting the old issue, but the initial value is not loading when the page reloads

**Comment by BitPhinix** [comment] 2022-04-20 17:18
Hard to say what exactly is going on here. I suspect it's something specific to your implementation, although it could very well be a bug in slate as well. Can you share a code sandbox or something along those lines where we can reproduce the issue?

**Comment by udhay-appminds** [comment] 2022-04-28 02:50
HI team , we have the below sandbox env  
https://dev.sportsblog.com/

You can sign up , go with the flow and select free plan when asks  and create a new blog 
once you reach the dashboard page click on new post , in which you will find the editor

**Comment by udhay-appminds** [comment] 2022-04-28 09:36
adding a video of the issue [](url

https://user-images.githubusercontent.com/99753285/165723881-d9f25ac7-5c21-4fd2-bd42-4c65c6c23ee1.mov

)

**Comment by udhay-appminds** [comment] 2022-04-28 10:18
We also have another issue, when we try to edit the article, the content is not loading in editor.

https://user-images.githubusercontent.com/99753285/165731018-c0223631-a75d-4169-9751-a00e2a917fcb.mov

**Comment by srinivas-appminds** [comment] 2022-05-04 12:05
Hi Team

any response for above issue ?

**Comment by srinivas-appminds** [comment] 2022-05-04 15:50
It worked fine till few days back, when users update their browser versions they face this issue.

**Comment by dylans** [comment] 2022-05-04 18:11
> It worked fine till few days back, when users update their browser versions they face this issue.

Based on this I would have guessed that you are missing https://github.com/ianstormtaylor/slate/commit/3b3b0e32df4df9fb4cf1d82c0c09b7242c708169 but your version number should support that fix. Again, asking us to debug a production app isn't going to happen, and is no more useful than me giving you access to our app to show things working fine. :)

**Comment by thesunny** [comment] 2023-03-01 07:46
Since they can't be answered without more info and it doesn't seem to be forthcoming at this point, I'm closing this.

**Closed by thesunny** 2023-03-01 07:46 UTC
Labels: bug
