### ISSUE TITLE
Firefox: Marking not working correctly

### ISSUE THREAD

**Issue by matobiely** [ianstormtaylor/slate#4793] opened 2022-01-19 13:31 UTC
**Description**
On Firefox, mark text `italic`, `underline` or `strikethrough` is not working correctly. Once you mark selection with format, after reselect the formated selection, Editor does not recognize it as marked/formated text. 
Only working format is `bold`.

**Recording**
![slate issue](https://user-images.githubusercontent.com/64771567/150139019-493de808-2d5e-43ae-93d8-96357cecea6c.gif)

**Steps**
To reproduce the behavior:
1. Go to https://www.slatejs.org/examples/richtext on Firefox
2. Type some text
3. Select text
4. Mark it as `italic` or `underline`
5. Cancel selection
6. Select marked text again
7. Editor does not know that text is marked

**Expectation**
Working as it should

**Environment**
- Slate Version: [e.g. 0.72.3]
- Operating System: [macOS]
- Browser: [Firefox]

**Comment by matobiely** [comment] 2022-01-19 17:19
@dylans you are right. It works only on first word and also if i select word by draging cursor, then it works. But i think this is a issue because it is not very user friendly. If you want mark multiple words or whole sentence, then dragging is okay, but for one word, i think more preferred way to select is just double click. What do you think?

**Comment by dylans** [comment] 2022-01-19 18:05
@matobiely I didn't close/reject your report because it is an issue. 😂 ... just added notes to help clarify/track it down. Edges/boundaries are one of the things that is challenging to get right across platforms. For example, see the discussion in #4522 or #4588.

**Comment by bryanph** [comment] 2022-01-26 11:33
We don't seem to have a concept for unhanging selections w.r.t inlines/texts it seems. Introducing this as was suggested [here](https://github.com/ianstormtaylor/slate/pull/4703/files#r759525155) would solve this I think

**Comment by bryanph** [comment] 2022-01-26 11:59
Also looks like https://github.com/ianstormtaylor/slate/issues/3336 tracks the same issue

**Comment by dylans** [comment] 2022-03-20 11:42
Duplicate of #3336.

**Closed by dylans** 2022-03-20 11:42 UTC
Labels: bug, ⚑ cross platform
