### ISSUE TITLE
Incorrect selection auto update after inserting manual decorator

### ISSUE THREAD

**Issue by andrew-aladev** [ianstormtaylor/slate#3699] opened 2020-05-26 19:56 UTC
Hello. I am receiving famous error `Cannot resolve a DOM point from Slate point` after inserting manual decorator. This code was recently updated by the following pull request #3594. But this code is still broken.

1. Please apply the following [patch](https://github.com/ianstormtaylor/slate/files/4684538/mentions2.zip) for `mentions` example. This code will try to replace last child with `@Amee`.
2. Open `mentions` example.
3. Set cursor to the last possible position.
4. Press `insert` key.
5. You will receive `Cannot resolve a DOM point from Slate point`.

In this example cursor appears **after** last child and `toDOMPoint` can't find point. This is fine and should be handled properly: selection end should be limited to the last available point from `DOM`.

**Comment by andrew-aladev** [comment] 2020-05-26 20:01
We need to replace this code:

```js
const newDomRange = selection && ReactEditor.toDOMRange(editor, selection)
```

with another code that intersects maximum possible `editor` range with `selection`. I am new to slate codebase, so maybe you can fix this faster than me.

**Comment by CameronAckermanSEL** [comment] 2020-06-01 15:43
Thanks for the report and the accompanying PR :)

I'm interested in merging this, but would you mind preparing a minimum reproduction in a code sandbox? A bit nervous about downloading random .zip files. 

Thanks so much!

**Comment by andrew-aladev** [comment] 2020-06-01 17:17
You can use the following patch without archive:

```
diff --git a/site/examples/mentions.js b/site/examples/mentions.js
index 2289d151..cafd3e28 100644
--- a/site/examples/mentions.js
+++ b/site/examples/mentions.js
@@ -9,6 +9,7 @@ import {
   useSelected,
   useFocused,
 } from 'slate-react'
+import { sample as _sample } from 'lodash'
 
 import { Portal } from '../components'
 
@@ -55,6 +56,28 @@ const MentionExample = () => {
             break
         }
       }
+
+      if (event.key === 'Insert') {
+        event.preventDefault()
+        const newValue = [...value]
+        const lastItem = { ...newValue.pop() }
+        lastItem.children = [...lastItem.children]
+        lastItem.children.pop()
+        setValue([
+          ...newValue,
+          {
+            ...lastItem,
+            children: [
+              ...lastItem.children,
+              {
+                type: 'mention',
+                character: _sample(CHARACTERS),
+                children: [{ text: '' }],
+              },
+            ],
+          },
+        ])
+      }
     },
     [index, search, target]
   )
```

**Comment by andrew-aladev** [comment] 2020-06-01 17:23
Please use the following [link to sandbox](https://codesandbox.io/s/slate-mentions-bug-25iwg).

**Comment by CameronAckermanSEL** [comment] 2020-06-01 17:30
Thanks very much!

Looking at this patch, it's updating the editor state in a way that isn't recommended and may be contributing to this issue. Slate uses a library called `immer` for immutability and assumes that as a result it can leverage referential equality to validate whether nodes in the value have changed. This is done for performance reasons; it can know more precisely whether a node needs to be validated or rerendered.

Instead, slate has a number of commands that can be used to mutate the value in a more controlled way. 

If we use the guts of the `insertMention` function instead of the patch, then it seems to work:
https://codesandbox.io/s/slate-mentions-bug-gfqv9?file=/src/App.js

That said, I'm still interested in your PR in case it fixes another issue. Do you have a different way of reproducing that problem?

Thanks!

**Comment by andrew-aladev** [comment] 2020-06-01 17:46
This patch is just the way to reproduce the issue. I won't insist on including this code into actual example.

> Instead, slate has a number of commands that can be used to mutate the value in a more controlled way

This is the imperative way of mutating document based on previous document and changed part of value. React users wants component to understand new mutated document in **declarative** way. Please don't try to fix example by replacing declarative with imperative =)

**Comment by CameronAckermanSEL** [comment] 2020-06-01 17:55
> This patch is just the way to reproduce the issue. I won't insist on including this code into actual example.

Sounds good! Though, I'm unsure how to reproduce this issue otherwise.

>  React users wants component to understand new mutated document in declarative way.

I think this statement is broad and as a React user, I don't agree with this. Most users of the library don't seem to have this problem either.

> Please don't try to fix example by replacing declarative with imperative =)

The mutations of the document state have enough side effects (normalization, rerendering) that it is not feasible to arbitrarily accept a fresh value from a user and inject it in directly. If you set it up this way, you are going to run into bugs and performance problems.

For this code sandbox, the change wasn't for the sake of changing the coding style, it appears this crashing bug has been alleviated as a result of using the commands API to mutate the value.

**Comment by andrew-aladev** [comment] 2020-06-01 18:04
> I think this statement is broad and as a React user, I don't agree with this. Most users of the library don't seem to have this problem either.

This is the react design as it is, I am not related for creation of this design. Please read more about `getDerivedStateFromProps` usage. All props provided to react component should work in declarative way.

> The mutations of the document state have enough side effects (normalization, rerendering) that it is not feasible to arbitrarily accept a fresh value from a user and inject it in directly. If you set it up this way, you are going to run into bugs and performance problems.

If you don't want to implement support for this functionality - please remove `value` from `props` and use `value` in component `state` instead. This change will force users use imperative design only.

**Comment by CameronAckermanSEL** [comment] 2020-06-01 18:17
If you'd like to debate reworking the entire API for this style, please feel free to open another issue. But it is sounding out of scope for this problem. Your request would require a massive rewrite of the library for what I can only perceive to be very little gain, and I suspect most users would not consider it to be an improvement.

Food for thought, almost every other (if not all) editor framework in existence has a document mutation API because of the complexity of the problem space:

Prose mirror https://prosemirror.net/docs/guide/#transform
Draft JS https://draftjs.org/docs/api-reference-modifier
Quill  https://quilljs.com/docs/api/
TinyMCE https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/

I am still interested in determining if there's a bug here to fix though!

**Comment by andrew-aladev** [comment] 2020-06-01 18:57
> If you'd like to debate reworking the entire API for this style, please feel free to open another issue. But it is sounding out of scope for this problem. Your request would require a massive rewrite of the library for what I can only perceive to be very little gain, and I suspect most users would not consider it to be an improvement.

> Slate was at one time an uncontrolled component, and users didn't like this interface

Current controlled API is fine. The problem is that controlled API is not working, please review provided example how to reproduce bug. The fix is easy and I can't understand the reason why you are trying to push fix away. If project has ability to control `value` than it should derive new internal editor state according to new `value` (declarative way).

> Food for thought, almost every other (if not all) editor framework in existence has a document mutation API because of the complexity of the problem space

DOM is a basic example of imperative native API. React library converts declarative changes into imperative calls. Same layer can be implemented for text editor. This task is hard and we don't need to discuss it.

User wants to control `value` from outside. He knows that there is no special layer between declarative and imperative part of editor, controlling `value` from outside will provide performance penalty. But he still wants to use it. Please fix bug that stops him from that usage.

**Comment by CameronAckermanSEL** [comment] 2020-06-01 18:59
> The fix is easy and I can't understand the reason why you are trying to push fix away.
Sorry, I think I've been a little bit too indirect about what my concern is. 

You have not proved to me that there is a bug and this is not user error.

**Comment by andrew-aladev** [comment] 2020-06-01 19:15
> You have not proved to me that there is a bug and this is not user error, and in the absence of a defect, I am highly reluctant to introduce changes in a sensitive area. Other than this case where the user is trying to (probably incorrectly) mutate the value directly in a way that is not recommended and supported, you have not provided a reliable way to reproduce the problem. I was able to fix it by using the command instead.

Controlling `value` from outside means `mutate the value directly` without any restrictions and recommendations. Component should be able to get derived state from `value` prop and update existing state.

I don't know what else we need to proof here, please provide more information.

**Comment by CameronAckermanSEL** [comment] 2020-06-01 19:33
> Controlling value from outside means mutate the value directly without any restrictions and recommendations.

I disagree with your assertion that this is a bug. Immer is used to provide immutability over the Immutable JS because it's lightweight and more efficient. The unintended consequence is that many users have tried to shallow clone the value and mutate it directly instead of going through the commands, and this is an unintended use case. It is not expected, or recommended that users do this, and it will cause problems for them in their own applications if they do.

If you want this way of mutating the editor state to be first class, again, I need you to make a separate issue and propose it.

This issue is open because you said there is a crashing bug with selection, and you submitted a PR. I am interested in making sure there is no such outstanding bug with selection. I'm asking you to provide a reproduction of this issue that does not involve mutating the value directly.

**Comment by andrew-aladev** [comment] 2020-06-01 21:43
> I disagree with your assertion that this is a bug. Immer is used to provide immutability over the Immutable JS because it's lightweight and more efficient. The unintended consequence is that many users have tried to shallow clone the value and mutate it directly instead of going through the commands, and this is an unsupported use case. It is not expected, or recommended that users do this, and it will cause problems for them in their own applications if they do.

I've [updated example](https://codesandbox.io/s/slate-mentions-bug-25iwg) with `immer`.

```js
setValue(
  produce(value, draft => {
    const lastItem = draft[draft.length - 1];
    if (
      lastItem != null &&
      lastItem.children != null &&
      lastItem.children.length !== 0
    ) {
      lastItem.children[lastItem.children.length - 1] = {
        type: "mention",
        character: _sample(CHARACTERS),
        children: [{ text: "" }]
      };
    }
  })
);
```

Nothing changed - it crashes anyway.

> If you want this way of mutating the editor state to be first class, again, I need you to make a separate issue and propose it.

We can see that any `value` mutation increases value length conflicts with selection and throws error.

**Comment by CameronAckermanSEL** [comment] 2020-06-01 21:50
I'm not sure what I'm missing from my explanation. You doing this mutation manually is skipping a bunch of state management with validation, selection management, and rendering that slate does under the hood to keep the model consistent. Because you aren't doing all of these things yourself and are bypassing the commands completely, the editor is not being updated correctly.

I'm closing this issue. Use the commands.

**Closed by CameronAckermanSEL** 2020-06-01 21:50 UTC
Labels: ⚑ needs info, ⚑ needs research

**Comment by andrew-aladev** [comment] 2020-06-01 22:03
> I'm not sure what I'm missing from my explanation. You doing this mutation manually is skipping a bunch of state management with validation, selection management, and rendering that slate does under the hood to keep the model consistent. Because you aren't doing all of these things yourself and are bypassing the commands completely, the editor is not being updated correctly.

I am sure that you have understand everything correctly, but don't want to change this code, because it can break something else and you don't know when and where.

I will try to cast here @ianstormtaylor and ask him about that question. He is an author of original slate controlled API, maybe he will find time to help with fixing it.

I won't create additional issues.

**Comment by TheSpyder** [comment] 2021-08-09 03:27
> If project has ability to control `value` than it should derive new internal editor state according to new `value` (declarative way).

Not true. If you want new internal state, create a new editor. Prior to v0.5 the value contained state - now it explicitly does not, state is managed separately. That state is designed to be updated through API methods to update the content model not direct mutation.
