### ISSUE TITLE
Invalid marks in schema are not removed

### ISSUE THREAD

**Issue by PierBover** [ianstormtaylor/slate#1792] opened 2018-04-24 05:00 UTC
#### Bug report

With this schema it shouldn't be possible to have any marks in the `heading-one` block:
```
const schema = {
  blocks: {
    'heading-one': {
      nodes: [{ objects: ['text'] }],
      marks: []
    }
  }
};
```
But as you can see I'm able to insert bold text in it:
![image](https://user-images.githubusercontent.com/226483/39166782-2aca079a-4751-11e8-98d5-b989999c9889.png)

#### What's the current behavior?
You can see this behaviour in action here:
https://youtu.be/mfI3U3KX9ug

To reproduce I'm just toggling a mark without actually making a selection and then simply writing.

**Comment by CameronAckermanSEL** [comment] 2018-04-24 05:12
Try `marks: ['']`

**Comment by CameronAckermanSEL** [comment] 2018-04-24 05:13
Also there's a [slack channel](https://slate-js.slack.com/messages/C1RH7AXSS/), which is a better place to ask support questions like this:

**Comment by PierBover** [comment] 2018-04-24 05:42
Thanks @CameronAckermanSEL but I'm getting the same result with either `[]` or `['']`.

**Comment by CameronAckermanSEL** [comment] 2018-04-24 05:44
The `['']` should definitely work so there's something else in play. 

Should probably go to the slack channel for some support.

**Comment by CameronAckermanSEL** [comment] 2018-04-24 05:58
Sorry, misunderstood. Able to reproduce this bug, specifically when inserting text. Appears to be because the insertion of text doesn't cause normalization so it doesn't pick up schema violations like this anymore.

**Comment by PierBover** [comment] 2018-04-25 22:36
Is this a good first task? I'd like to contribute to Slate.

**Comment by zhujinxuan** [comment] 2018-05-02 16:01
@PierBover Yes, you can fix it here: packages/slate/src/changes/by-key in insertTextAtRange
```
  if (normalize !== undefined) {
    normalize = range.isExpanded
  }
```
to something like
```
  if (normalize !== undefined) {
    normalize = range.isExpanded && marks.size !== 0
  }
```

**Comment by PierBover** [comment] 2018-05-02 16:07
Ok I'll take a look tonight.

**Comment by SmilinBrian** [comment] 2018-06-03 19:39
A discussion with "bupkis" on Slack on May 29th shows that this issue also applies to cases where the editor is intended to automatically convert certain sequences of characters typed into macros or something.

I made a JSFiddle showing this issue so that this other aspect of this problem can be fixed/tested as well:  https://jsfiddle.net/SmilinBrian/d5qrhtgx/2/

**Comment by zhujinxuan** [comment] 2018-06-03 21:54
@SmilinBrian Can you move the discussion to https://github.com/ianstormtaylor/slate/pull/1823

**Comment by isubasti** [comment] 2018-06-04 00:47
@SmilinBrian you might want to use something like https://github.com/ianstormtaylor/slate-plugins/tree/master/packages/slate-auto-replace rather than validateNode for that

**Comment by samuelwagen** [comment] 2018-06-05 06:53
@isubasti slate-auto-replace is only suitable for when the user actually types. It doesn't work for example if you also need to process the initial state.

**Comment by isubasti** [comment] 2018-06-05 13:47
@samuelwagen yeah the `schema normalization` is still needed for some circumstances but for the use cases that @SmilinBrian pointed out, which is for macros then it will work. I believe it should work as it is anyway for the schema normalization on initial state

**Comment by CameronAckermanSEL** [comment] 2018-06-05 15:41
@samuelwagen this issue is in regards to `insertTextAtRange` not normalizing, so I think `slate-auto-replace` would still be a more appropriate approach to achieving the use case that @SmilinBrian described, as both `insertTextAtRange` and `slate-auto-replace` are tied closely to `onKeyDown` events. 

Cases where you would want schema normalization to be applied to the text on load are out of scope for this issue and for `slate-auto-replace`

**Comment by SmilinBrian** [comment] 2018-06-05 17:37
I agree that normalization on load is out of scope for this issue.

I still feel ambivalent about whether or not `validateNode()` should be called for all text insertion regardless of whether prior selection is collapsed. Seems to me it should be called, assuming validation is properly limited to "only the affected node(s)." If limited, any performance issues are due to the validations being too complex.  That is, I'm assuming the built-in validations are fairly performant, and it would only be custom validations that might cause performance problems.

**Comment by CameronAckermanSEL** [comment] 2018-06-05 20:35
There are a couple of open PRs related to `insertTextAtRange` that address this. 

The first of these triggers normalization when there's a mark, which I think is one case where normalization needs to be evaluated on insertion of text.

https://github.com/ianstormtaylor/slate/pull/1875
https://github.com/ianstormtaylor/slate/pull/1823

**Closed** 2018-06-10 23:31 UTC
Labels: bug, ♥ help please
