### ISSUE TITLE
Anchor tag (link) not working inside a isVoid node

### ISSUE THREAD

**Issue by bkniffler** [ianstormtaylor/slate#542] opened 2016-12-29 08:14 UTC
Hi,
Anchor tags / links are not working inside a isVoid=true node.

https://jsfiddle.net/2zokvrvt/32/

Is there something interrupting the mouse events?

**Comment by ianstormtaylor** [comment] 2016-12-30 20:41
Hey @bkniffler, good find. I think this might be a duplicate of #508, so I'm going to close in favor of that issue. But if you figure out a good solution to it that maintains the existing behavior I'm happy to accept a pull request to fix links!

**Closed by ianstormtaylor** 2016-12-30 20:41 UTC
