### ISSUE TITLE
Placing accents over characters does not work

### ISSUE THREAD

**Issue by TheLastBug** [ianstormtaylor/slate#2781] opened 2019-05-15 14:49 UTC
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
When typing '´' + 'a' to get 'á', the accent is ignored and only 'a' is written (same result is seen when attempting to write a á à ã ă â e é è ê i í ì ĩ o ó ò õ ô ơ u ú ù ũ ư y ý ỳ).
http://recordit.co/WrUR6GiCt4

**Note**: When typing from the middle or the text, both the accent and the letter are ignored, and neither are written.

#### What's the expected behavior?
http://recordit.co/yqayENkyIu

**Note**: Pasting these composite characters directly works.

You may reproduce it here: https://www.slatejs.org/#/rich-text
Browser: Safari 12.0.1
OS: macOS Mojave 10.14.1

**Comment by alanhogan** [comment] 2019-05-28 23:00
I can reproduce this, also on Safari + Mojave

**Comment by alanhogan** [comment] 2019-05-28 23:01
(It's fine in Chrome + Mojave)

**Comment by philn** [comment] 2019-08-04 18:22
on macOS to get 'à' I long-press on 'a' and a popup shows up offering me the variants for that character. So IMHO this issue in invalid on macOS, although it can be valid on other platforms like Linux.

**Comment by rikkit** [comment] 2019-08-05 09:52
<kbd>\`</kbd> + <kbd>a</kbd> = `à` works for me as expected on Firefox on Windows with United Kingdom Extended keyboard

**Comment by ksimons** [comment] 2019-08-05 10:39
If I type <kbd>´</kbd> with a Norwegian keyboard, the cursor moves backwards to the left of the accent, whereas on all other editors, it correctly stays to the right.

**Comment by knubie** [comment] 2019-09-24 00:22
@philn There are two ways to input accented characters on macOS. The way that you described, which is the default behavior (**method A**), and the way that @TheLastBug describes (**method B**). The behaviour can be toggled with a defaults write command.

That said, there exists bugs in each method.

#### In Safari
- method A works as expected
- method B - The accent is ignored and the standard character is written

#### In Chrome
- method A - Both the standard character and the accent character are inserted
- method B  works as expected

I have no tested Firefox yet

**Comment by ianstormtaylor** [comment] 2019-11-28 03:29
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Closed by ianstormtaylor** 2019-11-28 03:29 UTC
