### ISSUE TITLE
Weird jumping with long texts

### ISSUE THREAD

**Issue by svenadlung** [ianstormtaylor/slate#3677] opened 2020-05-12 14:20 UTC
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

With long texts scroll position randomly jumps while typing. Please see sandbox example: https://jsfiddle.net/h94wn1Lf/

![May-12-2020 16-15-27](https://user-images.githubusercontent.com/11420688/81702699-e9043500-946b-11ea-9d68-2559023bb477.gif)

1. Place cursor in the beginning of the text and start typing

Maybe this is related to https://github.com/ianstormtaylor/slate/issues/3463?

Slate: 0.57.1
Browser: Chrome / Firefox
OS: Mac

#### What's the expected behavior?

The view should not leave the cursor while writing.

**Comment by CameronAckermanSEL** [comment] 2020-05-12 15:41
Hey @svenadlung  thanks for filing this. I think you're right that it's a potential duplicate of #3463, but I'm not 100% sure, so for the time being I'll leave it open. Would you be able to try a small change 
https://github.com/ianstormtaylor/slate/commit/1652ecab52088e64ffbaa130fa4049f60cdce57e
and see if this fixes the issue for you? That'll help us be sure.

Thanks!

**Comment by svenadlung** [comment] 2020-05-14 11:43
Hi @CameronAckermanSEL thanks for your quick reply. 

I patched our code and jumping around stopped. Within scrollable container it seems to work well. Unfortunately it doesn't scroll anymore at all without a scrollable parent. But this could be related to our source as well. Maybe you can keep an eye on that while reviewing https://github.com/ianstormtaylor/slate/commit/1652ecab52088e64ffbaa130fa4049f60cdce57e

Another issue besides wrong calculations in scrollable containers that we encountered concerns long texts. 
`scroll-into-view` by default uses `block: "center"` which causes scrolling to the vertical center of texts which might lead to a mispositioning in that case.

Still I am not sure how everything works with overlaying element like a fixed header. There is no easy way to change current calculation and add an offset f. ex.

Let me know if there is anything else I can do.

Best whishes.

**Comment by CameronAckermanSEL** [comment] 2020-05-14 16:31
Thanks for taking the time to try this and for the feedback. That's really helpful. I'll be sure to look in that area when reviewing the PR

**Comment by CameronAckermanSEL** [comment] 2020-05-21 00:34
I merged a PR that appears to fix this problem. When I tried to reproduce the issue you mentioned, I didn't have much luck running into it. If you still have that problem and have a reproduction of it handy, please let me know and we can make sure it gets addressed.

Thanks!

**Closed by CameronAckermanSEL** 2020-05-21 00:34 UTC
Labels: bug, ♥ help

**Comment by svenadlung** [comment] 2020-06-01 12:57
@CameronAckermanSEL Many thanks for your efforts! I have updated the fiddle with slate `0.58.1` and slate-react `0.58.2` and can reproduce my misbehavior:

https://jsfiddle.net/cq57zf2a/7/

Place the cursor in the last line of the visible text and start writing. There is no scrolling for me anymore.

Can you recheck?

**Comment by skogsmaskin** [comment] 2020-06-03 12:48
I'm experiencing the same as @svenadlung, the editor no longer scolls as new text is added to the bottom.

**Comment by svenadlung** [comment] 2020-06-15 19:55
@CameronAckermanSEL could you reopen this ticket or should we create a new one based on this?

**Comment by CameronAckermanSEL** [comment] 2020-06-15 20:17
Hey thanks, a different ticket is probably in order because the behavior characteristic is different
