### ISSUE TITLE
Incorrect Cursor Position on Enter

### ISSUE THREAD

**Issue by irmerk** [ianstormtaylor/slate#3642] opened 2020-04-27 23:18 UTC
#### Do you want to request a _feature_ or report a _bug_?

Bug 🐛

#### What's the current behavior?

Cursor doesn't move to following line when pressing <kbd>ENTER</kbd> at end of formatted text (**bold**, _italic_, etc.) 

##### GIF of issue in action
![Apr-27-2020 19-14-10](https://user-images.githubusercontent.com/36460856/80429982-57b59000-88bb-11ea-88b3-83b602ddac2a.gif)

##### Sandbox of issue reproduction
Slate's [Rich Text example](https://www.slatejs.org/examples/richtext)

##### Information about your OS, browser, Slate version, etc.
Slate: **0.57.1**
Browser: **Chrome**
OS: **Mac**

#### What's the expected behavior?

Cursor should move to following line when pressing <kbd>ENTER</kbd>

**Comment by CameronAckermanSEL** [comment] 2020-04-28 15:37
Thanks! Going to close this as a duplicate of this: https://github.com/ianstormtaylor/slate/issues/3600

**Closed by CameronAckermanSEL** 2020-04-28 15:37 UTC
