### ISSUE TITLE
Serious performance problems with large block node + marks inside

### ISSUE THREAD

**Issue by sashless** [ianstormtaylor/slate#606] opened 2017-02-15 15:20 UTC
When you change the `largeDocument" example like this to get a single block node containing a lot of text

```
const nodes = []
let text = ''
for(let i = 0; i < 5; i++){ // you can start at 5 and then increment. you will see problems very soon
  text += faker.lorem.paragraph()
}

nodes.push({
  kind: 'block',
  type: 'paragraph',
  nodes: [ { kind: 'text', text: text} ]
})
```

Then try to enter text you will recognize it is really slow. Now try to select a great portion of the text and apply a `bold` mark. 
Now try to edit the text again. 
It becomes unusable :(

**Comment by ianstormtaylor** [comment] 2017-03-22 07:23
Hey @sashless thanks for reporting. Can you create a place to reproduce this in JSFiddle? There have been some performance improvements since you've posted, although I believe you that it's probably still slow! Thanks

**Comment by ianstormtaylor** [comment] 2017-04-01 02:43
Hey @sashless thanks for this! I've just opened a handful of other performance tickets after profiling to see where things are slow, so I'm going to close this one in favor of those!

**Closed by ianstormtaylor** 2017-04-01 02:43 UTC
Labels: needs-info, ⚑ performance
