### ISSUE TITLE
Disabling mark with no selection doesn't cause it to stop being active

### ISSUE THREAD

**Issue by glebtv** [ianstormtaylor/slate#2736] opened 2019-05-05 11:08 UTC
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
https://www.slatejs.org/#/rich-text
Enable "bold"
Type some text
Disable bold (don't select anything), button in toolbar shows as not active
Type some text, button in toolbar becomes active again
Second part of the text (after disabling bold) is bold, and bold button is re-highlighted in toolbar

#### What's the expected behavior?
Second part of the text (after disabling bold) is *not* bold

Possibly, ```removeMark``` should now do a ```split_node``` if the mark was active and the selection is collapsed?

Note: [gitbook slate rich text demo](https://gitbookio.github.io/slate/#/rich-text) doesn't have this problem

**Comment by rebirthtobi** [comment] 2019-05-05 13:52
I have the same problem, its like slate is broken at some point

**Comment by rebirthtobi** [comment] 2019-05-05 20:48
@glebtv Gitbook might be using a different version

**Comment by isubasti** [comment] 2019-05-06 02:55
this bug is actually different then what #1113 try to fix. it's a bug introduced due to seemingly incomplete implementation of removing leaves https://github.com/ianstormtaylor/slate/commit/a220cd5ae10c7e5f7df6d018deae0670526dbb73. @ianstormtaylor it looks like on `remove/adding` mark, `Text` node is not created/removed properly

**Comment by mwegman** [comment] 2019-05-06 19:30
I ended up downgrading to 0.45 to avoid this bug so it was definitely something introduced in 0.46.

**Comment by rebirthtobi** [comment] 2019-05-06 20:19
do you also downgrade slate react also?

**Comment by mwegman** [comment] 2019-05-06 20:22
> do you also downgrade slate-react also?
> 
> > I ended up downgrading to 0.45 to avoid this bug so it was definitely something introduced in 0.46.

I didn't. It seems to work fine without downgrading slate-react

**Comment by rebirthtobi** [comment] 2019-05-07 01:59
I'm still experiencing the same issue probably because my editor lose focus as i click on the button

> > do you also downgrade slate-react also?
> > > I ended up downgrading to 0.45 to avoid this bug so it was definitely something introduced in 0.46.
> 
> I didn't. It seems to work fine without downgrading slate-react

**Comment by rebirthtobi** [comment] 2019-05-07 04:53
I've resolve this using `onMouseDown` instead of `onClick`, but thwn i have a colour picker, font and font size picker also. I'm still trying to make this work

**Comment by brynshanahan** [comment] 2019-05-07 23:37
In the same vein of this issue. If you are in a plain text node and then activate a mark like bold, the first character you type will be bold then the following characters will revert back to the original style. This only happens if you try to enter a mark in the middle of a text node
![2019-05-08 09-06-57](https://user-images.githubusercontent.com/37826020/57339389-bd71af00-7174-11e9-8820-e0a5519f148a.gif)

**Comment by akovantsev** [comment] 2019-05-14 10:17
@brynshanahan I think this is the cause:
https://github.com/ianstormtaylor/slate/pull/2715/commits/b3175ba565e8c307d35854bff80913e00ee78799#diff-dc737afa91245a08a36c966a9da47690R417
cc @ianstormtaylor

**Comment by adjourn** [comment] 2019-05-22 14:26
@ianstormtaylor I managed to fix this issue (hurray!) but few tests are failing. Would love to get your (and others) thoughts on this. Just pushed a PR for you to see and test #2818.

All failing tests are similar to this example. The core of this fail is that it doesn't provide any marks but target node has marks. "Wanted" marks and node marks are not equal, node is split and desired marks are applied to new one (or not if don't want any). Is this a desired side-effect or not?

```jsx
export default function(editor) {
  // No 4th argument (marks) 
  editor.insertTextByKey('a', 4, 'x')
}

export const input = (
  <value>
    <document>
      <paragraph>
        <text key="a" marks={[{ type: 'bold' }]}>
          w<cursor />ord
        </text>
      </paragraph>
    </document>
  </value>
)

export const output = (
  <value>
    <document>
      <paragraph>
        <b>
          w<cursor />ordx
        </b>
      </paragraph>
    </document>
  </value>
)

// With my PR
const output = (
  <value>
    <document>
      <paragraph>
        <b>
          w<cursor />ord
        </b>
        x
      </paragraph>
    </document>
  </value>
)
```

**Comment by CameronAckermanSEL** [comment] 2019-08-30 01:09
I believe a fix for this was merged in and published

**Comment by crow1796** [comment] 2019-10-16 07:13
Is there any way to make the marks work like this?

**Comment by ianstormtaylor** [comment] 2019-11-29 13:23
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Closed by ianstormtaylor** 2019-11-29 13:23 UTC
Labels: bug, ♥ help
