### ISSUE TITLE
Highlighting and deleting an ordered list fragment results in an orphaned list item

### ISSUE THREAD

**Issue by arahansen** [ianstormtaylor/slate#3434] opened 2020-01-17 08:43 UTC
#### What's the current behavior?

Whenever highlighting multiple lines containing list-items, and then deleting those, the fragment is deleted (`editor.deleteFragment` is triggered). However, there is a single remaining empty list-item with no parent ul or ol element.

[codesandbox repro](https://codesandbox.io/s/slate-reproductions-bd2rt)

GIF Repro:
![Kapture 2020-01-17 at 0 38 53](https://user-images.githubusercontent.com/8746094/72597215-2263d400-38c2-11ea-9154-607090074176.gif)

Notice how after deleting, the remaining bullet is no longer indented indicating there is no wrapper list element.

![image](https://user-images.githubusercontent.com/8746094/72597288-4f17eb80-38c2-11ea-9ea5-e16a8950d450.png)

Slate: 0.57.1
Browser: Chrome
OS: Mac

#### What's the expected behavior?
Expectation is the entire list would be deleted including all list-items, wrapper ul/ol element, and no orphaned list-item remains.

**Comment by ryanmitts** [comment] 2020-01-20 00:34
Digging through the merge code, it looks like this is what it wants to happen, and makes sense for other types of nested elements.

Is this a case that is supposed to be handled by normalization perhaps?

**Comment by LiuJi-Jim** [comment] 2020-01-20 09:44
I currently wrote some `normalizeNode` rules to avoid this. e.g. turning it into `<p>`😢

**Comment by CameronAckermanSEL** [comment] 2020-02-26 06:11
It's intended that you write a normalize function to clean up empty `<li>` elements. Slate is, by design, unopinionated about the elements that are supported in your editor and their relationship to other elements. 

Ideally, this would be handled by a list plugin. I'm unfortunately a little bit out of the loop on the plugin ecosystem at this time so I can't recommend one. 

Going to close this for now. Thanks for the question.

**Closed by CameronAckermanSEL** 2020-02-26 06:11 UTC
