### ISSUE TITLE
bug with selection around inline void node edges

### ISSUE THREAD

**Issue by AlexeiAndreev** [ianstormtaylor/slate#710] opened 2017-04-03 17:45 UTC
Here is the JSFiddle: https://jsfiddle.net/f2t6vd6z/

Basically I'm inserting an inline node (IfStatement) that has a few Void nodes inside it. After insertion, if you just click Left to go character by character, you'll see errors. It's not clear if I'm doing something incorrectly or if this is a bug.

**Comment by Rebulus** [comment] 2017-04-04 12:33
@AlexeiAndreev Hi. Could you check your example with the last version of Slate. You can just open your link and try to reproduce errors.
I can't reproduce it, maybe, I do something wrong.
Please, looks at screencast:
![screencast 2017-04-04 15-21-42](https://cloud.githubusercontent.com/assets/587265/24656668/061ce9aa-194c-11e7-898b-91df081c94ac.gif)

**Comment by AlexeiAndreev** [comment] 2017-04-04 15:06
Oh apparently I didn't click the "Update button" when I forked. This should be updated: https://jsfiddle.net/f2t6vd6z/1/

**Comment by Rebulus** [comment] 2017-04-04 16:06
@AlexeiAndreev Thank you. Currently, I see 😊 
```bash
Uncaught DOMException: Failed to execute 'setStart' on 'Range': The offset -1 is larger than or equal to the node's length (1).
    at Content.updateSelection (https://npmcdn.com/slate@0.19.16/dist/slate.js:32587:11)
    at Content.componentDidUpdate (https://npmcdn.com/slate@0.19.16/dist/slate.js:32507:12)
    at measureLifeCyclePerf (https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js:4529:12)
    at https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js:5183:11
    at CallbackQueue.notifyAll (https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js:948:22)
    at ReactReconcileTransaction.close (https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js:11398:26)
    at ReactReconcileTransaction.closeAll (https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js:14790:25)
    at ReactReconcileTransaction.perform (https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js:14737:16)
    at ReactUpdatesFlushTransaction.perform (https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js:14724:20)
    at ReactUpdatesFlushTransaction.perform (https://npmcdn.com/react-dom@15.4.2/dist/react-dom.js:12844:32)
```

**Comment by AlexeiAndreev** [comment] 2017-04-04 16:09
Yes. And note how strangely the cursor moves. Sometimes it skips characters.

**Comment by echenley** [comment] 2017-08-02 19:30
Wanted to cross reference a [similar issue with the Medium editor](https://github.com/jakiestfu/Medium.js/issues/82). This is probably a separate issue, but apparently similar errors can be caused by certain browser extensions that automatically alter your input. I was able to reproduce this error using [this plugin](https://chrome.google.com/webstore/detail/text-url-linker/aegfbpchoheaflicfmggkmlmcccpjpgd).

**Comment by crazylive** [comment] 2018-11-15 08:19
i think you used table in html.
i get this bug as: https://gist.github.com/crazylive/911953db4ca90db3c47b3dfb6133e515

and i don't know as it works but simple solution is wrap ckeditor to table, sample:
https://gist.github.com/crazylive/040aa95f4d980230cd776a60ff00603a

**Comment by ianstormtaylor** [comment] 2019-05-09 02:55
This issue hasn't had a response in a while, and it's unclear if it's still present in the latest versions of Slate. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice that the bug is still happening, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!

**Closed by ianstormtaylor** 2019-05-09 02:55 UTC
Labels: bug, ♥ help please
