### ISSUE TITLE
When selecting the whole line the editor throws on any input key press.

### ISSUE THREAD

**Issue by czechdave** [ianstormtaylor/slate#1391] opened 2017-11-08 23:45 UTC
#### Do you want to request a *feature* or report a *bug*?
BUG

#### What's the current behavior?
Go to http://slatejs.org/#/rich-text
Triple click on the first line to select the whole line.
Press any letter key.
Nothing happens.
The console throws an error: `Uncaught Error: Could not find a node with key "3".`

https://monosnap.com/file/grOvTJAnUNOEFatgoobbVd6NBGMxhB

#### What's the expected behavior?
The selected text to be replaced by the letter that got pressed.

**Comment by kashifimran** [comment] 2017-11-09 06:10
This is a duplicate of https://github.com/ianstormtaylor/slate/issues/1189

**Closed** 2017-11-09 17:49 UTC
