### ISSUE TITLE
When Selection passes over an image block in firefox, 

### ISSUE THREAD

**Issue by CameronAckermanSEL** [ianstormtaylor/slate#1712] opened 2018-03-19 22:43 UTC
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

In Firefox when selection crosses an image (or more precisely probably a void block), selection is lost on nodes that were selected before the image, and selection does not continue afterwards.

This is possibly due to Firefox being unable to deal with its own `contentEditable` feature in an elegant or sensible way.

http://recordit.co/U7l8b7MyJp

#### What's the expected behavior?

Selection is not lost

**Comment by zhujinxuan** [comment] 2018-03-20 04:42
I remember there were an issue about selection crossing images?

**Comment by urugator** [comment] 2018-03-21 16:55
The problem is that firefox can't extend selection over nested `contenteditable="true"`.
Try this:
```html
<div id="editable" contenteditable="true">
  start
  <div contenteditable="false">            
    <div contenteditable="true">editable [MOUSE SELECTION WON'T EXTEND OVER THIS POINT]</div>
    unselectable      
  </div>  
  unselectable     
</div>
```
Play with it for a while, try selecting from different directions, using mouse or cursor keys ... it's super buggy.
There is such nested `contenteditable="true"` (`data-slate-spacer`) just before `<img>`.
Emojis suffer the same problem (perhaps all voids?).

I also found an edge case where FF can't extend selection backward with arrow left over image, but it doesn't relate to this issue and can be probably fixed in slate by normalizing arrow-left:
```html
<!-- regardles of contenteditable -->
<p>try to end here</p>  
<!-- img must not be wrapped in block -->       
<img src="https://github.com/ianstormtaylor/slate/raw/master/docs/images/banner.png">
<!-- this point is unreachable by selection -->            
<p>start here and use shift + arrow left</p> 
```

**Comment by ianstormtaylor** [comment] 2019-11-28 03:07
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Closed by ianstormtaylor** 2019-11-28 03:07 UTC
Labels: bug, ♥ help
