### ISSUE TITLE
If you move the cursor up into a multiline block, and the last line is empty, the cursor skips the entire block

### ISSUE THREAD

**Issue by justinweiss** [ianstormtaylor/slate#1961] opened 2018-07-09 19:39 UTC
#### Do you want to request a _feature_ or report a _bug_?

Report a bug.

#### What's the current behavior?

![screen-recording](https://user-images.githubusercontent.com/1020/42472088-fc790a3e-8374-11e8-9462-73e607aa8baf.gif)

#### What's the expected behavior?

When pressing the up arrow, the cursor should enter the last line in the multiline block.

**Comment by ianstormtaylor** [comment] 2018-08-08 00:49
Hey, thanks for reporting this. I think this is actually a duplicate of https://github.com/ianstormtaylor/slate/issues/1413, so I'm going to close this in favor of that one. Feel free to comment over there with any other info!

**Closed by ianstormtaylor** 2018-08-08 00:49 UTC
