### ISSUE TITLE
Slate Example - Markdown Shortcuts Not Working

### ISSUE THREAD

**Issue by varlevi** [ianstormtaylor/slate#3631] opened 2020-04-22 23:12 UTC
#### Do you want to request a _feature_ or report a _bug_?

Bug request

#### What's the current behavior?

When I use markdown symbols, the text formatting stays the same.

Slate: Example Site
Browser: Chrome (Vivaldi)
OS: Linux - Rasbian w/ KDE

#### What's the expected behavior?

I expect, when I use the symbols ">", "-", and "#", I expect the line to format automatically as the example text indicates.

**Comment by CameronAckermanSEL** [comment] 2020-04-23 02:11
Hi @varlevi , the markdown shortcut example is working. You need to hit the space character after typing one of the replaceable symbols.

If you feel the text could use some clarification, please feel free to submit a PR. For now though, I'll close the issue as the example is working as intended.

Thanks!

**Closed by CameronAckermanSEL** 2020-04-23 02:11 UTC
