### ISSUE TITLE
Undo will move selection to block start when cursor is at end of inline

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#1587] opened 2018-02-01 16:30 UTC
#### Do you want to request a *feature* or report a *bug*?

bug
#### What's the current behavior?

I press `cmd-z` when the cursor is moved to the end of inline;  Then the cursor does not move to the previous place, but the block start

![Undo At the inline end](http://g.recordit.co/d2NzqpsCRD.gif)

**Comment by DamareYoh** [comment] 2018-02-21 07:33
I'm very confident that root cause of this is that the `set_selection` type operations don't contain enough information to properly invert them. I think we may be able to fix this by adding a `previous` property to the `set_selection` operation which would effectively hold all of the properties of the previous selection.

It's unknown whether `previous` is the best interface for this behavior, but it would at least make sense. The downside is that this property would basically only be consumable by the undo logic and would not be useful for collaboration features (probably)

**Comment by ianstormtaylor** [comment] 2019-11-28 02:43
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Closed by ianstormtaylor** 2019-11-28 02:43 UTC
Labels: bug, ♥ help
