### ISSUE TITLE
deleteLineBackward borks the website demo

### ISSUE THREAD

**Issue by mattkrick** [ianstormtaylor/slate#1965] opened 2018-07-11 01:22 UTC
#### Do you want to request a _feature_ or report a _bug_?

BUG

#### What's the current behavior?
delete line back works, and then i hit the "a" key (or any other key that will make a character)  & it borks:
![borkdeletelineback](https://user-images.githubusercontent.com/5514175/42545623-e5db6b24-846d-11e8-8d40-9683156ac051.gif)

Chrome 67
Ubuntu 16.04
Slate Demo website https://www.slatejs.org/#/rich-text

**Comment by zhujinxuan** [comment] 2018-07-12 15:47
I think the problem is fixed by https://github.com/ianstormtaylor/slate/pull/1888

**Comment by ianstormtaylor** [comment] 2019-11-28 02:42
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Closed by ianstormtaylor** 2019-11-28 02:42 UTC
Labels: bug, ♥ help
