### ISSUE TITLE
rich-text example not works.

### ISSUE THREAD

**Issue by sherry0429** [ianstormtaylor/slate#3043] opened 2019-09-30 07:42 UTC
see :
```JavaScript
import { Editor } from 'slate-react'
import { Value } from 'slate'

import React from 'react'
import initialValue from './value.json'
import { isKeyHotkey } from 'is-hotkey'
import { Button, Icon, Toolbar } from '../components'
```

this line
```JavaScript
import { Button, Icon, Toolbar } from '../components'
```

raise error
```
Module not found: You attempted to import ../components which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
```

is there i need some extra module ? thanks

**Comment by thesunny** [comment] 2019-09-30 15:23
Hi, thanks for your question but I'm closing this for a few reasons:

1. It looks like a support request and not a bug report
2. If you meant this to be a bug report, it's not clear because there isn't enough information to make that determination. Please follow the issue template. As this issue is provided, there is not enough information to help debug (e.g. which example is this?)

For general help, there is a channel for support here https://slate-slack.herokuapp.com/ and it will probably help you solve your issue faster.

**Closed by thesunny** 2019-09-30 15:23 UTC
