### ISSUE TITLE
Error replacing multi blocks with IME composition inputs

### ISSUE THREAD

**Issue by doodlewind** [ianstormtaylor/slate#1114] opened 2017-09-12 03:27 UTC
#### Do you want to request a *feature* or report a *bug*?
Bug.

#### What's the current behavior?
When replacing multi blocks text with IME composition inputs, an `fail to removeChild` error raised, and the IME result is also lost, only remains temp keys during composition. Reproduction: 

1. Select multi blocks.
2. Use IME to input some texts.
3. Choose a word.

![compositon-bug](http://7u2gqx.com1.z0.glb.clouddn.com/composition-bug.gif)

In this case, `啊啊啊` is the expected result instead of `a'a'a`.

#### What's the expected behavior?
Text input from IME inserted correctly without error.

**Comment by doodlewind** [comment] 2017-09-12 06:26
@ianstormtaylor I dived a bit and this has something to do with native IME behavior: 

1. When user starts typing with IME, the selected DOM is removed, but editor state is untouched.
2. When user eventually choose a word, a `Change` is applied to state in `onBeforeInput`, trying to remove initially selected nodes, which no longer exists. But since state is out of sync against DOM, manipulating non-exist DOM nodes raised this error.

I suggest two approaches:

- Trying to `preventDefault` native IME behavior. Currently slate only listens to `onCompositionStart` and `onCompositionEnd`, while there is an `onCompositionUpdate` event that may help.
- Use some slate API to manipulate state without 'binding' DOM, so that we can remove state nodes without DOM ops. Is this possible or an anti-pattern?

Hope for your suggestion!

**Comment by ianstormtaylor** [comment] 2017-09-12 07:05
Hey @doodlewind thanks!

I'm not sure I understand your second approach option. What do you mean there?

Preventing default on the `onCompositionEnd` events sounds like an interesting solution to me, if it solves the problem I'm definitely game for that.

**Comment by ianstormtaylor** [comment] 2017-10-26 20:54
Hey, thanks for reporting this. I think this is actually a duplicate of #967, so I'm going to close this in favor of that one. Feel free to comment over there with any other info!

**Closed by ianstormtaylor** 2017-10-26 20:54 UTC
Labels: bug
