### ISSUE TITLE
The onChange event never occurs in 'embeds example' 

### ISSUE THREAD

**Issue by cymoo** [ianstormtaylor/slate#3615] opened 2020-04-15 17:16 UTC
#### Do you want to request a _feature_ or report a _bug_?

A bug.

#### What's the current behavior?

When running the example of embeds (https://github.com/ianstormtaylor/slate/blob/master/site/examples/embeds.js), the input seems to be frozen.

- A GIF showing the issue in action.

![slate-bugs](https://user-images.githubusercontent.com/7800791/79367086-d50a0800-7f7f-11ea-8e8c-70b3ff394638.gif)

- A sandbox that minimally reproduces the issue.

https://codesandbox.io/s/slate-reproductions-phgh6?file=/index.js

- Information about your OS, browser, Slate version, etc.

Slate: 0.57.1
Browser: Chrome / Safari / Edge
OS: Mac / Windows

#### What's the expected behavior?

Like https://www.slatejs.org/examples/embeds

**Comment by CameronAckermanSEL** [comment] 2020-04-15 18:36
Hi @cymoo , the fixes that make the embeds example have not yet been released. If you're trying them in a local reproduction of the embeds example using the latest package from NPM, then this is not going to function.

(Before you ask me when a release is, I have no idea)

I'm going to close this issue because the bug is resolved and it's dependent in progress for a release. If after the release you continue to observe this issue, feel free to post and I can reopen.

**Closed by CameronAckermanSEL** 2020-04-15 18:36 UTC
