### ISSUE TITLE
Double clicking words with marks does not select them properly more often than not

### ISSUE THREAD

**Issue by Slapbox** [ianstormtaylor/slate#2317] opened 2018-10-24 22:48 UTC
Not sure where the origin of this might be, but here's what I'm seeing - using the Rich Text example: http://recordit.co/sqMCk2ylvI

**Comment by ericedem** [comment] 2018-10-24 23:01
Hmm, this seems to work for me at https://www.slatejs.org/#/rich-text.

What browser / version are you using?

**Comment by Slapbox** [comment] 2018-10-24 23:08
That's really weird. I reproduced this 3 separate times in Chrome 70, but now I can't. Closing this unless I find a way to make this happen again.

**Comment by kode-ninja** [comment] 2019-02-18 14:11
Still happens to me on Chrome 72 (Win 10). Does not happen on IE nor Edge.

**Comment by Slapbox** [comment] 2019-02-18 17:37
@kode-ninja this is happening in the latest version of Slate at https://www.slatejs.org/?

Can you provide instructions to recreate the issue, a last known working version of Slate, and a video recording the issue? For a video you can use [RecordIt](http://recordit.co/)

The more of these you can provide the better chance there is for this issue to be reopened. FWIW I can't recreate this in Chrome 72 on Windows 7.

**Comment by kode-ninja** [comment] 2019-02-19 06:52
Yep, forgot to mention I'm using latest Slate version (44.10) and latest React and react-dom (16.8.2).
Chrome 72 (Win 10). Does not happen on IE nor Edge.

@Slapbox, here's a video of my own editor in which it happens on non-marked nodes too: http://recordit.co/qD8V6i7COh

On the [example page](https://www.slatejs.org/#/rich-text), it happens on marked nodes only: http://recordit.co/OMtXAL1pen

**Comment by Slapbox** [comment] 2019-02-19 18:48
Huh. I wonder if it's related to React versions. I haven't check what the examples are running.

**Comment by kode-ninja** [comment] 2019-02-20 18:20
So, any news?

**Comment by kode-ninja** [comment] 2019-02-21 16:27
@Slapbox will you re-open?

**Comment by Slapbox** [comment] 2019-02-21 17:59
@kode-ninja you've definitely demonstrated the issue exists. Re-opened.

You can try asking on the Slack channel to see if anyone has any insights until this issue gets some attention and investigation. Since no one else seems to be seeing it yet I wouldn't expect for this issue to gain traction quickly.

**Comment by isubasti** [comment] 2019-02-25 03:48
@kode-ninja I tried to reproduce but it doesn't seem to be reproducible. the only way I can kinda reproduce the problem is if I move my mouse slightly in between the click

**Comment by Slapbox** [comment] 2019-02-25 05:28
@kode-ninja what version of Slate-React are you using? You're testing with no plugins or extra event handlers?

**Comment by kode-ninja** [comment] 2019-02-25 06:21
@isubasti this is so strange...did you try to reproduce on Win10 with the exact same versions?

**Comment by kode-ninja** [comment] 2019-02-25 06:21
@Slapbox react-slate 0.21.16

**Comment by isubasti** [comment] 2019-02-25 08:44
@kode-ninja yes the exact same windows, chrome, & slate version

**Comment by kode-ninja** [comment] 2019-02-25 14:10
@Slapbox @isubasti's comment got me thinking and I've tried to reproduce the issue using a mouse instead of the laptop's mouse-pad and I couldn't. Can anyone else try with a mouse pad?

**Comment by ianstormtaylor** [comment] 2019-11-28 19:39
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Closed by ianstormtaylor** 2019-11-28 19:39 UTC
Labels: ⚑ needs info
