### ISSUE TITLE
By default, editor renders twice

### ISSUE THREAD

**Issue by raymestalez** [ianstormtaylor/slate#1785] opened 2018-04-17 15:20 UTC
Once the editor renders for the first time, onChange() is immediately triggered, which causes it to rerender once again.

I have added `console.log("Render!")` to the `render()` function in the default example, and it runs twice:
https://jsfiddle.net/fj9dvhom/333/

This seems like a weird behavior that shouldn't happen.

![slate-double-render](https://user-images.githubusercontent.com/4761235/38879636-ace8dfbe-4218-11e8-92fa-1867dc382909.png)

**Comment by ianstormtaylor** [comment] 2018-08-08 00:59
Hey, thanks for reporting this. I think this is actually a duplicate of #1762, so I'm going to close this in favor of that one. Feel free to comment over there with any other info!

**Closed by ianstormtaylor** 2018-08-08 00:59 UTC
