### ISSUE TITLE
Link example: button is off when it shouldn't be

### ISSUE THREAD

**Issue by AlexeiAndreev** [ianstormtaylor/slate#758] opened 2017-04-26 00:39 UTC
http://slatejs.org/#/links
If you position the cursor at the end of the link, the button is not active. (Note that for similar sections, like bold/italics the corresponding button would be active.) If you type something, the link is extended, which is inconsistent with the button state.

I think you could resolve this issue either way. If the button was shown active, then it's at least consistent with other buttons. If the button was inactive and typing at the end didn't expand the text, that's would be consistent with other editors, like Google Docs.

**Comment by SmilinBrian** [comment] 2017-09-14 22:06
Fixed by other changes?

I can't reproduce this bug using Slate 0.24.0 code (September 12, 2017) with Mac Google Chrome Version 61.0.3163.79.

**Comment by ianstormtaylor** [comment] 2017-09-14 23:13
@SmilinBrian thanks, yup this is fixed!

**Closed by ianstormtaylor** 2017-09-14 23:13 UTC
Labels: bug, ⭐  help please
