### ISSUE TITLE
Editor.previous() returns the incorrect node if match isn't true for the specified location.

### ISSUE THREAD

**Issue by majelbstoat** [ianstormtaylor/slate#3590] opened 2020-04-07 19:16 UTC
#### Do you want to request a _feature_ or report a _bug_?

report a _bug_

#### What's the current behavior?

In `Editor.previous()`, the second result of `Editor.nodes()` is always returned:

https://github.com/ianstormtaylor/slate/blob/master/packages/slate/src/interfaces/editor.ts#L1122

As a result, calling `Editor.previous()` with a location that doesn't satisfy the match function causes the wrong node to be returned.

Example:

https://codesandbox.io/s/crazy-engelbart-evxu3

Slate: 0.57.1
Browser: Chrome
OS: Mac

#### What's the expected behavior?

Editor.previous should always return the first element  that satisfies the match function before the supplied Location.

**Comment by BrentFarese** [comment] 2020-07-24 21:11
#3791, which I submitted appears to be a duplicate of this.

**Comment by BrentFarese** [comment] 2020-07-24 21:12
FWIW, in my own codebase my solution is to find the `Point` after the `at` location passed in and then return the first match after that `Point`.  It works well for me and maybe it'd work well enough for core...

**Comment by BrentFarese** [comment] 2020-11-11 02:57
Fixed by #3957.

**Closed by BrentFarese** 2020-11-11 02:57 UTC
