### ISSUE TITLE
Chinese input is interrupted and disappears during the input of continuous long text

### ISSUE THREAD

**Issue by CodePlayer** [ianstormtaylor/slate#2795] opened 2019-05-17 02:42 UTC
#### Do you want to request a _feature_ or report a _bug_?

bug

#### What's the current behavior?

![slate-chinese-error](https://user-images.githubusercontent.com/3793502/57899381-61530d00-788f-11e9-8e24-40f5b977d50e.gif)

When inputting Chinese, we need to input multiple Pinyin letters continuously, and then press the `Space` key to place the input text into the corresponding text field.

However, when using Slate, if you input long text continuously and have **not** pressed the `Space` key, the continuous input will be interrupted and will be cleared.

This bug is currently only available on the Chrome browser and will not appear on Firefox.

This bug can be reproduced on the official example (I am using the official example).

#### What's the expected behavior?

Continuous long text input will not be interrupted and will be retained correctly.

Related issue: #2349

**Comment by thesunny** [comment] 2019-05-17 14:41
@ianstormtaylor I think this is related to the remove leaves update. I noticed that `set-text-from-dom-node` was not updated and is not working. Any code that uses that function is therefore also not working including composition and Android IME.

https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/src/utils/set-text-from-dom-node.js

I made a cursory look yesterday to fix it but am encountering bugs when doing `insertTextAtRange` which I'm not sure is me or also related bugs in the code since the update. It doesn't make sense to me why I'm getting the errors. This one would also be helpful to have fixed for me to finish Android work.

**Comment by ianstormtaylor** [comment] 2019-05-20 21:43
Hey, thanks for reporting this. I think this is actually a duplicate of https://github.com/ianstormtaylor/slate/issues/2368, so I'm going to close this in favor of that one. Feel free to comment over there with any other info!

**Closed by ianstormtaylor** 2019-05-20 21:43 UTC
