### ISSUE TITLE
Moving caret with arrow keys misbehaving when multiple editors are present

### ISSUE THREAD

**Issue by ikupenov** [ianstormtaylor/slate#4129] opened 2021-03-18 14:44 UTC
**Description**
When multiple editors are present on the same page, regardless of whether they exist within the same Slate context or not, moving the caret with the arrow keys does not work as expected. The behavior differs for each browser; for instance, in Chrome if you focus the first editor and move the caret with the arrow keys, the caret will instantly move to the, seemingly, last editor on the page. In Firefox it will move to the beginning of the current editor. 

**Recording**
https://streamable.com/fs4wae.

**Sandbox**
Can be seen in one of the examples: https://www.slatejs.org/examples/editable-voids.

**Steps**
To reproduce the behavior:
1. Go to 'https://www.slatejs.org/examples/editable-voids'
2. Click on the '+' button at the top left corner
3. Select the **first** editor
4. Press either the left or right arrow key
5. The caret will move to the **second** editor and the editor will be focused

**Expectation**
The caret should stay on the editor that was focused initially.

**Environment**
- Slate Version: [e.g. 0.59]
- Browser: [e.g. Chrome, Safari]

**Comment by ikupenov** [comment] 2021-04-02 10:35
Is there anyone familiar with a possible workaround? I am still stuck on this...

**Comment by skogsmaskin** [comment] 2021-08-23 14:31
Duplicate of this https://github.com/ianstormtaylor/slate/issues/3997

**Closed by skogsmaskin** 2021-08-23 14:31 UTC
Labels: bug
