### ISSUE TITLE
something wrong when i delete from new blank line and the previous line is blank list-item

### ISSUE THREAD

**Issue by sennpang** [ianstormtaylor/slate#3796] opened 2020-07-22 08:18 UTC
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
**delete from new blank paragraph line start**, if **previous line is blank list-item** , list-item node should not delete anything
![Jul-22-2020 16-21-35](https://user-images.githubusercontent.com/16861647/88153087-854e7300-cc37-11ea-8607-1af894d56436.gif)

Slate: 0.58.4
Browser: Chrome
OS: Mac

**Comment by pottedmeat** [comment] 2020-07-23 02:39
This is a duplicate of #3408 and is a problem with any empty trailing node.

**Closed** 2022-06-02 08:10 UTC
