### ISSUE TITLE
Bug: Can't move cursor to the end of the line that ends with an inline element followed by a single character

### ISSUE THREAD

**Issue by mwalkerr** [ianstormtaylor/slate#4000] opened 2020-11-27 18:13 UTC
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

When there is an inline element followed by a single text character at the end of a line, it's impossible to move the cursor past the last character using the arrow keys. This can be seen on the rich text example by deleting everything except the first line and trying to go past the exclamation point:
https://www.slatejs.org/examples/richtext
![out](https://user-images.githubusercontent.com/1845299/100475881-1081be80-3099-11eb-84d1-67de65ce17cb.gif)
In the GIF, I'm only able to move past the exclamation point by using `end` or by leaving an extra character (at the end I left a space)

Slate: 0.59.0
Browser: all
OS: Mac

#### What's the expected behavior?

Cursor should be able to go past the last character

**Comment by skokenes** [comment] 2020-12-29 15:09
I've got the same issue, did you ever find a solution or workaround?

**Comment by mwalkerr** [comment] 2020-12-29 18:38
@skokenes No, unfortunately I never found a fix for this.

**Comment by ridhambhat** [comment] 2021-04-12 15:49
@BrentFarese, please assign this issue to me

**Comment by dan-lee** [comment] 2021-04-12 18:28
I don't know if that's the same issue, but please have a look at the following video:

https://user-images.githubusercontent.com/571589/114441984-55336f80-9bcc-11eb-97d7-7a6ba27e09e9.mov

When I refresh the page with some initial content I try to navigate the cursor with my arrow keys between the adjacent void elements and it doesn't work.

After interacting with the editor, however, it works 


I am not sure if this issue is related or not but I seemed familiar. Please tell me if I should create a new one or not.

**Comment by BrentFarese** [comment] 2021-04-13 12:54
@dan-lee I don't think it's the same issue.  The initialValue doesn't have a text node between the "mention" inlines, then after you type it gets normalized and the normalization puts a text node automatically between the mention inlines.  That is why you can cursor between the inlines after typing but not before (normalization doesn't run on selection changes).

**Comment by dan-lee** [comment] 2021-04-13 15:22
@BrentFarese thanks a lot for your reply! That helped a lot, I could work around by manually calling 
```ts
Editor.normalize(editor, { force: true })
```

I am wondering if this is intended?

**Comment by BrentFarese** [comment] 2021-04-13 15:25
> @BrentFarese thanks a lot for your reply! That helped a lot, I could work around by manually calling
> 
> ```ts
> Editor.normalize(editor, { force: true })
> ```
> 
> I am wondering if this is intended?

Just make your intialValue the below (empty text node between mentions) and your issue should go away.

```
const initialValue: Descendant[] = [
  {
    type: 'paragraph',
    children: [
      { text: 'Try mentioning characters, like ' },
      {
        type: 'mention',
        character: 'R2-D2',
        children: [{ text: '' }],
      },
      { text: '' },
      {
        type: 'mention',
        character: 'Mace Windu',
        children: [{ text: '' }],
      },
    ],
  },
]
```

**Comment by dan-lee** [comment] 2021-04-13 17:28
Thanks again @BrentFarese, I also needed to adjust my `deserialize` function accordingly, now it works :)

**Comment by ridhambhat** [comment] 2021-04-16 15:18
Hey @mwalkerr , 
I tried reproducing the issue but the current behavior was as expected. Tried replicating on both Windows and Mac and on different browsers, but couldn't replicate it. Can you give me some details helping me figure out why I may not be able to replicate it or just confirm whether this issue is resolved for you.

_Current findings_
<img src="https://i.imgur.com/9eP9A5t.gif"></img>

**Comment by skokenes** [comment] 2021-04-16 15:52
I don't see the issue anymore - I believe it may have been fixed by some other recent fix

**Comment by BrentFarese** [comment] 2021-04-16 15:53
Closing this issue as it seems it cannot be reproduced/may be fixed.

**Closed by BrentFarese** 2021-04-16 15:53 UTC
Labels: mlh
