### ISSUE TITLE
Inline node bugs

### ISSUE THREAD

**Issue by hector-esv** [ianstormtaylor/slate#317] opened 2016-09-14 08:58 UTC
On the Links demo:

1. Inserting a link and then undoing throws Uncaught TypeError: Cannot read property 'size' of undefined.
2. Inserting a link at the start of a line, and then backspacing from the end of the link to its beginning: as the first character is deleted it throws Uncaught Error: Could not find a descendant node with key "xinw".
3. Adding text immediately after the link styles the text as part of the link. In other words it doesn't seem easy to add normal text after the link.

I'd be prepared to contribute fixes, but please provide some pointers on what would need to be done. Thanks!

**Comment by kommen** [comment] 2016-09-14 18:25
One more issue I just ran into in our app and can reproduce in the Links demo:

1) Delete the `!` after `hyperlinks` in the first line
2) Press Enter

This results in `TypeError: undefined is not an object (evaluating 'node.nodes.first().kind')`

**Comment by ianstormtaylor** [comment] 2016-09-22 22:36
Thanks for reporting this @hector-esv! I just split this up into multiple errors, since they are solved independently. I'm going to close this one, and tackle them in those smaller issues instead!

**Closed by ianstormtaylor** 2016-09-22 22:36 UTC
Labels: bug
