### ISSUE TITLE
Spellcheck while typing

### ISSUE THREAD

**Issue by jorilallo** [ianstormtaylor/slate#1804] opened 2018-04-30 20:45 UTC
#### Do you want to request a _feature_ or report a _bug_?

- Bug

#### What's the current behavior?

![kapture 2018-04-30 at 13 42 36](https://user-images.githubusercontent.com/31465/39449295-81f672d0-4c7c-11e8-9250-61d7063001be.gif)

Spellchecking checks while typing.

#### What's the expected behavior?

With native input fields, spellchecking seems to be applied only after space or other indication that the user has stopped typing the word.

Not sure if this is even possible to fix, curious if anyone has addressed this.

**Comment by zhujinxuan** [comment] 2018-05-02 15:53
I do not know.  I think it is the strange behavior of Chrome.  We can event reproduce it in `<textarea/>`

**Comment by jorilallo** [comment] 2018-05-02 20:28
@zhujinxuan I'm not able to, it will only do the red underline after space is applied, not while typing the word

**Comment by steobrien** [comment] 2018-06-11 15:22
I think this is a duplicate of https://github.com/ianstormtaylor/slate/issues/1598.

**Comment by zhujinxuan** [comment] 2018-06-11 15:24
@steobrien @jorilallo  I find the solution.  The idea is to prevent the react-rendering in necessary cases.  

I will work on that next week.

**Comment by dmitrizzle** [comment] 2018-06-13 06:04
FWIW spell check with Slate is already a lot better than what Medium.com has (M basically does not work at all). Looking forward to this fix 💪

**Comment by Slapbox** [comment] 2018-08-05 06:46
@zhujinxuan did you make progress on this issue?

**Comment by zhujinxuan** [comment] 2018-08-06 05:35
@Slapbox I am not working on this recently.  It may include a lot of shouldComponentUpdate changes.  I am working on something else, and perhaps switch back to this issue in Nov

**Comment by ianstormtaylor** [comment] 2018-08-08 02:26
Closing in favor of #1598, as @steobrien reported.

**Closed by ianstormtaylor** 2018-08-08 02:26 UTC
Labels: bug, ♥ help please
