### ISSUE TITLE
html serialize, node.getLeaves is not a function

### ISSUE THREAD

**Issue by gorillatron** [ianstormtaylor/slate#1789] opened 2018-04-20 10:58 UTC
Following the example given on the webpage the html serializer throws the following error upon calling serialize:

```
Uncaught TypeError: node.getLeaves is not a function
```

**Comment by CameronAckermanSEL** [comment] 2018-04-20 18:13
Hi, you might be using a version of the serializer that doesn't match with the version of slate.  But it's kind of hard to tell because there's not a lot of information in this issue.

Could you provide some code that can reproduce your issue? Double checking your `yarn.lock` file and your `package.json` file might help.

**Comment by ianstormtaylor** [comment] 2018-04-20 21:04
Hey, thanks for using Slate! Unfortunately, we can't offer support for usage questions in the issues here because it becomes overwhelming to maintain the project if the issues are filled with questions. 

However, we do have a Slack channel and people are constantly asking and answering questions in there. So I'm going to close this issue, but I definitely recommend joining the Slack channel if you want to find people that might be able to help. 

Thanks for understanding!

**Closed by ianstormtaylor** 2018-04-20 21:04 UTC
Labels: question

**Comment by istarkov** [comment] 2018-04-30 16:18
@gorillatron this usually happens if you pass just JSON into serializer
you need to parse it before as like as

```javascript
import { Value } from 'slate';

serialize(Value.fromJSON(yourObj))
```
