### ISSUE TITLE
Press space in the wrapped second line eats the first line

### ISSUE THREAD

**Issue by terryoy** [ianstormtaylor/slate#938] opened 2017-07-17 12:32 UTC
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?

![image](http://g.recordit.co/bl4qrkSQ6b.gif)

#### What's the expected behavior?

Just insert plain space...

**Comment by hubgit** [comment] 2017-07-20 12:17
I'm able to reproduce this on http://slatejs.org/#/plain-text by entering a long line of text and trying to type a space at the start of the wrapped line.

**Comment by J22Melody** [comment] 2017-07-28 06:25
Same here, on Chrome it will eat the first line while on Safari it won't get any response

**Comment by tommyokeefe** [comment] 2017-08-10 18:20
Any eta on a fix for this? We're using slate @ NPR for the editor in our cms and I just ran into this bug when an editor lost a chunk of text in a story.

**Comment by danburzo** [comment] 2017-08-15 11:12
I can confirm the simplified use-case: just causing the line to wrap and pressing Space at the beginning of the second line will eat the first lien of text in Chrome 60/macOS. Safari/FF seem to be okay.

**Comment by danburzo** [comment] 2017-08-15 12:27
Okay, found it! The problem is generated by the CSS rule `-webkit-user-modify: read-write-plaintext-only;`. It causes Chrome to wrongly report window.getSelection().anchorNode as being only the _second_ line of text, and the offset = 0.

**Comment by danburzo** [comment] 2017-08-15 15:13
To mitigate the problem we can prevent the default behavior in Chrome and replace it with a synthetic insertion of the Space character: 

```js
  // this is in plugins/core.js
  function onKeyDownSpace(e, data, state) {
    if (IS_CHROME) {
      e.preventDefault();
      return state.transform().insertText(' ').apply();
    }
  }
```

Seems to get rid of the problem. You can put this into a plugin, or — if it's something we can have as part of the core — directly in the core plugin.

**Comment by tommyokeefe** [comment] 2017-08-15 15:17
@danburzo I played with that approach to mitigating the problem locally but ended up deciding against it. The extra space characters all get pushed to the end of the previous line (before the break) so a user could theoretically add a bunch of spaces unintentionally and not see them until text is published. Just something to consider.

**Comment by danburzo** [comment] 2017-08-15 15:25
@tommyokeefe you're right, but logically that's where it's supposed to be, and by patching Chrome all browsers behave in a fairly consistent manner. You'll see the same behavior in Google Docs and various desktop apps, as well.

**Comment by tommyokeefe** [comment] 2017-08-15 15:26
Ahh. True. Good point.

**Closed** 2017-08-15 17:42 UTC
Labels: bug, ⭐  help-please

**Comment by danburzo** [comment] 2017-08-16 10:33
@ianstormtaylor can you reopen this? Seems I have messed up IME on Chrome 🥇 I want to take another stab at it.
