### ISSUE TITLE
insertFragment fails on nested blocks 

### ISSUE THREAD

**Issue by Soreine** [ianstormtaylor/slate#1493] opened 2017-12-27 15:37 UTC
#### Do you want to request a *feature* or report a *bug*?

A bug

#### What's the current behavior?

As of slate@0.31.7 go to http://slatejs.org/#/rich-text and **triple click the quote** "A wise quote." to select the whole line, **then paste any piece of plain text** here. This triggers `insertFragmentAtRange` which fails

```
Uncaught TypeError: Cannot read property 'key' of undefined
    at Changes.insertFragmentAtRange (http://slatejs.org/build.prod.js:5089:8501)
    at e.value (http://slatejs.org/build.prod.js:5125:2404)
    at e.Change.(anonymous function) [as insertFragmentAtRange] (http://slatejs.org/build.prod.js:5125:2880)
    at Changes.insertFragment (http://slatejs.org/build.prod.js:5086:1769)
    at e.value (http://slatejs.org/build.prod.js:5125:2404)
    at e.Change.(anonymous function) [as insertFragment] (http://slatejs.org/build.prod.js:5125:2880)
    at Object.f [as onPaste] (http://slatejs.org/build.prod.js:5032:5358)
    at t.value (http://slatejs.org/build.prod.js:5161:2517)
    at http://slatejs.org/build.prod.js:5001:5650
    at e.value (http://slatejs.org/build.prod.js:5125:2404)
```
#### What's the expected behavior?

It should not fail

This makes it hard to paste in code blocks or lists for example, depending on the nested structure your app is using.

**Comment by tobiasandersen** [comment] 2018-01-18 12:25
This might be a stupid question, but what is the expected behavior here? Should it insert the pasted fragment into the quote-block (1), or should it replace the quote with the fragment (2/3)?
 
Let's say I paste the word "Hello", which of these are "correct"?

1:
<img width="715" alt="screen shot 2018-01-18 at 13 20 27" src="https://user-images.githubusercontent.com/3599069/35097909-860dbeca-fc52-11e7-80e0-bb64079e5efb.png">

2:
<img width="715" alt="screen shot 2018-01-18 at 13 20 53" src="https://user-images.githubusercontent.com/3599069/35097920-8fc2e51c-fc52-11e7-9e93-5e184a1acafe.png">

3:
<img width="714" alt="screen shot 2018-01-18 at 13 21 07" src="https://user-images.githubusercontent.com/3599069/35097926-95e4f098-fc52-11e7-830b-383c2908b592.png">

Personally I feel like (1) makes more sense. But maybe there're other situations where that behavior could be problematic?

**Comment by dmitrizzle** [comment] 2018-01-18 12:42
I'd expect (1) as that's what every other rich text editor does to my knowledge: paste and match style. Since that's what plain text is: data with no style association, meaning we have to assume some kind of style to it, which is usually derived from the location of paste.

**Comment by tobiasandersen** [comment] 2018-01-18 12:46
I had a look at how Dropbox Paper handles it. If I at this point paste the word "Hello":

<img width="755" alt="screen shot 2018-01-18 at 13 42 27" src="https://user-images.githubusercontent.com/3599069/35098692-85f5051c-fc55-11e7-9b3c-6d47930f6eb2.png">


I actually end up with:

<img width="767" alt="screen shot 2018-01-18 at 13 40 11" src="https://user-images.githubusercontent.com/3599069/35098682-7dac44c4-fc55-11e7-9d65-68b2b8bcfd04.png">

So I guess we have a fourth candidate:
4:
<img width="716" alt="screen shot 2018-01-18 at 13 44 43" src="https://user-images.githubusercontent.com/3599069/35098806-e9bed8fc-fc55-11e7-8e26-1753577a177f.png">

**Comment by ianstormtaylor** [comment] 2018-01-25 20:54
I think (1) is the most expected.

There's a common issue that is when a user triple-clicks, they are usually referring to the idea of "the entire block", but the browser happens to put the focus point at the start of the next. Which explains the Dropbox Paper behavior, even though it's non-obvious.

That said, it might be harder to get that working to start, and we could start with the Dropbox Paper behavior if so.

**Comment by benjycui** [comment] 2018-03-29 03:08
Most of us expect 1. But why do we delete start block when selection is hanging?

https://github.com/ianstormtaylor/slate/blob/fb8075a2332b97abdc9fb8baae2ad3da052cba9f/packages/slate/src/changes/at-range.js#L244-L250

IMO, we just need to clean children of start block, and we don't need to delete start block or merge end block.

**Comment by ianstormtaylor** [comment] 2019-05-09 03:01
See https://github.com/ianstormtaylor/slate/issues/2746

**Comment by ianstormtaylor** [comment] 2019-11-28 03:10
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Closed by ianstormtaylor** 2019-11-28 03:10 UTC
Labels: bug, ♥ help
