### ISSUE TITLE
Programmatically triggered changes are not being normalized

### ISSUE THREAD

**Issue by grsmvg** [ianstormtaylor/slate#2264] opened 2018-10-15 14:31 UTC
Using Slate 0.42.2, if you trigger changes programmatically, you need to call `normalize()` yourself.

See the bug in action here:

https://jsfiddle.net/gersomvg/fj9dvhom/2451/

I would expect normalization to take place without invoking manually, since the docs state:
> The vast majority of changes, whether by the user or invoked programmatically, will run normalize by default to ensure the document is always in adherence to its schema.

I can try to PR this myself, after this is confirmed by someone else as a bug.

**Comment by tomaratyn** [comment] 2018-10-17 18:15
This is a great question as I'm a bit confused by some of the changes in 0.42.x. One thing that the changelog says is:

> Remove the Schema "model", in favor of the new Editor.

Perhaps this is working as intended then?

**Comment by ianstormtaylor** [comment] 2018-10-18 00:48
I think it’s a bug with `marks` specifically. Since they’re the only rule that crosses many layers in the tree. We need to be re-validating all the ancestors of changed noes instead of just them and their direct parent. That should solve it.

**Comment by grsmvg** [comment] 2018-10-24 14:49
I've found a related bug.

If you do this:
```
change.insertNodeByKey(document.key, 1, {
    object: 'block',
    type: 'divider',
});
```

Then `normalizeNode` is only invoked once for the divider node and not for the document as a whole.

This can be solved again by calling `normalize` manually:

```
change.insertNodeByKey(...).normalize()
```

**Comment by Slapbox** [comment] 2018-10-24 14:55
I agree, the entire schema appears to have a few bugs in 0.42. I set a break point in `validateNode` and found that it doesn't trigger for a number of my rules. It's hard to say exactly what rules don't get normalized, but I'd say this is the most serious issue in Slate at the moment, and the one least likely to be addressable by the community. @ianstormtaylor do you have any thoughts on the potential cause?

**Comment by ianstormtaylor** [comment] 2018-10-24 15:46
Closing in favor of https://github.com/ianstormtaylor/slate/issues/2312.

**Closed by ianstormtaylor** 2018-10-24 15:46 UTC
