### ISSUE TITLE
Unexpected scroll when start/end of a block is outside the viewport

### ISSUE THREAD

**Issue by zbeyens** [ianstormtaylor/slate#3146] opened 2019-11-28 19:30 UTC
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

https://i.imgur.com/p28xul5.gifv

https://www.slatejs.org/examples/rich-text 

Just paste a long paragraph. It scrolls everytime the start or the end of the block is outside the viewport. Scroll target seems to be the middle of the block?

Chrome 78.0.3904.108
Windows 10
Slate v0.50.0

#### What's the expected behavior?

It should not scroll when the cursor is in the viewport.

**Comment by ejoebstl** [comment] 2019-12-10 14:29
Proposed a setting to turn this on/off in #3284.

**Comment by ianstormtaylor** [comment] 2019-12-10 16:08
What’s the use case for adding a configuration to turn it off?

**Comment by ejoebstl** [comment] 2019-12-10 16:27
To prevent this behavior. 

An alternative would be to remove it entirely, but then it could break use cases I'm not aware of.

**Comment by ianstormtaylor** [comment] 2019-12-10 17:49
Prevent what behavior? And to what end?

**Comment by ejoebstl** [comment] 2019-12-10 18:27
The behavior described in this very issue by the original author. 

When a long paragraph which is partly out of the viewport gets selected, the window is scrolled so the paragraph is centered in the viewport. Also, the behavior is not consistent. Sometimes it does scroll, sometimes it does not.

I think this is rather unexpected and I'd like to turn it of, hence this PR.

Hope that helps!

**Comment by ianstormtaylor** [comment] 2019-12-10 19:08
Gotcha, yes the current bug of scrolling incorrectly should be fixed.

I don't think that merits adding more configuration to disable scrolling. It should instead be fixed so that it mimics the built-in browser behavior properly.

**Comment by thallada** [comment] 2020-01-23 18:15
My 2 cents: I think #3284 is worth merging regardless of the bug or not.

I have implemented my own scrolling logic for the editor that runs `onKeyDown` and `onSelect`. It does custom things that most users of Slate probably don't want (e.g. keeps a certain amount of buffer space between the cursor and the edge of the scroll container). But, this broken scrolling is running first and causes the scroll to jump back and forth. With no way to disable the Slate scrolling, I have to fork slate to remove the code.

**Comment by tgonzalez-asapp** [comment] 2020-02-16 17:21
I'm experiencing this issue too in a scrollable input. Turning off auto-scroll as proposed doesn't seem to improve things in this case:
![no-auto-scroll](https://user-images.githubusercontent.com/1714020/74609248-1472c000-50c7-11ea-9b60-6ddee80b4950.gif)
And this is the current broken behavior with the existing auto-scroll:
![current-auto-scroll](https://user-images.githubusercontent.com/1714020/74609268-4c7a0300-50c7-11ea-8491-8110639d9275.gif)
I've seen that scrolling is natively handled fine at least in chrome for a `<div contenteditable="true" />`, wondering what is slate doing that prevents the native behavior.

**Comment by borgar** [comment] 2020-04-02 16:52
I work on a large project that uses Slate and we would love to be able to disable or override the default scrolling via a prop. We have navigation and editing controls that we need to make sure don't obscure the cursor, and we also have very large block elements which have "scrolling focal points" in different areas of the block. Essentially this is similar to what @thallada says above, we require specialized scrolling that the Slate framework will never want.

Also, I may just have filed something that is very related or perhaps a duplicate of this issue: #3576

**Comment by CameronAckermanSEL** [comment] 2020-05-22 22:40
Hey @zbeyens, I went to check this out today and I wasn't able to reproduce it, but I'm not exactly sure I was using the right steps. Could you see if this bug still exists on latest examples? I think a PR merged in recently might have fixed it.

**Comment by zbeyens** [comment] 2020-05-22 22:45
Hi @CameronAckermanSEL , it looks to be fixed (at least for the STR), thanks!

**Comment by gztomas** [comment] 2020-06-20 04:34
It seems that the problem still exists, it can be repro here https://codesandbox.io/s/slate-scroll-issue-hlwv0
Typing in that input will auto-scroll to the middle.

**Closed** 2021-03-31 19:50 UTC
Labels: bug, ♥ help
