### ISSUE TITLE
"Invalid attempt to destructure non-iterable instance" in getActiveMarksAtRange()

### ISSUE THREAD

**Issue by vnugent** [ianstormtaylor/slate#2701] opened 2019-04-23 07:19 UTC
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
Slate crashes when I select an empty paragraph and empty custom block.  The problem seems to originate from `Document.getActiveMarksAtRange()`
```
<card>
   <location>
   </location>
   <description><--- place cursor here and then shift-down arrow (or drag mouse to begin select text)
  </description>
</card>
<normal_paragraph> 
```
![image](https://user-images.githubusercontent.com/3805254/56561663-81c3cc00-655c-11e9-98d9-29f0a789a1b3.png)

I'll try to create a jfiddle

**Comment by glebtv** [comment] 2019-05-12 20:28
Also having this issue with slate-deep-table plugin (which does nothing unusual and works by itself).

Here's a fiddle with only table plugin and slate 0.46, and it works fine:
https://codesandbox.io/s/vj1w98m787?fontsize=14

https://codesandbox.io/s/4zq7l5nvlx

Here's a fiddle with 

Here's a fiddle with 

Workaround:
```
  hasMark = type => {
    const { value } = this.props.editorState;
    var has = false
    try {
      has = value.activeMarks.some(mark => mark.type == type);
    } catch(e) {
      console.error(e)
    }
    return has
  };
```

**Comment by justinweiss** [comment] 2019-05-15 00:02
I've been running into this, and it seems like the problem is that `getPreviousMatchingNodeAndPath` doesn't work. It only does raw path manipulation. So if you have a document like:and a selection where

`startPath`: `[1, 1, 0, 0]`
`endPath`:  `[1, 2, 1, 0]`

**Comment by ianstormtaylor** [comment] 2019-11-28 02:24
Fixed by https://github.com/ianstormtaylor/slate/pull/3093.

**Closed by ianstormtaylor** 2019-11-28 02:24 UTC
Labels: ⚑ needs info, ⚑ needs sandbox
