### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isNative' of undefined

### ISSUE THREAD

**Issue by calepsol** [ianstormtaylor/slate#981] opened 2017-08-13 19:44 UTC
```
import React from 'react'
import ReactDOM from 'react-dom'
import Portal from 'react-portal'
import { Editor, Raw } from 'slate'

/**
 * Define a schema.
 *
 * @type {Object}
 */

const initialState = {
  "nodes": [
    {
      "kind": "block",
      "type": "paragraph",
      "nodes": [
        {
          "kind": "text",
          "ranges": [
            {
              "text": "This example shows how you can make a hovering menu appear above your content, which you can use to make text "
            },
            {
              "text": "bold",
              "marks": [
                {
                  "type": "bold"
                }
              ]
            },
            {
              "text": ", "
            },
            {
              "text": "italic",
              "marks": [
                {
                  "type": "italic"
                }
              ]
            },
            {
              "text": ", or anything else you might want to do!"
            }
          ]
        }
      ]
    },
    {
      "kind": "block",
      "type": "paragraph",
      "nodes": [
        {
          "kind": "text",
          "ranges": [
            {
              "text": "Try it out yourself! Just "
            },
            {
              "text": "select any piece of text and the menu will appear",
              "marks": [
                {
                  "type": "bold"
                },
                {
                  "type": "italic"
                }
              ]
            },
            {
              "text": "."
            }
          ]
        }
      ]
    }
  ]
}

const schema = {
  marks: {
    bold: props => <strong>{props.children}</strong>,
    code: props => <code>{props.children}</code>,
    italic: props => <em>{props.children}</em>,
    underlined: props => <u>{props.children}</u>,
  }
}

/**
 * The hovering menu example.
 *
 * @type {Component}
 */

class HoveringMenu extends React.Component {

  /**
   * Deserialize the raw initial state.
   *
   * @type {Object}
   */
  constructor(props) {
    super(props);
    this.state = {
      state: Raw.deserialize(initialState, { terse: true })
    }
  }

  /**
   * On update, update the menu.
   */

  componentDidMount() {
    this.updateMenu()
  }

  componentDidUpdate() {
    this.updateMenu()
  }

  /**
   * Check if the current selection has a mark with `type` in it.
   *
   * @param {String} type
   * @return {Boolean}
   */

  hasMark(type) {
    const { state } = this.state
    return state.marks.some(mark => mark.type == type)
  }

  /**
   * On change, save the new state.
   *
   * @param {State} state
   */

  onChange(state) {
    this.setState({ state })
  }

  /**
   * When a mark button is clicked, toggle the current mark.
   *
   * @param {Event} e
   * @param {String} type
   */

  onClickMark(e, type) {
    e.preventDefault()
    let { state } = this.state

    state = state
      .transform()
      .toggleMark(type)
      .apply()

    this.setState({ state })
  }

  /**
   * When the portal opens, cache the menu element.
   *
   * @param {Element} portal
   */

  onOpen(portal) {
    this.setState({ menu: portal.firstChild })
  }

  /**
   * Render.
   *
   * @return {Element}
   */

  render() {
    return (
      <div>
        {this.renderMenu()}
        {this.renderEditor()}
      </div>
    )
  }

  /**
   * Render the hovering menu.
   *
   * @return {Element}
   */

  renderMenu() {
    return (
      <Portal isOpened onOpen={(e) => this.onOpen(e)}>
        <div className="menu hover-menu">
          {this.renderMarkButton('bold', 'format_bold')}
          {this.renderMarkButton('italic', 'format_italic')}
          {this.renderMarkButton('underlined', 'format_underlined')}
          {this.renderMarkButton('code', 'code')}
        </div>
      </Portal>
    )
  }

  /**
   * Render a mark-toggling toolbar button.
   *
   * @param {String} type
   * @param {String} icon
   * @return {Element}
   */

  renderMarkButton(type, icon) {
    const isActive  = e => this.hasMark(type)
    const onMouseDown = e => this.onClickMark(e, type)

    return (
      <span className="button" onMouseDown={onMouseDown} data-active={isActive}>
        <span className="material-icons">{icon}</span>
      </span>
    )
  }

  /**
   * Render the Slate editor.
   *
   * @return {Element}
   */

  renderEditor() {
    return (
      <div className="editor">
        <Editor
          schema={schema}
          state={this.state.state}
          onChange={() => this.onChange()}
        />
      </div>
    )
  }

  /**
   * Update the menu's absolute position.
   */
  updateMenu() {
    const { menu, state } = this.state
    if (!menu) return

    if (state.isBlurred || state.isEmpty) {
      menu.removeAttribute('style')
      return
    }

    const selection = window.getSelection()
    const range = selection.getRangeAt(0)
    const rect = range.getBoundingClientRect()
    menu.style.opacity = 1
    menu.style.top = `${rect.top + window.scrollY - menu.offsetHeight}px`
    menu.style.left = `${rect.left + window.scrollX - menu.offsetWidth / 2 + rect.width / 2}px`
  }

}

/**
 * Export.
 */

export default HoveringMenu
```

**Comment by calepsol** [comment] 2017-08-14 15:15
![screenshot from 2017-08-14 17-14-44](https://user-images.githubusercontent.com/10830896/29278144-21bd6d3a-8114-11e7-8e60-411bfa8e0b79.png)

**Comment by danburzo** [comment] 2017-08-15 17:07
Hi @calepsol, could you try to recreate a simplified case that reproduces the issue based on [this JSFiddle template](https://jsfiddle.net/2zokvrvt/7/)? It will help anyone trying to tackle this issue.

**Comment by ianstormtaylor** [comment] 2017-08-15 17:36
Hey, thanks for using Slate. Unfortunately, this issue doesn't have enough information to make it easy for maintainers to actually respond. 

We usually require that all issues include a JSFiddle that reproduces the problem (using the [template here](https://jsfiddle.net/2zokvrvt/7/)), a short explanation of what is going on, and a GIF showing the problem in action. Without those, trying to diagnose what the issue even is in the first place takes a lot more time, and seeing as the project is still in beta and people are working on different things, it's likely that without those the issue won't get fixed any time soon. 

Please read the [contributing instructions](https://github.com/ianstormtaylor/slate/blob/master/Contributing.md).

I'm going to close this issue, because I have to keep issues cleaned for maintenance to be manageable. But feel free to either ask more questions in our [Slack channel](https://slate-slack.herokuapp.com/), or to recreate a new issue with more information that clearly outlines the problem. Thanks for understanding.

**Closed by ianstormtaylor** 2017-08-15 17:36 UTC

**Comment by beeant** [comment] 2017-09-10 19:33
I got this error too..

**Comment by calepsol** [comment] 2017-09-14 20:17
paste a code into https://jsfiddle.net/ and share, for more information
