### ISSUE TITLE
Selection issue in Safari

### ISSUE THREAD

**Issue by kib357** [ianstormtaylor/slate#1481] opened 2017-12-15 19:48 UTC
#### Do you want to request a *feature* or report a *bug*?

bug

#### What's the current behavior?

When trying to implement one-line editor, i'm getting this error in Safari:
https://jsfiddle.net/tesvg2qw/
Please try to put the cursor in the end of input and then press backspace.
Error only throws when editor (or it's descendent) has `white-space: nowrap` style applied.
![image](https://user-images.githubusercontent.com/347668/34057847-8222cb60-e1fa-11e7-9eef-1e7f6cbfa6c0.png)

#### What's the expected behavior?

I know it's looks like a Safari bug, but maybe we can found some workaround for this behaviour.

**Comment by zGrav** [comment] 2017-12-24 14:41
After a bit of testing, it seems that it loses anchorNode/focusNode due to the wrapping... it's one of those quirks with Safari I guess...

I did find a workaround, but not sure if... well, it's the right approach.

`      if (_environment.IS_SAFARI) {
        if (native.anchorNode.textContent.endsWith(' ')) {
            native.anchorNode.textContent = native.anchorNode.textContent.replace(' ', '\u00a0')
        }
      }`

If @ianstormtaylor doesn't see a problem with it, I can build a PR for it.

**Comment by ianstormtaylor** [comment] 2017-12-29 19:03
Hey @zGrav thank you for investigating.

For that PR, I think editing the underlying text itself should be our last resort, since it's going to cause issues with copy-pasting, where we end up with artifacts.

Is there a way to fix this in the selection-handling logic instead? or other behavioral logic?

**Comment by zGrav** [comment] 2017-12-29 19:07
@ianstormtaylor if there is, I haven't discovered it as of now, it just feels like a very very quirky issue with Safari and how it handles wrapping the whitespace itself since the issue is not present in Chrome (have not tested Firefox).

**Comment by ianstormtaylor** [comment] 2017-12-29 19:13
Yeah true. Is there an open browser issue for this? 

I'm worried about just patching it without having some knowledge of why it's happening, but I'd be open to the PR. I think it would need to be reworked though to be more foolproof. It should probably be at render time, instead of editing the node at selection update time. And it should be done in a way that doesn't affect the copy-paste content (using a wrapping span that can be adjusted I think, like we do with zero-width spaces).

**Comment by zGrav** [comment] 2018-01-09 20:45
@ianstormtaylor picking this one back up as well.

I am not quite sure there is a browser issue for it, at least I cannot find one.

**Comment by kinhbang89** [comment] 2018-01-23 13:37
Is there any update or fixes in this Safari issue?

**Comment by ianstormtaylor** [comment] 2019-11-28 03:07
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Closed by ianstormtaylor** 2019-11-28 03:07 UTC
Labels: bug, ♥ help, ⚑ cross platform
