### ISSUE TITLE
KeyDown `Space` eat some characters

### ISSUE THREAD

**Issue by pizn** [ianstormtaylor/slate#968] opened 2017-08-02 12:06 UTC
The current behavior?

![space](https://user-images.githubusercontent.com/986480/28872938-e561354c-77bd-11e7-852e-500a95cb3c59.gif)

---

macOS + Chrome 60

1. Anchor at one lines first character
2. Keydown `Space`
3. It will eat some characters

**Comment by schneidmaster** [comment] 2017-08-02 15:04
This is a duplicate of #938. (I have been working on-and-off on a PR to fix but it's trickier than you might think.)

**Comment by ianstormtaylor** [comment] 2017-08-02 16:29
Closing as it's a dupe, thanks @pizn!

**Closed by ianstormtaylor** 2017-08-02 16:29 UTC
