### ISSUE TITLE
Pasting in text with tab characters breaks the editor in strange ways

### ISSUE THREAD

**Issue by gdehmlow** [ianstormtaylor/slate#960] opened 2017-07-31 20:54 UTC
#### Do you want to request a *feature* or report a *bug*?

Bug

#### What's the current behavior?

![slatebug](https://user-images.githubusercontent.com/850025/28797610-c2f7a180-75f6-11e7-959b-bb570eb9fdd4.gif)

I pasted in some text with tab characters in it. I then proceed to add some additional text and then hit Cmd-Z to undo my work. Strange things happen - When I added text next to the tab and then hit undo, it appeared to copy the text. I also tried deleting all the text, but the text still appeared along with the placeholder.

#### What's the expected behavior?

Tab characters shouldn't cause weird behavior.

#### My thoughts

I noticed a bug similar to this in my production implementation with DraftJS (but not on the [Draft demo website](https://draftjs.org/)) and was curious if Slate had the same problem.

If I check out the DOM after inserting some text next to a tab, it looks really funky:

<img width="953" alt="screen shot 2017-07-31 at 1 53 01 pm" src="https://user-images.githubusercontent.com/850025/28797893-af640ff4-75f7-11e7-9c2e-d0d41615b607.png">

Notice the text I inserted *isn't* inside `<span>` blocks.

**Comment by danburzo** [comment] 2017-08-15 12:49
This is a recent regression in Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=741826 — it splits text containing tab characters.

**Comment by danburzo** [comment] 2017-08-15 15:35
@gdehmlow In the Chromium conversation I see a FB developer mentioned they patched for this behavior, so I am assuming the patch landed in Draft.js as well? Couldn't find _where_ it got patched, though...

**Comment by danburzo** [comment] 2017-08-15 16:26
I may be taking a facile route here, but until a better solution comes around, tab chars can be converted so spaces (removing, of course, the support for pasting tab characters altogether):

```js
// content.js
onPaste() {
    // ...
    // replace tab chars with 2 (or maybe 4?) spaces
    if (IS_CHROME) {
      data.text = data.text.replace(/\t/g, '    ')
    }
    // ...
}
```

The patch can be placed at one of three levels:

1. in `content.js`
2. in `plugins/core.js`
3. in an external plugin

**Comment by steida** [comment] 2018-07-23 16:48
It seems to be fixed. Can be closed imho. https://bugs.chromium.org/p/chromium/issues/detail?id=741826

**Comment by ianstormtaylor** [comment] 2018-07-23 18:45
Thanks @steida!

**Closed by ianstormtaylor** 2018-07-23 18:45 UTC
Labels: bug, ♥ help please
