### ISSUE TITLE
IE11 cursor jumps when set text to bold (using rich text editor example)

### ISSUE THREAD

**Issue by ProductiveRage** [ianstormtaylor/slate#1784] opened 2018-04-17 13:12 UTC
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

(Note: I'm aware that IE11 is not being given priority support in this beta stage but I thought that I would raise this bug in case anyone could point me in the right direction or let me know if they have seen this issue before)

I'm using the polyfills "babel-polyfill" (so that Symbol support is available) and "element-closest" (so that element.closest is available) to try to get things working.

If I use the rich text editor example and select some text to make bold, when I click the "b" in the toolbar then the text _is_ successfully bolded but the cursor jumps away to the wrong place in the document. The same happens if I remove the bold styling and if I use italic styling. Sometimes it jumps to the start of the line and sometimes it jumps to the start of the next work.

See video here: [http://recordit.co/pYGfsE5FhH](http://recordit.co/pYGfsE5FhH)

(My description sounds similar to the title of this issue: [IE11 Selection Blur Bug](https://github.com/ianstormtaylor/slate/issues/1187) - but that issue's description sounds like it's something different)

~~Apologies that I can't provide a JSFiddle, I tried but failed! I tried to create an example in Chrome that loaded in the required polyfills for IE11 (see [https://jsfiddle.net/fj9dvhom/332/](https://jsfiddle.net/fj9dvhom/332/)) but when I load that in IE11 it doesn't work (the sidebar is missing and there is a "SCRIPT5: Access is denied" error in the console - see the screenshot that I've attached at the bottom of this content for reference).~~ I couldn't get the example to work in JSFiddle, I'm afraid, but I have got a complete example working here: [https://codesandbox.io/s/1ylqxl21lq](https://codesandbox.io/s/1ylqxl21lq)

Also, further down, I've listed the content of all of the files necessary to create a new project from scratch using npm and webpack.

I'm testing on Windows 8.1 with IE11 (11.0.9600.18978) and current latest Slate (0.33.4) and React (16.3.1).

#### What's the expected behavior?

This works fine in Chrome, the cursor behaves itself. It would be great to get this working in IE11 too,

#### The example project

To set this up from scratch, the following files are needed:

- index.html
- main.css
- main.js
- package.json
- webpack.config.js

(After creating these files, run `npm install` and then `npm run webpack`)

The main.css file is taken from the Slate examples site and main.js is basically the rich text editor example from the Slate site but with a little extra code to load polyfills and to render an editor on the page.

Their contents are as follows:

**index.html**

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Basic application with Webpack</title>
    <link rel="stylesheet" href="main.css"></link>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,400i,700,700i&subset=latin-ext"></link>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"></link>
  </head>
  <body>
    <script src="dist/bundle.js"></script>
  </body>
</html>
```

**package.json**

```
{
  "name": "SlateJsExperiment",
  "version": "1.0.0",
  "description": "test",
  "repository": "https://shush.com",
  "main": "main.js",
  "scripts": {
    "babel": "babel --presets es2015 main.js -o dist/bundle.js",
    "start": "http-server",
    "webpack": "webpack"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "webpack": "^4.5.0",
    "webpack-cli": "^2.0.14"
  },
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "element-closest": "^2.0.2",
    "immutable": "^3.8.2",
    "react": "^16.3.1",
    "react-dom": "^16.3.1",
    "slate": "^0.33.4",
    "slate-html-serializer": "^0.6.1",
    "slate-plain-serializer": "^0.5.10",
    "slate-react": "^0.12.4"
  }
}
```

**webpack.config.js**

```
var path = require('path');
var webpack = require('webpack');

module.exports = {
    entry: './main.js',
    mode: 'none',
    watch: true,
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'bundle.js'
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /(node_modules|bower_components)/,
                use: { 
                  loader: 'babel-loader',
                  options: {
                    presets: ['env', 'es2015', 'stage-0', 'react']
                  }
                } 
            }
        ]
    },
    stats: {
        colors: true
    },
    devtool: 'source-map'
};
```
**main.js**

```
import "babel-polyfill";
import "element-closest";

import { Editor } from 'slate-react'
import { Value } from 'slate'

import React from 'react'
import ReactDOM from 'react-dom'
import { isKeyHotkey } from 'is-hotkey'

const initialValue = {"document":{"nodes":[{"object":"block","type":"paragraph","nodes":[{"object":"text","leaves":[{"text":"This is editable "},{"text":"rich","marks":[{"type":"bold"}]},{"text":" text, "},{"text":"much","marks":[{"type":"italic"}]},{"text":" better than a "},{"text":"<textarea>","marks":[{"type":"code"}]},{"text":"!"}]}]},{"object":"block","type":"paragraph","nodes":[{"object":"text","leaves":[{"text":"Since it's rich text, you can do things like turn a selection of text "},{"text":"bold","marks":[{"type":"bold"}]},{"text":", or add a semantically rendered block quote in the middle of the page, like this:"}]}]},{"object":"block","type":"block-quote","nodes":[{"object":"text","leaves":[{"text":"A wise quote."}]}]},{"object":"block","type":"paragraph","nodes":[{"object":"text","leaves":[{"text":"Try it out for yourself!"}]}]}]}};

const DEFAULT_NODE = 'paragraph'

const isBoldHotkey = isKeyHotkey('mod+b')
const isItalicHotkey = isKeyHotkey('mod+i')
const isUnderlinedHotkey = isKeyHotkey('mod+u')
const isCodeHotkey = isKeyHotkey('mod+`')

class RichTextExample extends React.Component {
  state = {
    value: Value.fromJSON(initialValue),
  }

  hasMark = type => {
    const { value } = this.state
    return value.activeMarks.some(mark => mark.type == type)
  }

  hasBlock = type => {
    const { value } = this.state
    return value.blocks.some(node => node.type == type)
  }

  onChange = ({ value }) => {
    this.setState({ value })
  }

  onKeyDown = (event, change) => {
    let mark

    if (isBoldHotkey(event)) {
      mark = 'bold'
    } else if (isItalicHotkey(event)) {
      mark = 'italic'
    } else if (isUnderlinedHotkey(event)) {
      mark = 'underlined'
    } else if (isCodeHotkey(event)) {
      mark = 'code'
    } else {
      return
    }

    event.preventDefault()
    change.toggleMark(mark)
    return true
  }

  onClickMark = (event, type) => {
    event.preventDefault()
    const { value } = this.state
    const change = value.change().toggleMark(type)
    this.onChange(change)
  }

  onClickBlock = (event, type) => {
    event.preventDefault()
    const { value } = this.state
    const change = value.change()
    const { document } = value

    // Handle everything but list buttons.
    if (type != 'bulleted-list' && type != 'numbered-list') {
      const isActive = this.hasBlock(type)
      const isList = this.hasBlock('list-item')

      if (isList) {
        change
          .setBlocks(isActive ? DEFAULT_NODE : type)
          .unwrapBlock('bulleted-list')
          .unwrapBlock('numbered-list')
      } else {
        change.setBlocks(isActive ? DEFAULT_NODE : type)
      }
    } else {
      // Handle the extra wrapping required for list buttons.
      const isList = this.hasBlock('list-item')
      const isType = value.blocks.some(block => {
        return !!document.getClosest(block.key, parent => parent.type == type)
      })

      if (isList && isType) {
        change
          .setBlocks(DEFAULT_NODE)
          .unwrapBlock('bulleted-list')
          .unwrapBlock('numbered-list')
      } else if (isList) {
        change
          .unwrapBlock(
            type == 'bulleted-list' ? 'numbered-list' : 'bulleted-list'
          )
          .wrapBlock(type)
      } else {
        change.setBlocks('list-item').wrapBlock(type)
      }
    }

    this.onChange(change)
  }

  render() {
    return (
      <div>
        {this.renderToolbar()}
        {this.renderEditor()}
      </div>
    )
  }

  renderToolbar = () => {
    return (
      <div className="menu toolbar-menu">
        {this.renderMarkButton('bold', 'format_bold')}
        {this.renderMarkButton('italic', 'format_italic')}
        {this.renderMarkButton('underlined', 'format_underlined')}
        {this.renderMarkButton('code', 'code')}
        {this.renderBlockButton('heading-one', 'looks_one')}
        {this.renderBlockButton('heading-two', 'looks_two')}
        {this.renderBlockButton('block-quote', 'format_quote')}
        {this.renderBlockButton('numbered-list', 'format_list_numbered')}
        {this.renderBlockButton('bulleted-list', 'format_list_bulleted')}
      </div>
    )
  }

  renderMarkButton = (type, icon) => {
    const isActive = this.hasMark(type)
    const onMouseDown = event => this.onClickMark(event, type)

    return (
      <span className="button" onMouseDown={onMouseDown} data-active={isActive}>
        <span className="material-icons">{icon}</span>
      </span>
    )
  }

  renderBlockButton = (type, icon) => {
    const isActive = this.hasBlock(type)
    const onMouseDown = event => this.onClickBlock(event, type)

    return (
      <span className="button" onMouseDown={onMouseDown} data-active={isActive}>
        <span className="material-icons">{icon}</span>
      </span>
    )
  }

  renderEditor = () => {
    return (
      <div className="editor">
        <Editor
          placeholder="Enter some rich text..."
          value={this.state.value}
          onChange={this.onChange}
          onKeyDown={this.onKeyDown}
          renderNode={this.renderNode}
          renderMark={this.renderMark}
          spellCheck
          autoFocus
        />
      </div>
    )
  }

  renderNode = props => {
    const { attributes, children, node } = props
    switch (node.type) {
      case 'block-quote':
        return <blockquote {...attributes}>{children}</blockquote>
      case 'bulleted-list':
        return <ul {...attributes}>{children}</ul>
      case 'heading-one':
        return <h1 {...attributes}>{children}</h1>
      case 'heading-two':
        return <h2 {...attributes}>{children}</h2>
      case 'list-item':
        return <li {...attributes}>{children}</li>
      case 'numbered-list':
        return <ol {...attributes}>{children}</ol>
    }
  }

  renderMark = props => {
    const { children, mark } = props
    switch (mark.type) {
      case 'bold':
        return <strong>{children}</strong>
      case 'code':
        return <code>{children}</code>
      case 'italic':
        return <em>{children}</em>
      case 'underlined':
        return <u>{children}</u>
    }
  }
}

const container = document.createElement("div");
document.body.appendChild(container);
ReactDOM.render(
  <div className="example">
    <RichTextExample />
  </div>,
  container
);

```

**main.css**

```
:not(pre)>code,pre{background-color:#eee}input,td{border:2px solid #ddd}.menu>*,.tab{display:inline-block}.toolbar-menu,.toolbar-menu .search{position:relative}html,input,textarea{font-family:Roboto,sans-serif;line-height:1.4;background:#eee}body,p{margin:0}pre{padding:10px;white-space:pre-wrap}:not(pre)>code{font-family:monospace;padding:3px}img{max-width:100%;max-height:20em}img.active{box-shadow:0 0 0 2px #00f}blockquote{border-left:2px solid #ddd;margin-left:0;margin-right:0;padding-left:10px;color:#aaa;font-style:italic}blockquote[dir=rtl]{border-left:none;padding-left:0;padding-right:10px;border-right:2px solid #ddd}table{border-collapse:collapse}td{padding:10px}input{box-sizing:border-box;font-size:.85em;width:100%;padding:.5em;background:#fafafa}input:focus{outline:0;border-color:#00f}.material-icons{font-size:18px;vertical-align:text-bottom}.nav{padding:10px 15px;color:#aaa;background:#000}.nav-title{margin-right:.5em}.nav-links{float:right}.nav-link{margin-left:1em;color:#aaa;text-decoration:none}.nav-link:hover{color:#fff;text-decoration:underline}.tabs{padding:15px;background-color:#222;text-align:center;margin-bottom:30px}.tab.active,.tab:hover{background:#333}.tab{color:#777;text-decoration:none;padding:.2em .5em;border-radius:.2em;margin-bottom:.2em}.tab+.tab{margin-left:.5em}.tab.active{color:#fff}.error,.example{max-width:42em;margin:0 auto 20px;padding:20px}.example{background:#fff}.error{background:#fffae0}.error .info{background:#fbf1bd;white-space:pre;overflow-x:scroll;margin-bottom:0}.editor>*>*+*{margin-top:1em}.menu>*+*{margin-left:15px}.button{color:#ccc;cursor:pointer}.button[data-active=true]{color:#000}.toolbar-menu{padding:1px 18px 17px;margin:0 -20px 20px;border-bottom:2px solid #eee}.toolbar-menu .search-icon{position:absolute;top:.5em;left:.5em;color:#ccc}.toolbar-menu .search-box{padding-left:2em;width:100%}.hover-menu{padding:8px 7px 6px;position:absolute;z-index:1;top:-10000px;left:-10000px;margin-top:-6px;opacity:0;background-color:#222;border-radius:4px;transition:opacity .75s}.hover-menu .button{color:#aaa}.hover-menu .button[data-active=true]{color:#fff}.emoji.selected{outline:#00f solid 2px}.check-list-item+.check-list-item{margin-top:0}.check-list-item{display:flex;flex-direction:row;align-items:center}.check-list-item.checked{opacity:.666;text-decoration:line-through}.check-list-item>span:first-child{margin-right:.75em}.check-list-item>span:last-child{flex:1}.check-list-item>span:last-child:focus{outline:0}.word-counter{margin-top:10px;padding:12px;background-color:#ebebeb;display:inline-block}
```

#### The JSFiddle problem

This is what I see when I try to load the JSFiddle ([https://jsfiddle.net/fj9dvhom/332/](https://jsfiddle.net/fj9dvhom/332/)) that I started in IE11. I'm not sure what the problem is.

![image](https://user-images.githubusercontent.com/742348/38870445-c422e99a-4245-11e8-8c60-5eddf4dd768b.png)

**Comment by ProductiveRage** [comment] 2018-04-17 14:07
I've tested in Edge (Microsoft Edge 41.16299.248.0) and problem does not occur - just in case that information is helpful to anyone!

**Comment by ProductiveRage** [comment] 2018-04-17 17:00
I'm guessing that this is something to do with the workaround for IE11 not supporting "Selection.setBaseAndExtent" -

[github.com/ianstormtaylor/slate/search?q=setBaseAndExtent](https://github.com/ianstormtaylor/slate/search?q=setBaseAndExtent)

I'm new to this code base and so very much still in the poking around and guessing phase.. but if anyone can confirm or deny (or suggestion improvements) then that would be very welcome! :)

**Comment by sethmcleod** [comment] 2018-09-12 19:49
@ProductiveRage are you able to test with the latest version of Slate packages and see if you can reproduce the issue? This has been an open issue with our application for a while since our customers use IE11, but it seems like it's been resolved in one of the recent updates.

**Comment by brendancarney** [comment] 2019-03-02 20:49
I tested IE11 on Browserstack on the latest version and it appears this is fixed. @ProductiveRage if you can still reproduce the issue, let us know and we can reopen.

**Closed by brendancarney** 2019-03-02 20:49 UTC
Labels: bug, ♥ help please, ⚑ cross platform
