### ISSUE TITLE
insert, undo, undo, insert bug

### ISSUE THREAD

**Issue by chrsan** [ianstormtaylor/slate#1673] opened 2018-02-23 14:01 UTC
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

An exception is thrown when inserting a character, performing a couple of undos and then trying to insert another character. I think it's related to the `startKey` being `null` in `Changes::setTextInRange`.

1. Start with a new empty document
2. Insert a character
3. Press `mod+u` to undo
4. Press `mod+u` to undo again
5. Insert a character

Open the JavaScript console to see the stack trace

[https://jsfiddle.net/fj9dvhom/146/](https://jsfiddle.net/fj9dvhom/146/)

I had no luck creating a GIF, but the JSFiddle reproduces the bug in `componentDidMount`.

slate 0.33.0
slate-react 0.12.0
Chrome
OS X

#### What's the expected behavior?

That no exception is thrown, and that the character at step 5 above will be inserted.

**Comment by CameronAckermanSEL** [comment] 2018-02-24 04:03
Hey @chrsan, the fiddle here actually fails at the first `insertText` operation because there is no selection in the `value`. All of these "Current Value Change" functions assume that there is some selection in the document before they are called, and if there isn't any such selection then they throw with a null key error.

The error you describe is reproducible with the steps in the report, though, and they fail for the same reason. The selection is lost because the second undo will undo the `set_selection` operation that applied the selection to the `value`, and then `insertText` breaks despite the editor component appearing to have focus.

There's a couple of ways to work around this:

1. You could write some logic that ignores operation lists on the `change.value.undos` stack that only contain `set_selection` operations, but undoes them along with changes that are something other than `set_selection` changes. (I kinda think that should be default behavior but I'm not sure if that's a sane opinion)
2. You could write some logic that ensures there is some selection on the editor at all times. `editor.focus()` is a pretty cheap way to do this.

That being said, I think there's a similar report about this somewhere on the issue log (though I can't find it), and I don't have a well informed opinion on what the fix should be.

Hope this helps you

**Comment by chrsan** [comment] 2018-02-26 10:02
Thanks @CameronAckermanSEL, I also noticed that the fiddle didn't work as I initially thought it would, but as you write the error is reproducible given the steps I've outlined. Right now I've created a proxy to intercept some calls via the history due to using Teletype for collaborative text, but I wanted to use the default logic for everything else. I think the default behaviour that causes an exception right now is kind of strange. I mean, a normal user might press an undo key combo multiple times, and that should just work IMHO.

**Comment by CameronAckermanSEL** [comment] 2018-02-26 17:32
I think maybe the select caused by `editor.focus()` shouldn't be persisted to the `change.value.history.undos` collection, and this would remove the ability to undo at the very least the initial select within the editor. Not sure what sort of consequences that would have.

**Comment by ianstormtaylor** [comment] 2019-11-28 02:43
I believe that this may be fixed by https://github.com/ianstormtaylor/slate/pull/3093, which has changed a *lot* of the logic in Slate and `slate-react` especially. I'm going to close this out, but as always, feel free to open a new issue if it persists for you. Thanks for understanding.

**Closed by ianstormtaylor** 2019-11-28 02:43 UTC
