### ISSUE TITLE
Clicking on an editor doesn't always give focus

### ISSUE THREAD

**Issue by quentez** [ianstormtaylor/slate#2137] opened 2018-08-29 20:52 UTC
#### Do you want to request a _feature_ or report a _bug_?

I'm reporting a bug: when using multiple editors on the same page, moving the focus from one editor to the next with the pointer is unreliable.

#### What's the current behavior?

With more than one editor on the same page, clicking from one editor to another does not always give it the focus. The behavior is non-deterministic (as a far as I can tell), and it sometimes works.

This can be reproduced on the `Syncing Operations` example on the [SlateJS website](https://www.slatejs.org/#/syncing-operations).
(For this reason, I'm not including a Fiddle).

![issue gif](https://user-images.githubusercontent.com/504055/44814561-fc854480-ab91-11e8-8bb1-fa7358a1a388.gif)

My setup:
- MacOS `10.14`
- Chrome `68.0.3440.106`
- Slate `0.40.2`

#### What's the expected behavior?

The focus should reliably move to an editor when clicking on it.

**Comment by bryanph** [comment] 2018-08-30 13:37
Probably related to #2097

**Comment by Mythli** [comment] 2018-08-31 20:32
I can confirm this. Having two editor components with just the "getting started" editor renders one editor unusable.

**Comment by ericedem** [comment] 2018-09-11 02:57
@quentez Do you still see this behavior? I can't reproduce and I think it may have been fixed in https://github.com/ianstormtaylor/slate/pull/2150

**Closed** 2018-11-08 00:45 UTC
Labels: bug, ♥ help please

**Comment by Saebyuckbaan** [comment] 2019-01-11 16:40
I still seeing this issue on 
slate: "0.44.9"
slate-react: '0.21.15"

**Comment by jrm2k6** [comment] 2019-02-03 20:05
I am still seeing the same issue with:
```
slate@0.44.10
slate-react@0.21.16
```

**Comment by FezVrasta** [comment] 2020-04-06 15:28
![Kapture 2020-04-06 at 16 39 16](https://user-images.githubusercontent.com/5382443/78575711-0110e500-782c-11ea-9df9-826daead1011.gif)

I think I'm reproducing the same issue, see the above gif.

**Comment by FezVrasta** [comment] 2020-04-14 17:57
@CameronAckermanSEL may this issue get reopened?

**Comment by CameronAckermanSEL** [comment] 2020-04-19 22:53
Hey @FezVrasta , this original issue was related to a long deprecated version of slate. I think it’d make more sense to open something new with some fresh information. Happy to reopen it though if you feel strongly that the same conditions are true. Also, see this https://github.com/ianstormtaylor/slate/issues/3380#issuecomment-612432934, it might be related?
