### ISSUE TITLE
Inlines causes firefox to crash

### ISSUE THREAD

**Issue by gracicot** [ianstormtaylor/slate#2606] opened 2019-02-19 22:30 UTC
#### Do you want to request a _feature_ or report a _bug_?

Bug

> Name: Firefox
> Version: 65.0.1
> Compile ID: 20190211233335
> Update Channel: release
> User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:65.0) Gecko/20100101 Firefox/65.0
> Operating System: Darwin 17.7.0

#### What's the current behavior?

The application crashes.

[Live example](https://codesandbox.io/s/1qp16q43yj)

![screenshot](https://i.imgur.com/BhjLnG4.png)

#### What's the expected behavior?
Displaying the example like in chrome.

**Comment by isubasti** [comment] 2019-02-20 00:50
it's codesandbox problem with their polyfill https://github.com/inf3rno/error-polyfill/issues/32

**Comment by ericedem** [comment] 2019-02-21 17:11
@gracicot It looks like codesandbox fixed their issue. Can you still reproduce this?

**Comment by gracicot** [comment] 2019-02-21 19:44
I still get the issue on codesandbox, but in a fresh setup everything works fine.

**Comment by ianstormtaylor** [comment] 2019-02-26 17:54
Sounds like this is something that needs to be fixed on their end, so I'm going to close for now.

**Closed by ianstormtaylor** 2019-02-26 17:54 UTC
