### ISSUE TITLE
Slate unfocusing and refocusing every keystroke

### ISSUE THREAD

**Issue by marktron** [ianstormtaylor/slate#2725] opened 2019-05-01 00:02 UTC
#### Do you want to request a _feature_ or report a _bug_?

Report a bug

#### What's the current behavior?

On the Mac in Chrome and Safari, the current release of Slate (0.45.1) shows an undesirable effect where every time I press a key the spellcheck fires and my MacBook Pro's touch bar switches from the suggested words display to the default browser touch bar display. This suggests to me that on keydown the Slate editor loses focus, then regains it on keyup.

This behavior is incredibly distracting and makes it difficult to use Slate for writing any length of text longer than a few words. Even without the touch bar display issue, having the spell check underline most of your words as you type is not useful (and affects users without the touch bar)

Here's a link to a video since you can't capture the Touch Bar in a gif: https://www.dropbox.com/s/gx2pfob0gbucu4b/slate-keyboard.mov?dl=0

I was able to recreate this issue both in my own local Slate builds and also on the examples at https://www.slatejs.org (which was used in my video example).

#### What's the expected behavior?

When I press a key, the spell check should appear after a word is completed instead of on every keydown, and the touch bar should always show the spelling suggestions until the editor loses focus.

**Comment by ianstormtaylor** [comment] 2019-05-01 03:12
Hey @marktron, thanks for reporting this. I totally agree with this being an issue. I think this is actually a duplicate of https://github.com/ianstormtaylor/slate/issues/2061, so I'm going to close this in favor of that one. Feel free to comment over there with any other info! The bit about the touchbar is new to me, and a good thing to account for.

**Closed by ianstormtaylor** 2019-05-01 03:12 UTC
Labels: bug
