### ISSUE TITLE
Slate zero width is rendered with UTF8 BOM symbol

### ISSUE THREAD

**Issue by glebtv** [ianstormtaylor/slate#2722] opened 2019-04-30 03:34 UTC
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
Slate currently renders data-slate-zero-width elements with UTF8 BOM character inside in Chrome

This is very annoying for users copying, for example, links text from Slate, as BOM character is inserted after the link.

#### Repoduction:

https://www.slatejs.org/#/links
Delete preset content
~~Add a link~~ paste a link over some text
UTF8 BOM &#65279; ```&#65279;``` (```\xEF\xBB\xBF``` or ```&#xFEFF;```) appears after the link

![DeepinScreenshot_select-area_20190430063244](https://user-images.githubusercontent.com/1041407/56939580-ced21000-6b11-11e9-827a-fd4e755be28a.png)

#### What's the expected behavior?

Content copied from Slate does not contain garbage characters

**Comment by glebtv** [comment] 2019-04-30 03:42
This is an EXTREMELY nasty character to add to a text editor
https://en.wikipedia.org/wiki/Byte_order_mark
https://medium.freecodecamp.org/a-quick-tale-about-feff-the-invisible-character-cd25cd4630e7

This is NOT a zero-width space (which seems to be the intended character)

Related: #1971 #2597

**Comment by ianstormtaylor** [comment] 2019-04-30 19:07
Hey, thanks for reporting this. I think this is actually a duplicate of https://github.com/ianstormtaylor/slate/issues/2597, so I'm going to close this in favor of that one. Feel free to comment over there with any other info!

**Closed by ianstormtaylor** 2019-04-30 19:07 UTC

**Comment by YaoKaiLun** [comment] 2021-06-15 07:24
I found that this is happen in old version of Chrome, like v83.
