### ISSUE TITLE
Ctrl + K on last node throws an error (deleteForwardAtRange)

### ISSUE THREAD

**Issue by kennethtruong** [ianstormtaylor/slate#608] opened 2017-02-16 00:06 UTC
Delete `deleteForwardAtRange` will throw an error if you try to do ctrl + K on the last node. 

If you try on any of the examples in http://slatejs.org/ it will throw an error

**Comment by vpontis** [comment] 2017-04-09 22:00
Hi @kennethtruong, I checked this out and I wasn't able to reproduce it. Can you submit more information? Maybe the console output, your browser/OS, or some more specific way of reproducing this bug.

**Comment by kennethtruong** [comment] 2017-04-10 04:45
You can press Ctrl + K on the last word inside any of the editors on http://slatejs.org/

**Comment by vpontis** [comment] 2017-04-10 06:17
Ah, yea that looks like it's working. I was trying to do Ctrl + K w/ the cursor at the end of the block. That works totally fine. But Ctrl + K in the last block throws the following.

```
build.prod.js:19425 Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.Transforms.deleteForwardAtRange (http://slatejs.org/build.prod.js:19425:33)
    at Transform.(anonymous function) [as deleteForwardAtRange] (http://slatejs.org/build.prod.js:14962:32)
    at Object.Transforms.deleteLineForwardAtRange (http://slatejs.org/build.prod.js:19294:13)
    at Transform.(anonymous function) [as deleteLineForwardAtRange] (http://slatejs.org/build.prod.js:14962:32)
    at Object.Transforms.deleteLineForward (http://slatejs.org/build.prod.js:18520:13)
    at Transform.(anonymous function) [as deleteLineForward] (http://slatejs.org/build.prod.js:14962:32)
    at onKeyDownK (http://slatejs.org/build.prod.js:15785:30)
    at Object.onKeyDown (http://slatejs.org/build.prod.js:15495:16)
    at Stack.(anonymous function) [as onKeyDown] (http://slatejs.org/build.prod.js:13468:37)
    at Object._this.(anonymous function) [as onKeyDown] (http://slatejs.org/build.prod.js:7220:70)
```

**Comment by yalu** [comment] 2017-04-10 08:31
I bumped into this a little while ago, couldn't describe clearly how to replicate, figured it would be fixed by numerous changes happening at the time(and recently), and so didn't report.

**Comment by vpontis** [comment] 2017-04-13 08:53
This is a `bug` again @ianstormtaylor

**Comment by vpontis** [comment] 2017-04-13 09:09
This diff works to fix the problem but I don't think this is the right way of doing it...


```diff --git a/src/transforms/at-range.js b/src/transforms/at-range.js
index 0ebf1af..620a001 100644
--- a/src/transforms/at-range.js
+++ b/src/transforms/at-range.js
@@ -470,14 +470,19 @@ Transforms.deleteForwardAtRange = (transform, range, n = 1, options = {}) => {
   let offset = focusOffset
   let traversed = text.length - focusOffset
 
-  while (n > traversed) {
-    node = document.getNextText(node.key)
-    const next = traversed + node.length
-    if (n <= next) {
-      offset = n - traversed
-      break
-    } else {
-      traversed = next
+  const nextNode = document.getNextBlock(node.key)
+  if (!nextNode) {
+    offset = text.length
+  } else {
+    while (n > traversed) {
+      node = document.getNextText(node.key)
+      const next = traversed + node.length
+      if (n <= next) {
+        offset = n - traversed
+        break
+      } else {
+        traversed = next
+      }
     }
   }
 
```

@ianstormtaylor what is the `n` argument in `deleteForwardAtRange` supposed to do? It looks like it's getting called w/ the `focusOffset` of the node but the comment below makes it sound like it's supposed to be the num characters to delete

```  // If the remaining characters to the end of the node is greater than or equal
  // to the number of characters to delete, just remove the characters forwards
  // inside the current node.
  if (n <= (text.length - focusOffset)) {
    range = range.merge({
      focusOffset: focusOffset + n
    })

    transform.deleteAtRange(range, { normalize })
    return
  }```

**Comment by ianstormtaylor** [comment] 2017-04-24 19:14
Yeah `n` should be the number of characters to delete

**Comment by ianstormtaylor** [comment] 2018-08-08 00:16
This should be fixed in the latest Slate.

**Closed by ianstormtaylor** 2018-08-08 00:16 UTC
Labels: bug, ♥ help please
