### ISSUE TITLE
Pasting any string containing " and no spaces throws an error

### ISSUE THREAD

**Issue by darkyshiny** [ianstormtaylor/slate#817] opened 2017-05-16 09:57 UTC
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What's the current behavior?
Pasting " anywhere in slate throws the following error.
![pasteerror](https://cloud.githubusercontent.com/assets/16773900/26141303/7abad5b4-3adb-11e7-897c-20edc8fde665.JPG)
Here is a very basic jsfiddle where the error can be reproduced: https://jsfiddle.net/4wzp6hxa/3/

Tested on Windows in Firefox with the latest version of Slate

#### What's the expected behavior?
" should be pasted into the editor.

**Comment by darkyshiny** [comment] 2017-05-16 10:03
Just noticed that if the string contains at least one space the error is not thrown. Ex. 'asd asd"'

**Comment by malloryerik** [comment] 2017-05-16 17:13
Couldn't reproduce the bug on Mac in Chrome, Safari, or Firefox.
" pasted as expected.

**Comment by darkyshiny** [comment] 2017-05-17 06:37
Looked at it some more today and can only reproduce in Firefox think the error I had in Chrome was entirely different (Sorry yesterday was a looong day). Updated the original comment with a new error stack

**Comment by danburzo** [comment] 2017-08-15 16:35
Clarification: this seems to be the case in Firefox when copying a `"` character from within Slate, and then trying to paste it. Clipboard reveals:

```
<span data-slate-fragment="JTdCJTIyZGF0YSUyMiUzQSU3QiU3RCUyQyUyMmtpbmQlMjIlM0ElMjJkb2N1bWVudCUyMiUyQyUyMm5vZGVzJTIyJTNBJTVCJTdCJTIyZGF0YSUyMiUzQSU3QiU3RCUyQyUyMmtpbmQlMjIlM0ElMjJibG9jayUyMiUyQyUyMmlzVm9pZCUyMiUzQWZhbHNlJTJDJTIydHlwZSUyMiUzQSUyMnBhcmFncmFwaCUyMiUyQyUyMm5vZGVzJTIyJTNBJTVCJTdCJTIya2luZCUyMiUzQSUyMnRleHQlMjIlMkMlMjJyYW5nZXMlMjIlM0ElNUIlN0IlMjJraW5kJTIyJTNBJTIycmFuZ2UlMjIlMkMlMjJ0ZXh0JTIyJTNBJTIyJTVDJTIyJTIyJTJDJTIybWFya3MlMjIlM0ElNUIlNUQlN0QlNUQlN0QlNUQlN0QlNUQlN0Q=">"</span>
```

for mime `text/html`.

**Comment by danburzo** [comment] 2017-08-15 16:45
The problem was with the `FRAGMENT_MATCHER` regex matching the `data-slate-fragment` too greedily. Fixed in PR above.

**Closed** 2017-08-15 17:39 UTC
Labels: bug, cross-platform, ⭐  help-please
