### ISSUE TITLE
onKeyDownEnter fails when using inline nodes

### ISSUE THREAD

**Issue by inyono** [ianstormtaylor/slate#472] opened 2016-12-01 14:34 UTC
see https://jsfiddle.net/qovz9jqf/1/

"Hello world" is a text node, "whatever" is created by an inline node and "." is also a text node. When placing the cursor before "." and pressing enter, Slate creates a new paragraph block containing the inline node (instead of the expected empty paragraph).

**Comment by ianstormtaylor** [comment] 2016-12-01 20:14
Hey @inyono thanks for reporting this. I think it's a duplicate of https://github.com/ianstormtaylor/slate/issues/466, so I'm going to close and use that one as the canonical issue.

**Closed by ianstormtaylor** 2016-12-01 20:14 UTC
Labels: bug
