### ISSUE TITLE
slate-react text render still get error in ie11

### ISSUE THREAD

**Issue by ThomasChan** [ianstormtaylor/slate#3013] opened 2019-09-10 08:43 UTC
#### Do you want to request a _feature_ or report a _bug_?

Report bug

#### What's the current behavior?

`slate-react/src/components/text.js#L18` the `leaves` is generated from `node.getLeaves` function, and `slate/src/models/text.js#L152` `getLeaves` function finally returned a immutable List, that's a `Object`, so ie11 still get error `Objects are not valid as a React child`

#### What's the expected behavior?

Modify slate-react text render function, make leaves toArray.

Should i make a pr?

**Comment by mmdonaldson** [comment] 2019-09-17 01:58
Can you reproduce in a codepen or jsfiddle?

**Comment by ThomasChan** [comment] 2019-09-17 13:41
@mmdonaldson unfortunately both codepen and jsfiddle do not support ie11, i can't provide online demo too, but i got my production's error screenshot in ie11 if you want see.

![屏幕快照 2019-09-17 下午9 36 40](https://user-images.githubusercontent.com/5715335/65046553-6df98600-d993-11e9-9f87-050cdf29b4e8.png)


And i'm 100% sure that error was throw by text.js#L152 which mentioned above, then i use my [commit](https://github.com/henglabs/slate/commit/465e8bab29f485a00fb5a0b8d434f91764fd0224) to webpack build, that error is gone.

**Comment by ianstormtaylor** [comment] 2019-11-28 02:32
As of https://github.com/ianstormtaylor/slate/pull/3093 (which was just merged), I believe this issue is no longer applicable, because a lot has changed. I'm going through and closing out any potential issues that are not out of date with the overhaul. Thanks for understanding.

**Closed by ianstormtaylor** 2019-11-28 02:32 UTC
