### ISSUE TITLE
Slate value is of type Node[]

### ISSUE THREAD

**Issue by lcswillems** [ianstormtaylor/slate#3448] opened 2020-01-20 08:58 UTC
#### What's the expected behavior?

I would like Slate value type to be equal to the type of the value I give it.

Making Slate generic would help I think.

**Comment by timbuckley** [comment] 2020-01-20 19:06
Related to (duplicate of?) #3416

**Comment by lcswillems** [comment] 2020-01-20 19:12
I am not sure

**Comment by martonlanga** [comment] 2020-01-20 20:11
Just in case: are you importing the Node type from slate? I've had conflicts like this before because there is also a built-in Node type. But importing it like this works for me: `import { Node } from 'slate'`

If you're trying to use a custom type, then ignore this.

**Comment by BrentFarese** [comment] 2020-07-24 21:26
Closing this as it's somewhat broad and not specific.  There are other issues too for making Slate's types more generic.  It is on the long-term roadmap.

**Closed by BrentFarese** 2020-07-24 21:26 UTC
