### ISSUE TITLE
having static content inside a custom block

### ISSUE THREAD

**Issue by jatins** [ianstormtaylor/slate#688] opened 2017-03-28 08:34 UTC
I discovered slate after weeks of playing around with draft. 

One of the use cases I have is having editing capabilities inside the custom blocks themselves. Similar to this: https://github.com/facebook/draft-js/issues/132

As you can see from the thread, it requires substantial effort in draft. 

How would you accomplish something like that in slate? Is it possible to have a slate `</Editor >` component itself inside a custom block component?

**Comment by ianstormtaylor** [comment] 2017-03-28 17:04
Hey @jatins good question. I haven't dug deeply into this myself, but I know others have so they might be able to give more context. (You might try asking in the Slack channel with some more context and people will respond.)

I've been curious about the check list use case though, which it sounds like that Draft.js thread was all about, so I just added a `check-lists` example to our examples. You can [check it out here](http://slatejs.org/#/check-lists?_k=a360i6).

It works because you can use `contenteditable="false"` to embed the check box, and then toggle the node's `data` when the checkbox value changes. I hope that helps!

**Comment by jatins** [comment] 2017-03-29 13:15
@ianstormtaylor Thanks for the response and that example! 

While that example seems to work fine for most part, it seems the `selection` gets messed up at times due to embedded content like a checkbox.

Here's a gif showing the behaviour: http://recordit.co/PiqFWRscA6 (I select the entire text of a check list item, and press delete, but only one char gets deleted)

In general the selection behaviour gets a little off with embedded content.

Any ideas what might be causing this?

**Comment by ianstormtaylor** [comment] 2017-03-29 17:38
Hey @jatins thanks for clarifying! I've just pushed up a few changes...

> Also, you can't delete the checkbox if there is no content before that: http://recordit.co/BWF0LvmmbZ

This one is actually by design, since there isn't the concept of "default" block in Slate, so the idea of "unsetting" a block back to its default needs to be handled at the application level. I've just updated the example though to add this functionality, it's pretty easy to add.

> While that example seems to work fine for most part, it seems the selection gets messed up at times due to embedded content like a checkbox.
> 
> Here's a gif showing the behaviour: http://recordit.co/PiqFWRscA6 (I select the entire text of a check list item, and press delete, but only one char gets deleted)

Very true! I've just added a fix that makes Slate skip over `contenteditable="false"` elements when trying to match a native selection to a Slate-specific one. This should eliminate a bunch of bugs there.

There is actually still at least one issue, in that clicking near the checkbox will select correctly the first time, but if you do it again, it will incorrectly allow the selection to be placed in next to it, because of the way that Slate handles "duplicate" selections currently.

I'm open to PR's that help fix this issue, and any other issue that may occur with these embedded `contenteditable="false"` sections. I think we're pretty close to it being fully functional.

**Comment by ianstormtaylor** [comment] 2017-08-01 20:51
This issue hasn't had a response in a while, and it's unclear if it's still present in the latest versions of Slate. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice that the bug is still happening, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!

**Closed by ianstormtaylor** 2017-08-01 20:51 UTC
Labels: bug, question, ⭐  help-please

**Comment by garretttaco** [comment] 2017-08-04 17:11
@ianstormtaylor You mentioned a slack for Slate channel but I cannot seem to find it. Would you mind providing a link?

**Comment by jatins** [comment] 2017-08-05 10:15
@garretttaco https://slate-js.slack.com
