### ISSUE TITLE
Lose focus after input Chinese in certain condition

### ISSUE THREAD

**Issue by djheart0710** [ianstormtaylor/slate#2594] opened 2019-02-13 01:44 UTC
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

JSFiddle Example:
https://jsfiddle.net/bzvw84tu/1/
reproduce process：
- add an sibling after Editor component
- delete all content in editor
- start to input Chinese, after click space, editor's value changes, but it loses focus

The weird thing is, if I put the sibling before Editor component, or just remove the Editor's placeholder props, or just input English words, It works perfect! Now I haven't find out what's going wrong, just knowing it may relates to placeholder props.

Environment: MacOS 10.14.2 /  Chrome 72.0.3626.96

#### What's the expected behavior?

Expected: No matter what inputs, what props passed to Editor, It should work as normal!

**Comment by djheart0710** [comment] 2019-02-19 03:18
Has anyone encountered this situation?

**Comment by ianstormtaylor** [comment] 2019-05-09 02:33
Hey, thanks for reporting this. I think this is actually a duplicate of https://github.com/ianstormtaylor/slate/issues/2368, so I'm going to close this in favor of that one. Feel free to comment over there with any other info!

**Closed by ianstormtaylor** 2019-05-09 02:33 UTC
