### ISSUE TITLE
Ctrl+ArrowKey cursor navigation not working properly inside blocks immediately before or after void blocks

### ISSUE THREAD

**Issue by ravi-braj** [ianstormtaylor/slate#2171] opened 2018-09-12 03:43 UTC
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?
Ctrl+arrowKey navigation to jump selection to the start of words not working properly inside blocks immediately before or after void blocks. If before, it will correctly move left to the beginning of the word, but will only move individual characters to the right. If after, it will correctly move right to the beginning of the next word, but will only move individual characters to the left.

This can be replicated on the slate image example

https://www.useloom.com/share/fd5992dcad0a4573993d556e6996a18b

#### What's the expected behavior?

The Ctrl+ArrowRight should move the cursor to the start of the next word. Ctrl+ArrowLeft should move the cursor to the start of the previous (or current) word.

**Comment by ericedem** [comment] 2018-09-12 12:39
Duplicate of #2069

**Comment by ianstormtaylor** [comment] 2018-09-18 01:13
Hey, thanks for reporting this. I think this is actually a duplicate of #2069, so I'm going to close this in favor of that one. Feel free to comment over there with any other info!

**Closed by ianstormtaylor** 2018-09-18 01:13 UTC
