### ISSUE TITLE
Cursor positioned wrong when typing with some Chinese input methods.

### ISSUE THREAD

**Issue by vylan** [ianstormtaylor/slate#2677] opened 2019-04-01 17:50 UTC
#### What's the current behavior?
The cursor won't change its position when typing each character, shown as the fellowing gif:

![jHR7ycP2nx](https://user-images.githubusercontent.com/8390531/55347774-2d42a900-54e8-11e9-8ccb-17131757fa45.gif)
System: Mac Pro, Browser: Chrome 73.

#### What's the expected behavior?
The cursor should change its position after every character typed.
![OTN4uPVfJc](https://user-images.githubusercontent.com/8390531/55348316-87903980-54e9-11e9-8d57-c6ff831e5922.gif)

**Comment by hecor** [comment] 2019-04-09 03:28
I have the same problem.

**Comment by vylan** [comment] 2019-04-19 11:06
@hecor I've transferred to ckeditor5, cause of slate's immatureness.

**Comment by hecor** [comment] 2019-04-22 11:31
@ianstormtaylor Please help，I found it only happens when I input at the end of a paragraph. It works fine if input at the middle of paragraph.

**Comment by hecor** [comment] 2019-04-23 02:51
For those have same problem, the following works well, thank @yunwuxin 
https://github.com/ianstormtaylor/slate/pull/2415/files

**Comment by ianstormtaylor** [comment] 2019-05-09 02:16
Hey, thanks for reporting this. I think this is actually a duplicate of https://github.com/ianstormtaylor/slate/issues/2368, so I'm going to close this in favor of that one. Feel free to comment over there with any other info!

**Closed by ianstormtaylor** 2019-05-09 02:16 UTC
