### ISSUE TITLE
`setBlock()` leads to glitches in editor

### ISSUE THREAD

**Issue by MaxGfeller** [ianstormtaylor/slate#402] opened 2016-10-24 10:32 UTC
This is something that can be reproduced in `0.14` as well as older versions of slate. Setting a block in `onChange` leads to weird glitches in the editor, as seen in this recording:

![in action](http://i.giphy.com/l0MYLCSq4f65TweoE.gif)

This code can be used to reproduce the issue:

``` javascript
import { render } from 'react-dom'
import React from 'react'
import { Editor, Plain } from 'slate'

const Main = React.createClass({
  getInitialState () {
    return { editorState: Plain.deserialize('') }
  },
  render () {
    return (
      <Editor
        state={this.state.editorState}
        onChange={(editorState) => {
          let next = editorState
            .transform()
            .setBlock({ data: { foo: 'bar' } })
            .apply()
          this.setState({ editorState: next })
        }}
      />
    )
  }
})

render(
  <Main />,
  document.getElementById('main')
)
```

**Comment by arekkas** [comment] 2016-11-02 14:46
This is because the `isNative` flag is set to false by the `setBlock` transform operation. This behaviour can be reproduced easily with the following demonstration that does not rely on the setBlock operation:

```jsx
import { render } from 'react-dom'
import React from 'react'
import { Editor, Plain } from 'slate'

const Main = React.createClass({
  getInitialState () {
    return { editorState: Plain.deserialize('') }
  },
  render () {
    return (
      <Editor
        state={this.state.editorState}
        onChange={(editorState) => {
          let next = editorState.merge({ isNative: false }) 
          this.setState({ editorState: next })
        }}
      />
    )
  }
})

render(
  <Main />,
  document.getElementById('main')
)
```

**Comment by arekkas** [comment] 2016-11-13 17:10
You could try wrapping `this.setState` in `setTimeout`

**Comment by arekkas** [comment] 2016-11-18 10:00
I simply think you shouldn't do this in onChange, maybe onDocumentChange or something like it instead?

**Comment by ianstormtaylor** [comment] 2017-08-01 20:52
This issue hasn't had a response in a while, and it's unclear if it's still present in the latest versions of Slate. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice that the bug is still happening, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!

**Closed by ianstormtaylor** 2017-08-01 20:52 UTC
Labels: question
