### ISSUE TITLE
prevProps.editor equals props.editor in shouldNodeComponentUpdate

### ISSUE THREAD

**Issue by grsmvg** [ianstormtaylor/slate#2269] opened 2018-10-16 13:50 UTC
See this bug in action here:

https://jsfiddle.net/gersomvg/fj9dvhom/2480/

I can try to PR this myself, after this is confirmed by someone else as a bug.

**Comment by isubasti** [comment] 2018-10-16 23:46
duplicate of https://github.com/ianstormtaylor/slate/issues/2159

**Comment by grsmvg** [comment] 2018-10-17 08:17
Ah, sharp. I didn't look back that far

**Comment by ianstormtaylor** [comment] 2018-10-25 16:38
Closing in favor of #2159.

**Closed by ianstormtaylor** 2018-10-25 16:38 UTC
