### ISSUE TITLE
Type Enter at end of first line in Syntax Highlighting Demo Throws Error

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate#2616] opened 2019-02-26 00:55 UTC
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

If you hit ENTER at the end of the first code line which is a comment in the demo here:

https://www.slatejs.org/#/code-highlighting

The result is this error:

```
TypeError: Cannot read property 'size' of null
    at We (https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:26219)
    at Object.Le [as compare] (https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:25121)
    at https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:173417
    at https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:242097
    at pa.__iterate (https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:235496)
    at r.Ia.r.__iterateUncached (https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:242066)
    at ue (https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:215563)
    at r.U.__iterate (https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:214394)
    at r.forEach (https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:259439)
    at https://www.slatejs.org/main-e8e0520e642ae32de49e.js:1:233254
```

It only happens on the first line.

#### What's the expected behavior?

Should not throw an error.

**Comment by brendancarney** [comment] 2019-03-02 19:08
I believe this is a duplicate of #2319

**Comment by thesunny** [comment] 2019-03-03 17:49
It may be a duplicate, but it seems unclear because the bugs present themselves differently.

- One is hitting enter twice at the second-last position of any line
- This one is hitting enter once at the last position of the first line

I suggest we keep this open until someone can confirm that they are the same.

**Closed** 2019-04-18 22:10 UTC
Labels: bug
